LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/BVESingleGaussianVortex.f90 File Reference
/Users/pabosle/lpm-v2/BVESingleGaussianVortex.f90 File Reference
Driver program for the problem of a single Gaussian vortex on a rotating sphere.
Detailed Description
Driver program for the problem of a single Gaussian vortex on a rotating sphere.
Author
Peter Bosler, Sandia National Laboratories Center for Computing Research
Driver program for the problem of a single Gaussian vortex on a rotating sphere.
Demonstrates the solution of an inviscid incompressible flow on the sphere using SphereBVE, SphereBVESolver, Refinement, and SSRFPACKRemesh.
Late-time vorticity distribution of an initially Gaussian vortex on a rotating sphere (coarse resolution).
Definition in file BVESingleGaussianVortex.f90.
Functions/Subroutines
program bvesinglegaussianvortexdriver
pure real(kreal) function initlattracer (x0, y0, z0)
Returns the latitude of a Lagrangian coordinate.
subroutine setabsolutetolerances (aBVEMesh, circTol, lagVarTol)
Sets absolute tolerances for AMR criteria based on an initially uniform mesh with corresponding vorticity distribution.
real(kreal) function gaussianvortexvorticity (x, y, z)
Vorticity distribution function, used to define initial conditions and for indirect vorticity interpolation to \(t = 0 \).
real(kreal) function setgaussconst (aBVEMesh)
Defines a constant to ensure that the total integral of vorticity is zero over the whole sphere.
subroutine readnamelistfile (rank)
Reads a namelist file, which must be specified on the command line at run-time execution as the first argument, to define the user-specified variables for this driver program.
subroutine initlogger (log, rank)
Initializes a Logger module for this executable program.
Function/Subroutine Documentation
program bvesinglegaussianvortexdriver ()
Definition at line 1 of file BVESingleGaussianVortex.f90.
References betaplanemeshmodule::addtracers(), numberkindsmodule::cubed_sphere_seed, gaussianvortexvorticity(), numberkindsmodule::icos_tri_sphere_seed, initlattracer(), initlogger(), fieldmodule::insertscalartofield(), refinementmodule::iteratemeshrefinementonevariableandflowmap(), ssrfpackremeshmodule::lagrangianremeshbvewithvorticityfunction(), mpisetupmodule::loadbalance(), numberkindsmodule::numprocs, betaplanemeshmodule::outputtovtk(), particlesmodule::physcoord(), numberkindsmodule::procrank, readnamelistfile(), refinementmodule::scalarintegralrefinement(), setabsolutetolerances(), setgaussconst(), betaplanemeshmodule::setinitialvorticityonmesh(), ssrfpackinterfacemodule::setsigmaflag(), betaplanemeshmodule::setstreamfunctionsonmesh(), betaplanemeshmodule::totalenstrophy(), betaplanemeshmodule::totalke(), loggermodule::trace_logging_level, and numberkindsmodule::write_unit_1.
real(kreal) function bvesinglegaussianvortexdriver::gaussianvortexvorticity (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Vorticity distribution function, used to define initial conditions and for indirect vorticity interpolation to \(t = 0 \).
Conforms to the numberkindsmodule::scalarFnOf3DSpace interface.
Parameters
[in] x
[in] y
[in] z
Returns
initial vorticity value at at location (x,y,z)
Definition at line 313 of file BVESingleGaussianVortex.f90.
pure real(kreal) function bvesinglegaussianvortexdriver::initlattracer (real(kreal), intent(in) x0, real(kreal), intent(in) y0, real(kreal), intent(in) z0)
Returns the latitude of a Lagrangian coordinate.
Conforms to numberkindsmodule::scalarFnOf3DSpace interface.
Definition at line 285 of file BVESingleGaussianVortex.f90.
subroutine bvesinglegaussianvortexdriver::initlogger (type(logger), intent(inout) log, integer(kint), intent(in) rank)
Initializes a Logger module for this executable program.
Output is controlled by message priority level and MPI rank.
Parameters
[in] log Logger module to initialize
[in] rank MPI rank
Definition at line 445 of file BVESingleGaussianVortex.f90.
References loggermodule::error_logging_level.
subroutine bvesinglegaussianvortexdriver::readnamelistfile (integer(kint), intent(in) rank)
Reads a namelist file, which must be specified on the command line at run-time execution as the first argument, to define the user-specified variables for this driver program.
Only MPI rank 0 reads the file; it then broadcasts the relevant data to all other ranks.
Parameters
[in] rank MPI rank
Definition at line 343 of file BVESingleGaussianVortex.f90.
References numberkindsmodule::cubed_sphere_seed, loggermodule::error_logging_level, numberkindsmodule::icos_tri_sphere_seed, numberkindsmodule::read_unit, and loggermodule::warning_logging_level.
subroutine bvesinglegaussianvortexdriver::setabsolutetolerances (type(bvemesh), intent(in) aBVEMesh, real(kreal), intent(inout) circTol, real(kreal), intent(inout) lagVarTol)
Sets absolute tolerances for AMR criteria based on an initially uniform mesh with corresponding vorticity distribution.
Parameters
[in] aBVEMesh SphereBVE mesh
[in,out] circTol On input, relative tolerance (between 0 and 1). On output, absolute tolerance for circulation magnitude about a face.
[in,out] lagVarTol On input, relative tolerance (between 0 and 1). On output, absolute tolerance for Lagrangian variation magnitude on each face.
Definition at line 295 of file BVESingleGaussianVortex.f90.
References betaplanemeshmodule::maxcirculationmagnitudeperface(), and polymesh2dmodule::maxlagrangianvariationperface().
real(kreal) function bvesinglegaussianvortexdriver::setgaussconst (type(bvemesh), intent(in) aBVEMesh)
Defines a constant to ensure that the total integral of vorticity is zero over the whole sphere.
Parameters
[in] aBVEMesh SphereBVE mesh
Returns
C such that
\[ \int_S \zeta(\vec{x})\,dA = \int_{S} \zeta_G(\vec{x})\,dA - C = 0, \]
where \(\zeta_G \) is a Gaussian distribution on a sphere.
Definition at line 328 of file BVESingleGaussianVortex.f90.
References planarincompressiblesolvermodule::planesolver::mask, and numberkindsmodule::pi.