LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/BVESolidBody.f90 File Reference
/Users/pabosle/lpm-v2/BVESolidBody.f90 File Reference
Functions/Subroutines
program bvesolidbody
pure real(kreal) function,
dimension(3) exactposition (x0, y0, z0)
pure real(kreal) function solidbodyvorticity (x, y, z)
pure real(kreal) function,
dimension(3) solidbodyvelocity (x, y, z)
subroutine readnamelistfile (rank)
subroutine initlogger (log, rank)
Function/Subroutine Documentation
program bvesolidbody ()
Definition at line 1 of file BVESolidBody.f90.
References betaplanemeshmodule::addtracers(), numberkindsmodule::cubed_sphere_seed, exactposition(), numberkindsmodule::icos_tri_sphere_seed, initlogger(), fieldmodule::maxmagnitude(), fieldmodule::multiplyfieldbyscalar(), numberkindsmodule::numprocs, betaplanemeshmodule::outputtovtk(), numberkindsmodule::procrank, readnamelistfile(), betaplanemeshmodule::setinitialvorticityonmesh(), betaplanemeshmodule::setstreamfunctionsonmesh(), solidbodyvelocity(), solidbodyvorticity(), betaplanemeshmodule::totalenstrophy(), betaplanemeshmodule::totalke(), loggermodule::trace_logging_level, and numberkindsmodule::write_unit_1.
pure real(kreal) function, dimension(3) bvesolidbody::exactposition (real(kreal), intent(in) x0, real(kreal), intent(in) y0, real(kreal), intent(in) z0)
Definition at line 213 of file BVESolidBody.f90.
subroutine bvesolidbody::initlogger (type(logger), intent(inout) log, integer(kint), intent(in) rank)
Definition at line 322 of file BVESolidBody.f90.
References loggermodule::error_logging_level.
subroutine bvesolidbody::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 245 of file BVESolidBody.f90.
References numberkindsmodule::cubed_sphere_seed, loggermodule::error_logging_level, numberkindsmodule::icos_tri_sphere_seed, numberkindsmodule::read_unit, and loggermodule::warning_logging_level.
pure real(kreal) function, dimension(3) bvesolidbody::solidbodyvelocity (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Definition at line 237 of file BVESolidBody.f90.
pure real(kreal) function bvesolidbody::solidbodyvorticity (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Definition at line 231 of file BVESolidBody.f90.