LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/BetaPlaneGaussianVortex.f90 File Reference
/Users/pabosle/lpm-v2/BetaPlaneGaussianVortex.f90 File Reference
Functions/Subroutines
program betaplanegaussian
subroutine setabsolutetolerances (betaPlane, circTol, lagVarTol)
real(kreal) function gaussianvortexvorticity (x, y)
subroutine readnamelistfile (rank)
subroutine initlogger (log, rank)
Function/Subroutine Documentation
program betaplanegaussian ()
Definition at line 1 of file BetaPlaneGaussianVortex.f90.
References polymesh2dmodule::polymesh2d::amrlimit, gaussianvortexvorticity(), initlogger(), polymesh2dmodule::polymesh2d::initnest, refinementmodule::iteratemeshrefinementonevariableandflowmap(), bivarremeshmodule::lagrangianremeshbetaplanewithvorticityfunction(), mpisetupmodule::loadbalance(), betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, numberkindsmodule::numprocs, betaplanemeshmodule::outputtovtk(), numberkindsmodule::procrank, readnamelistfile(), spherebvemodule::bvemesh::rotationrate, refinementmodule::scalarintegralrefinement(), setabsolutetolerances(), betaplanemeshmodule::setinitialvorticityonmesh(), betaplanemeshmodule::setstreamfunctionsonmesh(), polymesh2dmodule::polymesh2d::t, betaplanemeshmodule::totalenstrophy(), betaplanemeshmodule::totalke(), loggermodule::trace_logging_level, and numberkindsmodule::write_unit_1.
real(kreal) function betaplanegaussian::gaussianvortexvorticity (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 240 of file BetaPlaneGaussianVortex.f90.
References particlesmodule::particles::x, and particlesmodule::particles::y.
subroutine betaplanegaussian::initlogger (type(logger), intent(inout) log, integer(kint), intent(in) rank)
Definition at line 323 of file BetaPlaneGaussianVortex.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine betaplanegaussian::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 246 of file BetaPlaneGaussianVortex.f90.
References polymesh2dmodule::polymesh2d::amrlimit, loggermodule::error_logging_level, polymesh2dmodule::polymesh2d::initnest, betaplanemeshmodule::logkey, numberkindsmodule::read_unit, and spherebvemodule::bvemesh::rotationrate.
subroutine betaplanegaussian::setabsolutetolerances (type(betaplanemesh), intent(in) betaPlane, real(kreal), intent(inout) circTol, real(kreal), intent(inout) lagVarTol)
Definition at line 231 of file BetaPlaneGaussianVortex.f90.
References betaplanemeshmodule::maxcirculationmagnitudeperface(), and polymesh2dmodule::maxlagrangianvariationperface().