LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/BivarConvergenceTests.f90 File Reference
/Users/pabosle/lpm-v2/BivarConvergenceTests.f90 File Reference
Functions/Subroutines
program planarinterpconvergence
real(kreal) function gaussian (xy, b)
real(kreal) function, dimension(2) gaussgrad (xy, b)
real(kreal) function gausslap (xy, b)
real(kreal) function, dimension(3) gauss2ndderivs (xy, b)
Function/Subroutine Documentation
real(kreal) function, dimension(3) planarinterpconvergence::gauss2ndderivs (real(kreal), dimension(2), intent(in) xy, real(kreal), intent(in) b)
Definition at line 277 of file BivarConvergenceTests.f90.
real(kreal) function, dimension(2) planarinterpconvergence::gaussgrad (real(kreal), dimension(2), intent(in) xy, real(kreal), intent(in) b)
Definition at line 259 of file BivarConvergenceTests.f90.
real(kreal) function planarinterpconvergence::gaussian (real(kreal), dimension(2), intent(in) xy, real(kreal), intent(in) b)
Definition at line 251 of file BivarConvergenceTests.f90.
real(kreal) function planarinterpconvergence::gausslap (real(kreal), dimension(2), intent(in) xy, real(kreal), intent(in) b)
Definition at line 268 of file BivarConvergenceTests.f90.
program planarinterpconvergence ()
Definition at line 1 of file BivarConvergenceTests.f90.
References gauss2ndderivs(), gaussgrad(), gaussian(), gausslap(), bivarmodule::idlctn(), bivarmodule::idpdrv(), bivarmodule::idptip(), bivarmodule::idtang(), fieldmodule::insertscalartofield(), fieldmodule::insertvectortofield(), edgesmodule::maxedgelength(), fieldmodule::maxmagnitude(), loggermodule::trace_logging_level, numberkindsmodule::write_unit_1, fieldmodule::writefieldtomatlab(), and particlesmodule::writeparticlestomatlab().