LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/CollidingDipoles.f90 File Reference
/Users/pabosle/lpm-v2/CollidingDipoles.f90 File Reference
Driver program for the problem of two colliding Lamb dipoles in the plane.
Detailed Description
Driver program for the problem of two colliding Lamb dipoles in the plane.
Author
Peter Bosler, Sandia National Laboratories Center for Computing Research
Driver program for the problem of two colliding Lamb dipoles in the plane.
Demonstrates the solution of an inviscid incompressible flow in the plane using PlanarIncompressible, PlanarIncompressibleSolver, Refinement, and BIVARRemesh.
Initial vorticity distribution for colliding dipoles problem.
Definition in file CollidingDipoles.f90.
Functions/Subroutines
program collidingdipolesdriver
subroutine storelagparamastracer (aPlane, tracerID)
Stores the Lagrangian coordinate of each particle as a passive tracer. Helpful for visualization of transport.
real(kreal) function twodipolesvorticity (x, y)
Vorticity distribution function, used to define initial conditions and for indirect vorticity interpolation to \(t = 0 \).
real(kreal) function lambdipole (x, y, lambR, U0, xcent, ycent)
Vorticity function associated with a single Lamb dipole at location (xcent, ycent)
subroutine readnamelistfile (rank)
Reads a namelist file, which must be specified on the command line at run-time execution as the first argument, to define the user-specified variables for this driver program.
subroutine initlogger (aLog, rank)
Initializes a Logger module for this executable program.
real *8 function bessj (N, X)
This function calculates the first kind modified Bessel function of integer order N, for any REAL X.
real *8 function bessj0 (X)
This function calculates the First Kind Bessel Function of order 0, for any real number X.
real *8 function bessj1 (X)
This function calculates the First Kind Bessel Function of order 1, for any real number X.
Function/Subroutine Documentation
real *8 function bessj (N, real *8 X)
This function calculates the first kind modified Bessel function of integer order N, for any REAL X.
We use here the classical recursion formula, when X > N. For X < N, the Miller's algorithm is used to avoid overflows.
REFERENCE: C.W.CLENSHAW, CHEBYSHEV SERIES FOR MATHEMATICAL FUNCTIONS, MATHEMATICAL TABLES, VOL.5, 1962.
Parameters
[in] n order of Bessel function
[in] x
Returns
Bessel function output, \(B_n(x) \)
Definition at line 556 of file CollidingDipoles.f90.
References stdintvectormodule::stdintvector::int(), edgesmodule::edges::n, and stdintvectormodule::stdintvector::print().
real *8 function bessj0 (real *8 X)
This function calculates the First Kind Bessel Function of order 0, for any real number X.
The polynomial approximation by series of Chebyshev polynomials is used for 0<X<8 and 0<8/X<1.
REFERENCES:
M.ABRAMOWITZ,I.A.STEGUN, HANDBOOK OF MATHEMATICAL FUNCTIONS, 1965.
C.W.CLENSHAW, NATIONAL PHYSICAL LABORATORY MATHEMATICAL TABLES,
VOL.5, 1962.
Parameters
[in] x
Returns
Bessel function output, \(B_0(x) \)
Definition at line 624 of file CollidingDipoles.f90.
real *8 function bessj1 (real *8 X)
This function calculates the First Kind Bessel Function of order 1, for any real number X.
The polynomial approximation by series of Chebyshev polynomials is used for 0<X<8 and 0<8/X<1.
REFERENCES:
M.ABRAMOWITZ,I.A.STEGUN, HANDBOOK OF MATHEMATICAL FUNCTIONS, 1965.
C.W.CLENSHAW, NATIONAL PHYSICAL LABORATORY MATHEMATICAL TABLES,
VOL.5, 1962.
Parameters
[in] x
Returns
Bessel function output, \(B_1(x) \)
Definition at line 673 of file CollidingDipoles.f90.
program collidingdipolesdriver ()
Definition at line 1 of file CollidingDipoles.f90.
References betaplanemeshmodule::addtracers(), initlogger(), refinementmodule::iteratemeshrefinementonevariableandflowmap(), bivarremeshmodule::lagrangianremeshplanarincompressibletoreferencemesh(), bivarremeshmodule::lagrangianremeshplanarincompressiblewithvorticityfunction(), mpisetupmodule::loadbalance(), polymesh2dmodule::meshseedstring(), numberkindsmodule::numprocs, betaplanemeshmodule::outputtovtk(), numberkindsmodule::procrank, readnamelistfile(), particlesmodule::resetlagrangianparameter(), refinementmodule::scalarintegralrefinement(), setabsolutetolerances(), betaplanemeshmodule::setinitialvorticityonmesh(), planarincompressiblemodule::setstreamfunctiononmesh(), storelagparamastracer(), betaplanemeshmodule::totalenstrophy(), betaplanemeshmodule::totalke(), loggermodule::trace_logging_level, twodipolesvorticity(), and numberkindsmodule::write_unit_1.
subroutine collidingdipolesdriver::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank)
Initializes a Logger module for this executable program.
Output is controlled by message priority level and MPI rank.
Parameters
[in] aLog Logger module to initialize
[in] rank MPI rank
Definition at line 527 of file CollidingDipoles.f90.
References loggermodule::error_logging_level.
real(kreal) function collidingdipolesdriver::lambdipole (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) lambR, real(kreal), intent(in) U0, real(kreal), intent(in) xcent, real(kreal), intent(in) ycent)
Vorticity function associated with a single Lamb dipole at location (xcent, ycent)
Parameters
[in] x x-coordinate of output vorticity
[in] y y-coordinate of output vorticity
[in] lambR radius of dipole
[in] U0 strength parameter
[in] xcent x-coordinate of dipole center
[in] ycent y-coordinate of dipole center
Definition at line 392 of file CollidingDipoles.f90.
References numberkindsmodule::zero_tol.
subroutine collidingdipolesdriver::readnamelistfile (integer(kint), intent(in) rank)
Reads a namelist file, which must be specified on the command line at run-time execution as the first argument, to define the user-specified variables for this driver program.
Only MPI rank 0 reads the file; it then broadcasts the relevant data to all other ranks.
Parameters
[in] rank MPI rank
Definition at line 421 of file CollidingDipoles.f90.
References loggermodule::error_logging_level, numberkindsmodule::quad_rect_seed, numberkindsmodule::read_unit, numberkindsmodule::tri_hex_seed, and loggermodule::warning_logging_level.
subroutine collidingdipolesdriver::storelagparamastracer (type(planemeshincompressible), intent(inout) aPlane, integer(kint), intent(in) tracerID)
Stores the Lagrangian coordinate of each particle as a passive tracer. Helpful for visualization of transport.
Parameters
[in,out] aPlane PlanarIncompressible mesh
[in] tracerID index to PlanarIncompressible%tracers(:) array to store the Lagrangian coordinate
Definition at line 356 of file CollidingDipoles.f90.
real(kreal) function collidingdipolesdriver::twodipolesvorticity (real(kreal), intent(in) x, real(kreal), intent(in) y)
Vorticity distribution function, used to define initial conditions and for indirect vorticity interpolation to \(t = 0 \).
Conforms to the numberkindsmodule::scalarFnOf2DSpace interface.
Parameters
[in] x
[in] y
Returns
vorticity value at initial time at location (x,y)
Definition at line 376 of file CollidingDipoles.f90.
References lambdipole().