LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/CubedSphereTester.f90 File Reference
/Users/pabosle/lpm-v2/CubedSphereTester.f90 File Reference
Functions/Subroutines
program cubedspheremeshtest
Function/Subroutine Documentation
program cubedspheremeshtest ()
Definition at line 1 of file CubedSphereTester.f90.
References polymesh2dmodule::ccwadjacentfaces(), polymesh2dmodule::ccwedgesaroundface(), polymesh2dmodule::ccwfacesaroundvertex(), polymesh2dmodule::ccwverticesaroundface(), numberkindsmodule::cubed_sphere_seed, facesmodule::facecenterphyscoord(), polymesh2dmodule::locatefacecontainingpoint(), particlesmodule::physcoord(), numberkindsmodule::pi, loggermodule::trace_logging_level, loggermodule::warning_logging_level, numberkindsmodule::write_unit_1, and polymesh2dmodule::writemeshtovtkpolydata().