LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/IcosTriMeshTester.f90 File Reference
/Users/pabosle/lpm-v2/IcosTriMeshTester.f90 File Reference
Functions/Subroutines
program icostrimeshtester
Function/Subroutine Documentation
program icostrimeshtester ()
Definition at line 1 of file IcosTriMeshTester.f90.
References polymesh2dmodule::ccwadjacentfaces(), polymesh2dmodule::ccwedgesaroundface(), polymesh2dmodule::ccwfacesaroundvertex(), polymesh2dmodule::ccwverticesaroundface(), edgesmodule::edgelength(), loggermodule::error_logging_level, facesmodule::facecenterphyscoord(), numberkindsmodule::icos_tri_sphere_seed, polymesh2dmodule::locatefacecontainingpoint(), edgesmodule::maxedgelength(), polymesh2dmodule::nearestparticle(), particlesmodule::physcoord(), numberkindsmodule::pi, loggermodule::trace_logging_level, loggermodule::warning_logging_level, numberkindsmodule::write_unit_1, and polymesh2dmodule::writemeshtovtkpolydata().