LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/NitscheStrickland.f90 File Reference
/Users/pabosle/lpm-v2/NitscheStrickland.f90 File Reference
Driver program for a planar SWE problem defined by a symmetric vortex and zero initial divergence.
Detailed Description
Driver program for a planar SWE problem defined by a symmetric vortex and zero initial divergence.
Author
Peter Bosler, Sandia National Laboratories, Center for Computing Research
Demonstrates flow interaction with topography.
Demontstrates the use of PlanarSWE, SWEPlaneSolver, and PSEDirectSum.
Driver program based on the setup of an isentropic gas dymanics problem from Nitsche and Strickland (2002).
Intial conditions are a symmetric vortex located at the origin, uniform fluid depth and zero initial divergence.
Users may alter the source code to change the bottom topography function (each change requires a new compilation).
Other input is supplied via namelist file.
Flow interaction with topography. A vortex interacting with a mountain generates gravity waves.
For a complete description of the problem that this application is based upon, see
M. Nitsche and J. Strickland, Extension of the gridless vortex method into the compressible flow regime. J. Turb. 3 (2002)
Definition in file NitscheStrickland.f90.
Functions/Subroutines
program nitchestrickland
real(kreal) function initdivergence (x, y)
Defines the initial divergence.
real(kreal) function initvorticity (x, y)
Defines the initial vorticity.
real(kreal) function, dimension(2) initvelocity (x, y)
Defines the initial velocity.
real(kreal) function inith (x, y)
Defines the initial fluid depth.
real(kreal) function bottomtopo (x, y)
Defines the bottom topography.
subroutine initlogger (log, rank)
Initializes a Logger module for this executable program.
subroutine readnamelistfile (rank)
Reads a namelist file, which must be specified on the command line at run-time execution as the first argument, to define the user-specified variables for this driver program.
Function/Subroutine Documentation
real(kreal) function nitchestrickland::bottomtopo (real(kreal), intent(in) x, real(kreal), intent(in) y)
Defines the bottom topography.
Conforms to the numberkindsmodule::scalarFnOf2DSpace interface.
Parameters
[in] x
[in] y
Returns
height of bottom, \(h_B(x,y) \)
Definition at line 238 of file NitscheStrickland.f90.
real(kreal) function nitchestrickland::initdivergence (real(kreal), intent(in) x, real(kreal), intent(in) y)
Defines the initial divergence.
Conforms to the numberkindsmodule::scalarFnOf2DSpace interface.
Parameters
[in] x
[in] y
Returns
initial divergence, \(\delta(x,y,0) \)
Definition at line 173 of file NitscheStrickland.f90.
real(kreal) function nitchestrickland::inith (real(kreal), intent(in) x, real(kreal), intent(in) y)
Defines the initial fluid depth.
Conforms to the numberkindsmodule::scalarFnOf2DSpace interface.
Parameters
[in] x
[in] y
Returns
initial depth, \(h(x,y,0) \)
Definition at line 225 of file NitscheStrickland.f90.
References bottomtopo().
subroutine nitchestrickland::initlogger (type(logger), intent(inout) log, integer(kint), intent(in) rank)
Initializes a Logger module for this executable program.
Output is controlled by message priority level and MPI rank.
Parameters
[in] log Logger module to initialize
[in] rank MPI rank
Definition at line 251 of file NitscheStrickland.f90.
References loggermodule::error_logging_level.
real(kreal) function, dimension(2) nitchestrickland::initvelocity (real(kreal), intent(in) x, real(kreal), intent(in) y)
Defines the initial velocity.
Conforms to the numberkindsmodule::vectorFnOf2DSpace interface.
Parameters
[in] x
[in] y
Returns
initial velocity, \(\vec{u}(x,y,0) \)
Definition at line 203 of file NitscheStrickland.f90.
real(kreal) function nitchestrickland::initvorticity (real(kreal), intent(in) x, real(kreal), intent(in) y)
Defines the initial vorticity.
Conforms to the numberkindsmodule::scalarFnOf2DSpace interface.
Parameters
[in] x
[in] y
Returns
initial vorticiy, \(\zeta(x,y,0) \)
Definition at line 186 of file NitscheStrickland.f90.
References numberkindsmodule::zero_tol.
program nitchestrickland ()
Definition at line 1 of file NitscheStrickland.f90.
References bottomtopo(), initdivergence(), inith(), initlogger(), initvelocity(), initvorticity(), numberkindsmodule::numprocs, planarswemodule::outputtovtkfile(), numberkindsmodule::procrank, numberkindsmodule::quad_rect_seed, readnamelistfile(), planarswemodule::setbottomheightonmesh(), planarswemodule::setinitialdivergenceonmesh(), planarswemodule::setinitialhonmesh(), planarswemodule::setinitialpotvortonmesh(), planarswemodule::setinitialvelocityonmesh(), betaplanemeshmodule::setinitialvorticityonmesh(), loggermodule::trace_logging_level, and numberkindsmodule::tri_hex_seed.
subroutine nitchestrickland::readnamelistfile (integer(kint), intent(in) rank)
Reads a namelist file, which must be specified on the command line at run-time execution as the first argument, to define the user-specified variables for this driver program.
Only MPI rank 0 reads the file; it then broadcasts the relevant data to all other ranks.
Parameters
[in] rank MPI rank
Definition at line 268 of file NitscheStrickland.f90.
References loggermodule::error_logging_level, numberkindsmodule::quad_rect_seed, numberkindsmodule::read_unit, numberkindsmodule::tri_hex_seed, and loggermodule::warning_logging_level.