LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/ParabolicFlood.f90 File Reference
/Users/pabosle/lpm-v2/ParabolicFlood.f90 File Reference
Functions/Subroutines
program parabolicfloodwave
real(kreal) function initdivergence (x, y)
real(kreal) function initvorticity (x, y)
real(kreal) function, dimension(2) initvelocity (x, y)
real(kreal) function inith (x, y)
subroutine initlogger (log, rank)
real(kreal) function bottomtopo (x, y)
real(kreal) function depthlaplacian (x, y)
real(kreal) function, dimension(2) exactvelocity (x, y, t, TT)
real(kreal) function exactdivergence (x, y, t, TT)
real(kreal) function exacth (x, y, t, TT)
subroutine readnamelistfile (rank)
Function/Subroutine Documentation
real(kreal) function parabolicfloodwave::bottomtopo (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 219 of file ParabolicFlood.f90.
References bottomtopo().
real(kreal) function parabolicfloodwave::depthlaplacian (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 225 of file ParabolicFlood.f90.
real(kreal) function parabolicfloodwave::exactdivergence (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) t, real(kreal), intent(in) TT)
Definition at line 238 of file ParabolicFlood.f90.
References polymesh2dmodule::polymesh2d::t.
real(kreal) function parabolicfloodwave::exacth (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) t, real(kreal), intent(in) TT)
Definition at line 244 of file ParabolicFlood.f90.
References polymesh2dmodule::polymesh2d::t, particlesmodule::particles::x, and particlesmodule::particles::y.
real(kreal) function, dimension(2) parabolicfloodwave::exactvelocity (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) t, real(kreal), intent(in) TT)
Definition at line 231 of file ParabolicFlood.f90.
References polymesh2dmodule::polymesh2d::t, particlesmodule::particles::x, and particlesmodule::particles::y.
real(kreal) function parabolicfloodwave::initdivergence (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 184 of file ParabolicFlood.f90.
References initdivergence().
real(kreal) function parabolicfloodwave::inith (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 202 of file ParabolicFlood.f90.
References inith(), particlesmodule::particles::x, and particlesmodule::particles::y.
subroutine parabolicfloodwave::initlogger (type(logger), intent(inout) log, integer(kint), intent(in) rank)
Definition at line 208 of file ParabolicFlood.f90.
References betaplanemeshmodule::log, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
real(kreal) function, dimension(2) parabolicfloodwave::initvelocity (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 196 of file ParabolicFlood.f90.
References initvelocity().
real(kreal) function parabolicfloodwave::initvorticity (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 190 of file ParabolicFlood.f90.
References initvorticity().
program parabolicfloodwave ()
Definition at line 1 of file ParabolicFlood.f90.
References betaplanemeshmodule::addtracers(), polymesh2dmodule::polymesh2d::amrlimit, betaplanemeshmodule::betaplanemesh::beta, bottomtopo(), exactdivergence(), exacth(), exactvelocity(), betaplanemeshmodule::betaplanemesh::f0, facesmodule::faces::facekind, planarswemodule::swemesh::g, initdivergence(), inith(), initlogger(), polymesh2dmodule::polymesh2d::initnest, initvelocity(), initvorticity(), fieldmodule::insertscalartofield(), fieldmodule::insertvectortofield(), betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, betaplanemeshmodule::betaplanemesh::mesh, polymesh2dmodule::polymesh2d::meshseed, numberkindsmodule::numprocs, planarswemodule::outputtovtkfile(), numberkindsmodule::procrank, numberkindsmodule::quad_rect_seed, readnamelistfile(), planarswemodule::setbottomheightonmesh(), planarswemodule::setinitialdivergenceonmesh(), planarswemodule::setinitialhonmesh(), planarswemodule::setinitialpotvortonmesh(), planarswemodule::setinitialvelocityonmesh(), betaplanemeshmodule::setinitialvorticityonmesh(), polymesh2dmodule::polymesh2d::t, and numberkindsmodule::tri_hex_seed.
subroutine parabolicfloodwave::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 250 of file ParabolicFlood.f90.
References polymesh2dmodule::polymesh2d::amrlimit, facesmodule::faces::facekind, polymesh2dmodule::polymesh2d::initnest, betaplanemeshmodule::logkey, polymesh2dmodule::polymesh2d::meshseed, numberkindsmodule::quad_rect_seed, numberkindsmodule::read_unit, and numberkindsmodule::tri_hex_seed.