LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/PlaneSWEGravityWaves.f90 File Reference
/Users/pabosle/lpm-v2/PlaneSWEGravityWaves.f90 File Reference
Functions/Subroutines
program gravitywave
pure real(kreal) function inith (x, y)
pure real(kreal) function heightpertub (x, y)
pure real(kreal) function bottomtopo (x, y)
pure real(kreal) function initdivergence (x, y)
pure real(kreal) function initvorticity (x, y)
pure real(kreal) function,
dimension(2) initvelocity (x, y)
subroutine initlogger (log, rank)
subroutine readnamelistfile (rank)
Function/Subroutine Documentation
pure real(kreal) function gravitywave::bottomtopo (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 172 of file PlaneSWEGravityWaves.f90.
References bottomtopo(), particlesmodule::particles::x, and particlesmodule::particles::y.
program gravitywave ()
Definition at line 1 of file PlaneSWEGravityWaves.f90.
References polymesh2dmodule::polymesh2d::amrlimit, betaplanemeshmodule::betaplanemesh::beta, bottomtopo(), betaplanemeshmodule::betaplanemesh::f0, facesmodule::faces::facekind, planarswemodule::swemesh::g, initdivergence(), inith(), initlogger(), polymesh2dmodule::polymesh2d::initnest, initvelocity(), initvorticity(), betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, polymesh2dmodule::polymesh2d::meshseed, numberkindsmodule::numprocs, planarswemodule::outputtovtkfile(), numberkindsmodule::procrank, numberkindsmodule::quad_rect_seed, readnamelistfile(), planarswemodule::setbottomheightonmesh(), planarswemodule::setinitialdivergenceonmesh(), planarswemodule::setinitialhonmesh(), planarswemodule::setinitialpotvortonmesh(), planarswemodule::setinitialvelocityonmesh(), betaplanemeshmodule::setinitialvorticityonmesh(), polymesh2dmodule::polymesh2d::t, and numberkindsmodule::tri_hex_seed.
pure real(kreal) function gravitywave::heightpertub (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 161 of file PlaneSWEGravityWaves.f90.
References particlesmodule::particles::x, and particlesmodule::particles::y.
pure real(kreal) function gravitywave::initdivergence (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 179 of file PlaneSWEGravityWaves.f90.
References initdivergence().
pure real(kreal) function gravitywave::inith (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 155 of file PlaneSWEGravityWaves.f90.
References bottomtopo(), heightpertub(), inith(), particlesmodule::particles::x, and particlesmodule::particles::y.
subroutine gravitywave::initlogger (type(logger), intent(inout) log, integer(kint), intent(in) rank)
Definition at line 198 of file PlaneSWEGravityWaves.f90.
References betaplanemeshmodule::log, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
pure real(kreal) function, dimension(2) gravitywave::initvelocity (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 191 of file PlaneSWEGravityWaves.f90.
References initvelocity().
pure real(kreal) function gravitywave::initvorticity (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 185 of file PlaneSWEGravityWaves.f90.
References initvorticity().
subroutine gravitywave::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 209 of file PlaneSWEGravityWaves.f90.
References polymesh2dmodule::polymesh2d::amrlimit, betaplanemeshmodule::betaplanemesh::beta, betaplanemeshmodule::betaplanemesh::f0, facesmodule::faces::facekind, polymesh2dmodule::polymesh2d::initnest, betaplanemeshmodule::logkey, polymesh2dmodule::polymesh2d::meshseed, numberkindsmodule::quad_rect_seed, numberkindsmodule::read_unit, and numberkindsmodule::tri_hex_seed.