LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/PlanarMeshTest.f90 File Reference
/Users/pabosle/lpm-v2/PlanarMeshTest.f90 File Reference
Functions/Subroutines
program planarmeshtester
Function/Subroutine Documentation
program planarmeshtester ()
Definition at line 1 of file PlanarMeshTest.f90.
References polymesh2dmodule::ccwadjacentfaces(), polymesh2dmodule::ccwedgesaroundface(), polymesh2dmodule::ccwfacesaroundvertex(), polymesh2dmodule::ccwverticesaroundface(), facesmodule::facecenterphyscoord(), polymesh2dmodule::locatefacecontainingpoint(), particlesmodule::physcoord(), polymesh2dmodule::pointisoutsidemesh(), numberkindsmodule::quad_rect_seed, loggermodule::trace_logging_level, numberkindsmodule::tri_hex_seed, loggermodule::warning_logging_level, numberkindsmodule::write_unit_1, and polymesh2dmodule::writemeshtomatlab().