LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/RossbyHaurwitz54.f90 File Reference
/Users/pabosle/lpm-v2/RossbyHaurwitz54.f90 File Reference
Functions/Subroutines
program bverossbyhaurwitz54
subroutine setabsolutetolerances (aBVEMesh, circTol, lagVarTol)
pure real(kreal) function legendre54 (z)
pure real(kreal) function rossbyhaurwitz54vorticity (x, y, z)
pure real(kreal) function initlattracer (x0, y0, z0)
subroutine readnamelistfile (rank)
subroutine initlogger (log, rank)
Function/Subroutine Documentation
program bverossbyhaurwitz54 ()
Definition at line 1 of file RossbyHaurwitz54.f90.
References betaplanemeshmodule::addtracers(), polymesh2dmodule::polymesh2d::amrlimit, numberkindsmodule::cubed_sphere_seed, facesmodule::faces::facekind, numberkindsmodule::icos_tri_sphere_seed, initlattracer(), initlogger(), polymesh2dmodule::polymesh2d::initnest, fieldmodule::insertscalartofield(), refinementmodule::iteratemeshrefinementonevariableandflowmap(), ssrfpackremeshmodule::lagrangianremeshbvetoreferencemesh(), ssrfpackremeshmodule::lagrangianremeshbvewithvorticityfunction(), mpisetupmodule::loadbalance(), betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, polymesh2dmodule::polymesh2d::meshseed, numberkindsmodule::numprocs, betaplanemeshmodule::outputtovtk(), numberkindsmodule::procrank, spherebvemodule::bvemesh::radius, readnamelistfile(), ssrfpackremeshmodule::remeshcounter, particlesmodule::resetlagrangianparameter(), rossbyhaurwitz54vorticity(), spherebvemodule::bvemesh::rotationrate, refinementmodule::scalarintegralrefinement(), setabsolutetolerances(), betaplanemeshmodule::setinitialvorticityonmesh(), betaplanemeshmodule::setstreamfunctionsonmesh(), polymesh2dmodule::polymesh2d::t, betaplanemeshmodule::totalenstrophy(), betaplanemeshmodule::totalke(), and numberkindsmodule::write_unit_1.
pure real(kreal) function bverossbyhaurwitz54::initlattracer (real(kreal), intent(in) x0, real(kreal), intent(in) y0, real(kreal), intent(in) z0)
Definition at line 430 of file RossbyHaurwitz54.f90.
References initlattracer(), particlesmodule::particles::x0, particlesmodule::particles::y0, and particlesmodule::particles::z0.
subroutine bverossbyhaurwitz54::initlogger (type(logger), intent(inout) log, integer(kint), intent(in) rank)
Definition at line 526 of file RossbyHaurwitz54.f90.
References betaplanemeshmodule::log, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
pure real(kreal) function bverossbyhaurwitz54::legendre54 (real(kreal), intent(in) z)
Definition at line 413 of file RossbyHaurwitz54.f90.
References particlesmodule::particles::z.
subroutine bverossbyhaurwitz54::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 436 of file RossbyHaurwitz54.f90.
References polymesh2dmodule::polymesh2d::amrlimit, numberkindsmodule::cubed_sphere_seed, facesmodule::faces::facekind, numberkindsmodule::icos_tri_sphere_seed, polymesh2dmodule::polymesh2d::initnest, betaplanemeshmodule::logkey, polymesh2dmodule::polymesh2d::meshseed, numberkindsmodule::read_unit, and spherebvemodule::bvemesh::rotationrate.
pure real(kreal) function bverossbyhaurwitz54::rossbyhaurwitz54vorticity (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Definition at line 419 of file RossbyHaurwitz54.f90.
References legendre54(), spherebvemodule::bvemesh::radius, particlesmodule::particles::x, particlesmodule::particles::y, and particlesmodule::particles::z.
subroutine bverossbyhaurwitz54::setabsolutetolerances (type(bvemesh), intent(in) aBVEMesh, real(kreal), intent(inout) circTol, real(kreal), intent(inout) lagVarTol)
Definition at line 404 of file RossbyHaurwitz54.f90.
References betaplanemeshmodule::maxcirculationmagnitudeperface(), and polymesh2dmodule::maxlagrangianvariationperface().