LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/SSRFPACKTest.f90 File Reference
/Users/pabosle/lpm-v2/SSRFPACKTest.f90 File Reference
Functions/Subroutines
program ssrfpacktest
pure real(kreal) function sphereharmonic54 (xyz)
pure real(kreal) function sphereharm54latlon (lon, lat)
pure real(kreal) function,
dimension(3) harmgradient (xyz)
subroutine initlogger (aLog, rank)
Function/Subroutine Documentation
pure real(kreal) function, dimension(3) ssrfpacktest::harmgradient (real(kreal), dimension(3), intent(in) xyz)
Definition at line 248 of file SSRFPACKTest.f90.
References harmgradient(), planarincompressiblesolvermodule::planesolver::u, and planarincompressiblesolvermodule::planesolver::v.
subroutine ssrfpacktest::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank)
Definition at line 266 of file SSRFPACKTest.f90.
References betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
pure real(kreal) function ssrfpacktest::sphereharm54latlon (real(kreal), intent(in) lon, real(kreal), intent(in) lat)
Definition at line 241 of file SSRFPACKTest.f90.
pure real(kreal) function ssrfpacktest::sphereharmonic54 (real(kreal), dimension(3), intent(in) xyz)
Definition at line 234 of file SSRFPACKTest.f90.
References sphereharmonic54().
program ssrfpacktest ()
Definition at line 1 of file SSRFPACKTest.f90.
References polymesh2dmodule::polymesh2d::amrlimit, numberkindsmodule::cubed_sphere_seed, numberkindsmodule::deg_2_rad, ssrfpackremeshmodule::bveremeshsource::deltri, harmgradient(), numberkindsmodule::icos_tri_sphere_seed, initlogger(), polymesh2dmodule::polymesh2d::initnest, fieldmodule::insertscalartofield(), fieldmodule::insertvectortofield(), bivarinterfacemodule::interpolatescalar(), betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, polymesh2dmodule::polymesh2d::meshseed, numberkindsmodule::numprocs, numberkindsmodule::pi, numberkindsmodule::procrank, spherebvemodule::bvemesh::radius, ssrfpackinterfacemodule::setscalarsourcedata(), ssrfpackinterfacemodule::setsourcelagrangianparameter(), sphereharm54latlon(), sphereharmonic54(), and numberkindsmodule::write_unit_2.