LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/SWETestCase2.f90 File Reference
/Users/pabosle/lpm-v2/SWETestCase2.f90 File Reference
Functions/Subroutines
program swetestcase2
subroutine readnamelistfile (rank)
pure real(kreal) function testcase2vorticity (x, y, z)
real(kreal) function testcase2height (x, y, z)
pure real(kreal) function topography (x, y, z)
pure real(kreal) function testcase2divergence (x, y, z)
pure real(kreal) function,
dimension(3) testcase2velocity (x, y, z)
subroutine initlogger (log, rank)
Function/Subroutine Documentation
subroutine swetestcase2::initlogger (type(logger), intent(inout) log, integer(kint), intent(in) rank)
Definition at line 291 of file SWETestCase2.f90.
References betaplanemeshmodule::log, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine swetestcase2::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 176 of file SWETestCase2.f90.
References polymesh2dmodule::polymesh2d::amrlimit, numberkindsmodule::cubed_sphere_seed, facesmodule::faces::facekind, numberkindsmodule::icos_tri_sphere_seed, polymesh2dmodule::polymesh2d::initnest, betaplanemeshmodule::logkey, polymesh2dmodule::polymesh2d::meshseed, and numberkindsmodule::read_unit.
program swetestcase2 ()
Definition at line 1 of file SWETestCase2.f90.
References betaplanemeshmodule::addtracers(), polymesh2dmodule::polymesh2d::amrlimit, numberkindsmodule::cubed_sphere_seed, facesmodule::faces::facekind, planarswemodule::swemesh::g, numberkindsmodule::icos_tri_sphere_seed, initlogger(), polymesh2dmodule::polymesh2d::initnest, betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, polymesh2dmodule::polymesh2d::meshseed, numberkindsmodule::numprocs, betaplanemeshmodule::outputtovtk(), numberkindsmodule::procrank, spherebvemodule::bvemesh::radius, readnamelistfile(), planarswemodule::setbottomheightonmesh(), planarswemodule::setinitialdivergenceonmesh(), planarswemodule::setinitialhonmesh(), planarswemodule::setinitialpotvortonmesh(), sphereswemodule::setinitialrelvortonmesh(), planarswemodule::setinitialvelocityonmesh(), polymesh2dmodule::polymesh2d::t, testcase2divergence(), testcase2height(), testcase2velocity(), testcase2vorticity(), and topography().
pure real(kreal) function swetestcase2::testcase2divergence (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Definition at line 276 of file SWETestCase2.f90.
real(kreal) function swetestcase2::testcase2height (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Definition at line 260 of file SWETestCase2.f90.
References planarswemodule::swemesh::g, spherebvemodule::bvemesh::radius, particlesmodule::particles::x, particlesmodule::particles::y, and particlesmodule::particles::z.
pure real(kreal) function, dimension(3) swetestcase2::testcase2velocity (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Definition at line 282 of file SWETestCase2.f90.
References particlesmodule::particles::x, and particlesmodule::particles::y.
pure real(kreal) function swetestcase2::testcase2vorticity (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Definition at line 250 of file SWETestCase2.f90.
References spherebvemodule::bvemesh::radius, particlesmodule::particles::x, particlesmodule::particles::y, and particlesmodule::particles::z.
pure real(kreal) function swetestcase2::topography (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Definition at line 270 of file SWETestCase2.f90.