LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/SWESteadyState.f90 File Reference
/Users/pabosle/lpm-v2/SWESteadyState.f90 File Reference
Functions/Subroutines
program sweplanesteadystate
pure real(kreal) function initdivergence (x, y)
pure real(kreal) function initvorticity (x, y)
pure real(kreal) function,
dimension(2) initvelocity (x, y)
pure real(kreal) function inith (x, y)
pure real(kreal) function bottomtopography (x, y)
real(kreal) function depthlaplacian (x, y)
subroutine initlogger (log, rank)
subroutine readnamelistfile (rank)
Function/Subroutine Documentation
pure real(kreal) function sweplanesteadystate::bottomtopography (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 173 of file SWESteadyState.f90.
real(kreal) function sweplanesteadystate::depthlaplacian (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 180 of file SWESteadyState.f90.
pure real(kreal) function sweplanesteadystate::initdivergence (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 148 of file SWESteadyState.f90.
pure real(kreal) function sweplanesteadystate::inith (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 167 of file SWESteadyState.f90.
References bottomtopography().
subroutine sweplanesteadystate::initlogger (type(logger), intent(inout) log, integer(kint), intent(in) rank)
Definition at line 188 of file SWESteadyState.f90.
References loggermodule::error_logging_level.
pure real(kreal) function, dimension(2) sweplanesteadystate::initvelocity (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 160 of file SWESteadyState.f90.
pure real(kreal) function sweplanesteadystate::initvorticity (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 154 of file SWESteadyState.f90.
subroutine sweplanesteadystate::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 199 of file SWESteadyState.f90.
References loggermodule::error_logging_level, numberkindsmodule::quad_rect_seed, numberkindsmodule::read_unit, numberkindsmodule::tri_hex_seed, and loggermodule::warning_logging_level.
program sweplanesteadystate ()
Definition at line 1 of file SWESteadyState.f90.
References bottomtopography(), initdivergence(), inith(), initlogger(), initvelocity(), initvorticity(), numberkindsmodule::numprocs, planarswemodule::outputtovtkfile(), numberkindsmodule::procrank, numberkindsmodule::quad_rect_seed, readnamelistfile(), planarswemodule::setbottomheightonmesh(), planarswemodule::setinitialdivergenceonmesh(), planarswemodule::setinitialhonmesh(), planarswemodule::setinitialpotvortonmesh(), planarswemodule::setinitialvelocityonmesh(), betaplanemeshmodule::setinitialvorticityonmesh(), loggermodule::trace_logging_level, and numberkindsmodule::tri_hex_seed.