LPM: Lagrangian Particle Methods: /Users/pabosle/lpm-v2/SpherePSETest.f90 File Reference
/Users/pabosle/lpm-v2/SpherePSETest.f90 File Reference
Functions/Subroutines
program testpsesphere
pure real(kreal) function sphereharmonic54 (xyz)
pure real(kreal) function,
dimension(3) harmgradient (xyz)
subroutine initlogger (aLog, rank)
Function/Subroutine Documentation
pure real(kreal) function, dimension(3) testpsesphere::harmgradient (real(kreal), dimension(3), intent(in) xyz)
Definition at line 294 of file SpherePSETest.f90.
subroutine testpsesphere::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank)
Definition at line 312 of file SpherePSETest.f90.
References loggermodule::error_logging_level.
pure real(kreal) function testpsesphere::sphereharmonic54 (real(kreal), dimension(3), intent(in) xyz)
Definition at line 287 of file SpherePSETest.f90.
program testpsesphere ()
Definition at line 1 of file SpherePSETest.f90.
References numberkindsmodule::cubed_sphere_seed, numberkindsmodule::deg_2_rad, harmgradient(), numberkindsmodule::icos_tri_sphere_seed, initlogger(), fieldmodule::insertscalartofield(), fieldmodule::insertvectortofield(), fieldmodule::maxmagnitude(), numberkindsmodule::numprocs, numberkindsmodule::pi, numberkindsmodule::procrank, psedirectsummodule::psespheregradientatparticles(), psedirectsummodule::psesphereinterpolatescalar(), psedirectsummodule::psespherelaplacianatparticles(), sphereharmonic54(), loggermodule::trace_logging_level, numberkindsmodule::write_unit_1, numberkindsmodule::write_unit_2, facesmodule::writefaceareatovtkcelldata(), facesmodule::writefacestovtkpolygons(), fieldmodule::writefieldtovtkcelldata(), fieldmodule::writefieldtovtkpointdata(), particlesmodule::writevtklagcoords(), outputwritermodule::writevtkpointdatasectionheader(), and particlesmodule::writevtkpoints().