LPM: Lagrangian Particle Methods: bivarmodule Module Reference
bivarmodule Module Reference
Detailed Description
Definition at line 1 of file bivar.f90.
Public Member Functions
subroutine, public idbvip (md, ndp, xd, yd, zd, nip, xi, yi, zi, iwk, wk)
subroutine, public idlctn (ndp, xd, yd, nt, ipt, nl, ipl, xii, yii, iti, iwk, wk)
subroutine, public idpdrv (ndp, xd, yd, zd, nt, ipt, pd, wk)
subroutine, public idptip (ndp, xd, yd, zd, nt, ipt, nl, ipl, pdd, iti, xii, yii, zii)
subroutine, public idtang (ndp, xd, yd, nt, ipt, nl, ipl, iwl, iwp, wk)
Private Member Functions
subroutine idgrid (xd, yd, nt, ipt, nl, ipl, nxi, nyi, xi, yi, ngp, igp)
subroutine idsfft (md, ndp, xd, yd, zd, nxi, nyi, nzi, xi, yi, zi, iwk, wk)
integer(kint) function idxchg (x, y, i1, i2, i3, i4)
subroutine timestamp ()
Member Function/Subroutine Documentation
subroutine, public bivarmodule::idbvip (integer(kint) md, integer(kint) ndp, real(kreal), dimension(ndp) xd, real(kreal), dimension(ndp) yd, real(kreal), dimension(ndp) zd, integer(kint) nip, real(kreal), dimension(nip) xi, real(kreal), dimension(nip) yi, real(kreal), dimension(nip) zi, integer(kint), dimension(31*ndp + nip) iwk, real(kreal), dimension(8*ndp) wk)
Definition at line 12 of file bivar.f90.
References idlctn(), idpdrv(), idptip(), and idtang().
subroutine bivarmodule::idgrid (real(kreal), dimension(*) xd, real(kreal), dimension(*) yd, integer(kint) nt, integer(kint), dimension(3*nt) ipt, integer(kint) nl, integer(kint), dimension(3*nl) ipl, integer(kint) nxi, integer(kint) nyi, real(kreal), dimension(nxi) xi, real(kreal), dimension(nyi) yi, integer(kint), dimension(2*(nt+2*nl)) ngp, integer(kint), dimension(nxi*nyi) igp) private
Definition at line 346 of file bivar.f90.
subroutine, public bivarmodule::idlctn (integer(kint) ndp, real(kreal), dimension(ndp) xd, real(kreal), dimension(ndp) yd, integer(kint) nt, integer(kint), dimension(3*nt) ipt, integer(kint) nl, integer(kint), dimension(3*nl) ipl, real(kreal) xii, real(kreal) yii, integer(kint) iti, integer(kint), dimension(18*ndp) iwk, real(kreal), dimension(8*ndp) wk)
Definition at line 789 of file bivar.f90.
subroutine, public bivarmodule::idpdrv (integer(kint) ndp, real(kreal), dimension(ndp) xd, real(kreal), dimension(ndp) yd, real(kreal), dimension(ndp) zd, integer(kint) nt, integer(kint), dimension(3*nt) ipt, real(kreal), dimension(5*ndp) pd, real(kreal), dimension(ndp) wk)
Definition at line 1170 of file bivar.f90.
subroutine, public bivarmodule::idptip (integer(kint) ndp, real(kreal), dimension(*) xd, real(kreal), dimension(*) yd, real(kreal), dimension(*) zd, integer(kint) nt, integer(kint), dimension(3*nt) ipt, integer(kint) nl, integer(kint), dimension(3*nl) ipl, real(kreal), dimension(5*ndp) pdd, integer(kint) iti, real(kreal) xii, real(kreal) yii, real(kreal) zii)
Definition at line 1387 of file bivar.f90.
subroutine bivarmodule::idsfft (integer(kint) md, integer(kint) ndp, real(kreal), dimension(ndp) xd, real(kreal), dimension(ndp) yd, real(kreal), dimension(ndp) zd, integer(kint) nxi, integer(kint) nyi, integer(kint) nzi, real(kreal), dimension(nxi) xi, real(kreal), dimension(nyi) yi, real(kreal), dimension(nzi,nyi) zi, integer(kint), dimension(31*ndp + nxi*nyi) iwk, real(kreal), dimension(6*ndp) wk) private
Definition at line 1853 of file bivar.f90.
References idgrid(), idpdrv(), idptip(), and idtang().
subroutine, public bivarmodule::idtang (integer(kint) ndp, real(kreal), dimension(ndp) xd, real(kreal), dimension(ndp) yd, integer(kint) nt, integer(kint), dimension(6*ndp-15) ipt, integer(kint) nl, integer(kint), dimension(6*ndp) ipl, integer(kint), dimension(18*ndp) iwl, integer(kint), dimension(ndp) iwp, real(kreal), dimension(ndp) wk)
Definition at line 2175 of file bivar.f90.
References idxchg().
integer(kint) function bivarmodule::idxchg (real(kreal), dimension(*) x, real(kreal), dimension(*) y, integer(kint) i1, integer(kint) i2, integer(kint) i3, integer(kint) i4) private
Definition at line 2777 of file bivar.f90.
subroutine bivarmodule::timestamp () private
Definition at line 2879 of file bivar.f90.
The documentation for this module was generated from the following file:
/Users/pabosle/lpm-v2/bivar.f90