LPM: Lagrangian Particle Methods: sphereswemodule Module Reference
sphereswemodule Module Reference
Detailed Description
Definition at line 1 of file SphereSWE.f90.
Data Types
interface copy
interface delete
interface logstats
interface new
type swemesh
Public Member Functions
subroutine, public addtracers (self, nTracers, tracerDims)
subroutine, public outputtovtk (self, filename)
subroutine, public setinitialrelvortonmesh (self, vortFn)
subroutine, public setinitialhonmesh (self, hFn)
subroutine, public setbottomheightonmesh (self, topographyFn)
subroutine, public setinitialdivergenceonmesh (self, divFn)
subroutine, public setinitialvelocityonmesh (self, velFn)
subroutine, public setinitialpotvortonmesh (self)
Private Member Functions
subroutine newprivate (self, meshSeed, initNest, maxNest, amrLimit, sphereRadius, rotationRate, g)
subroutine deleteprivate (self)
subroutine copyprivate (self, other)
subroutine logstatsprivate (self, aLog)
subroutine setscalartraceronmesh (self, tracerID, tracerFn)
subroutine setvectortraceronmesh (self, tracerID, tracerFn)
subroutine initlogger (aLog, rank)
Private Attributes
logical(klog), save loginit = .FALSE.
type(logger) log
character(len=28), save logkey = 'SWE'
integer(kint), parameter loglevel = DEBUG_LOGGING_LEVEL
Member Function/Subroutine Documentation
subroutine, public sphereswemodule::addtracers (type(swemesh), intent(inout) self, integer(kint), intent(in) nTracers, integer(kint), dimension(:), intent(in) tracerDims)
Definition at line 181 of file SphereSWE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine sphereswemodule::copyprivate (type(swemesh), intent(inout) self, type(swemesh), intent(in) other) private
Definition at line 146 of file SphereSWE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine sphereswemodule::deleteprivate (type(swemesh), intent(inout) self) private
Definition at line 126 of file SphereSWE.f90.
subroutine sphereswemodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Definition at line 364 of file SphereSWE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine sphereswemodule::logstatsprivate (type(swemesh), intent(in) self, type(logger), intent(inout) aLog) private
Definition at line 199 of file SphereSWE.f90.
References loggermodule::trace_logging_level.
subroutine sphereswemodule::newprivate (type(swemesh), intent(out) self, integer(kint), intent(in) meshSeed, integer(kint), intent(in) initNest, integer(kint), intent(in) maxNest, integer(kint), intent(in) amrLimit, real(kreal), intent(in) sphereRadius, real(kreal), intent(in) rotationRate, real(kreal), intent(in) g) private
Definition at line 93 of file SphereSWE.f90.
References numberkindsmodule::cubed_sphere_seed, loggermodule::error_logging_level, numberkindsmodule::icos_tri_sphere_seed, initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, numberkindsmodule::numprocs, and numberkindsmodule::procrank.
subroutine, public sphereswemodule::outputtovtk (type(swemesh), intent(in) self, character(len=*), intent(in) filename)
Definition at line 225 of file SphereSWE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, numberkindsmodule::write_unit_1, facesmodule::writefaceareatovtkcelldata(), facesmodule::writefacestovtkpolygons(), fieldmodule::writefieldtovtkpointdata(), particlesmodule::writevtklagcoords(), outputwritermodule::writevtkpointdatasectionheader(), and particlesmodule::writevtkpoints().
subroutine, public sphereswemodule::setbottomheightonmesh (type(swemesh), intent(inout) self, procedure(scalarfnof3dspace) topographyFn)
Definition at line 316 of file SphereSWE.f90.
subroutine, public sphereswemodule::setinitialdivergenceonmesh (type(swemesh), intent(inout) self, procedure(scalarfnof3dspace) divFn)
Definition at line 328 of file SphereSWE.f90.
References fieldmodule::insertscalartofield().
subroutine, public sphereswemodule::setinitialhonmesh (type(swemesh), intent(inout) self, procedure(scalarfnof3dspace) hFn)
Definition at line 306 of file SphereSWE.f90.
References fieldmodule::insertscalartofield().
subroutine, public sphereswemodule::setinitialpotvortonmesh (type(swemesh), intent(inout) self)
Definition at line 348 of file SphereSWE.f90.
References fieldmodule::insertscalartofield(), and particlesmodule::physcoord().
subroutine, public sphereswemodule::setinitialrelvortonmesh (type(swemesh), intent(inout) self, procedure(scalarfnof3dspace) vortFn)
Definition at line 265 of file SphereSWE.f90.
References fieldmodule::insertscalartofield().
subroutine, public sphereswemodule::setinitialvelocityonmesh (type(swemesh), intent(inout) self, procedure(vectorfnof3dspace) velFn)
Definition at line 338 of file SphereSWE.f90.
References fieldmodule::insertvectortofield().
subroutine sphereswemodule::setscalartraceronmesh (type(swemesh), intent(inout) self, integer(kint), intent(in) tracerID, procedure(scalarfnof3dspace) tracerFn) private
Definition at line 277 of file SphereSWE.f90.
References fieldmodule::setfieldtozero().
subroutine sphereswemodule::setvectortraceronmesh (type(swemesh), intent(inout) self, integer(kint), intent(in) tracerID, procedure(vectorfnof3dspace) tracerFn) private
Definition at line 290 of file SphereSWE.f90.
References fieldmodule::setfieldtozero().
Member Data Documentation
type(logger) sphereswemodule::log private
Definition at line 82 of file SphereSWE.f90.
logical(klog), save sphereswemodule::loginit = .FALSE. private
Definition at line 81 of file SphereSWE.f90.
character(len=28), save sphereswemodule::logkey = 'SWE' private
Definition at line 83 of file SphereSWE.f90.
integer(kint), parameter sphereswemodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 84 of file SphereSWE.f90.
The documentation for this module was generated from the following file:
/Users/pabosle/lpm-v2/SphereSWE.f90