LPM: Lagrangian Particle Methods: sphereswesolvermodule Module Reference
sphereswesolvermodule Module Reference
Detailed Description
Definition at line 1 of file SphereSWESolver.f90.
Data Types
interface delete
interface new
type swesolver
interface timestep
Private Member Functions
subroutine newprivate (self, sphere, topoFn)
subroutine deleteprivate (self)
subroutine timestepprivate (self, sphere, dt, topoFn)
subroutine swesphererhsintegrals (u, v, w, doubleDot, lapSurf, x, y, z, relVort, div, h, area, topoFn, mask, radius, pseEps, mpiParticles)
subroutine initlogger (aLog, rank)
Private Attributes
logical(klog), save loginit = .FALSE.
type(logger) log
character(len=28), save logkey = 'SWESphereK4'
integer(kint), parameter loglevel = DEBUG_LOGGING_LEVEL
character(len=max_string_length) logstring
Member Function/Subroutine Documentation
subroutine sphereswesolvermodule::deleteprivate (type(swesolver), intent(inout) self) private
Definition at line 206 of file SphereSWESolver.f90.
subroutine sphereswesolvermodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Definition at line 611 of file SphereSWESolver.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine sphereswesolvermodule::newprivate (type(swesolver), intent(out) self, type(swemesh), intent(inout) sphere, procedure(scalarfnof3dspace) topoFn) private
Definition at line 119 of file SphereSWESolver.f90.
References initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, numberkindsmodule::procrank, and swesphererhsintegrals().
subroutine sphereswesolvermodule::swesphererhsintegrals (real(kreal), dimension(:), intent(inout) u, real(kreal), dimension(:), intent(inout) v, real(kreal), dimension(:), intent(inout) w, real(kreal), dimension(:), intent(inout) doubleDot, real(kreal), dimension(:), intent(inout) lapSurf, real(kreal), dimension(:), intent(in) x, real(kreal), dimension(:), intent(in) y, real(kreal), dimension(:), intent(in) z, real(kreal), dimension(:), intent(in) relVort, real(kreal), dimension(:), intent(in) div, real(kreal), dimension(:), intent(in) h, real(kreal), dimension(:), intent(in) area, procedure(scalarfnof3dspace) topoFn, logical(klog), dimension(:), intent(in) mask, real(kreal), intent(in) radius, real(kreal), intent(in) pseEps, type(mpisetup), intent(in) mpiParticles) private
Definition at line 447 of file SphereSWESolver.f90.
References psedirectsummodule::bivariatelaplaciankernel8(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, betaplanemeshmodule::betaplanemesh::mpiparticles, numberkindsmodule::numprocs, numberkindsmodule::pi, numberkindsmodule::procrank, planarswemodule::swemesh::pseeps, and spherebvemodule::bvemesh::radius.
subroutine sphereswesolvermodule::timestepprivate (type(swesolver), intent(inout) self, type(swemesh), intent(inout) sphere, real(kreal), intent(in) dt, procedure(scalarfnof3dspace) topoFn) private
Definition at line 262 of file SphereSWESolver.f90.
References planarswemodule::setbottomheightonmesh(), and swesphererhsintegrals().
Member Data Documentation
type(logger) sphereswesolvermodule::log private
Definition at line 108 of file SphereSWESolver.f90.
logical(klog), save sphereswesolvermodule::loginit = .FALSE. private
Definition at line 107 of file SphereSWESolver.f90.
character(len=28), save sphereswesolvermodule::logkey = 'SWESphereK4' private
Definition at line 109 of file SphereSWESolver.f90.
integer(kint), parameter sphereswesolvermodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 110 of file SphereSWESolver.f90.
character(len=max_string_length) sphereswesolvermodule::logstring private
Definition at line 111 of file SphereSWESolver.f90.
The documentation for this module was generated from the following file:
/Users/pabosle/lpm-v2/SphereSWESolver.f90