LPM: Lagrangian Particle Methods: SphereBVE
SphereBVE
Data structure for representing solutions of the Barotropic Vorticity Equation (BVE) on the surface of a rotating sphere.
Detailed Description
Data structure for representing solutions of the Barotropic Vorticity Equation (BVE) on the surface of a rotating sphere.
Combines a PolyMesh2d with the data Field objects for the BVE. Allows users to optionally add Field objects for passive tracers.
In addition to the variables carried by the base Particles object (e.g., physical and Lagrangian coordinates), the BVEMesh data type adds fields for relative vorticity \(\zeta(x,y,z,t) \) and the materially conserved absolute vorticity \(\omega(x_0,y_0,z_0) \). These variables are related by the equation
\[ \omega = \zeta + f, \]
where \(f = \frac{2\Omega}{a}z(t) \) is the Coriolis parameter, \(\Omega \) is the constant angular velocity of the sphere about the z-axis, and \(a \) is the radius of the sphere.
Two stream functions are defined on the particles, \(\psi_r(x,y,z,t) \) is defined with respect to the rotating frame and \(\psi_a(x,y,z,t) \) is defined with respect to the inertial frame. Both are represented (and computed) by convolution with the Green's function kernel,
\begin{align*} \psi_r(\vec{x},t) &= \frac{1}{4\pi a}\int_{S} \log(1 - \vec{x} \cdot \vec{\tilde{x}})\zeta(\vec{\tilde{x}})\,dA, \\ \psi_a(\vec{x},t) &= \frac{1}{4\pi a}\int_{S} \log(1 - \vec{x} \cdot \vec{\tilde{x}})\omega(\vec{\tilde{x}})\,dA. \end{align*}
The particles also have a Field to track their velocity, which is given by convolution with the Biot-Savart kernel,
\[ \vec{u}(\vec{x},t) = -\frac{1}{4\pi a}\int_{S} \frac{ \vec{x} \times \vec{\tilde{x}} }{a^2 - \vec{x}\cdot\vec{\tilde{x}}} \zeta(\vec{\tilde{x}})\,dA. \]
For a more detailed discussion, see
P. Bosler, L. Wang, C. Jablonowski, and R. Krasny, A Lagrangian particle/panel method for the barotropic vorticity equations on a rotating sphere, Fluid Dynamics Research 46 (2014). DOI: 10.1088/0169-5983/46/3/031406.
Data Types
interface spherebvemodule::new
interface spherebvemodule::delete
interface spherebvemodule::copy
interface spherebvemodule::logstats
interface spherebvemodule::setvelocityonmesh
Functions/Subroutines
final spherebvemodule::bvemesh::deleteprivate
subroutine spherebvemodule::new::newprivate (self, meshSeed, initNest, maxNest, amrLimit, sphereRadius, rotationRate)
Allocates memory and initializes a spherical mesh for BVE applications.
subroutine spherebvemodule::delete::deleteprivate (self)
Deletes and frees memory associated with a spherical BVE Mesh.
subroutine spherebvemodule::copy::copyprivate (self, other)
Performs a deep copy of a BVE mesh and all of its variables. The target mesh must have been allocated prior to calling this subroutine.
subroutine spherebvemodule::logstats::logstatsprivate (self, aLog)
Output basic information about a BVE mesh to a Logger module.
subroutine spherebvemodule::setvelocityonmesh::setvelocityfromfunction (self, velFn)
Defines an initial velocity distribution on a BVE mesh.
subroutine spherebvemodule::setvelocityonmesh::setvelocityfromvorticity (self)
Defines the velocity distribution on a BVE mesh using the Biot-Savart integral.
subroutine spherebvemodule::newprivate (self, meshSeed, initNest, maxNest, amrLimit, sphereRadius, rotationRate)
Allocates memory and initializes a spherical mesh for BVE applications.
subroutine spherebvemodule::deleteprivate (self)
Deletes and frees memory associated with a spherical BVE Mesh.
subroutine spherebvemodule::copyprivate (self, other)
Performs a deep copy of a BVE mesh and all of its variables. The target mesh must have been allocated prior to calling this subroutine.
subroutine, public spherebvemodule::addtracers (self, nTracers, tracerDims)
Adds memory for passive tracers to a spherical BVE mesh.
subroutine spherebvemodule::logstatsprivate (self, aLog)
Output basic information about a BVE mesh to a Logger module.
subroutine, public spherebvemodule::outputtovtk (self, filename)
Writes a BVE mesh to a legacy formatted .vtk file, including all Field data for variables and tracers.
subroutine, public spherebvemodule::setinitialvorticityonmesh (self, relVortFn)
Defines an initial vorticity distribution on a BVE mesh.
subroutine spherebvemodule::setvelocityfromfunction (self, velFn)
Defines an initial velocity distribution on a BVE mesh.
subroutine spherebvemodule::setscalartraceronmesh (self, tracerId, tracerFn)
Defines an initial tracer distribution on a BVE mesh.
subroutine spherebvemodule::setvectortraceronmesh (self, tracerID, tracerFn)
Defines an initial tracer distribution on a BVE mesh.
real(kreal) function, public spherebvemodule::totalke (self)
Computes the total kinetic energy (a conserved integral) on a BVE mesh.
real(kreal) function, public spherebvemodule::totalenstrophy (self)
Computes the total enstrophy (a conserved integral) on a BVE mesh.
subroutine, public spherebvemodule::setstreamfunctionsonmesh (self)
Defines the absolute and relative stream functions on a BVE mesh using the Green's function integral.
subroutine spherebvemodule::setvelocityfromvorticity (self)
Defines the velocity distribution on a BVE mesh using the Biot-Savart integral.
real(kreal) function, public spherebvemodule::maxcirculationmagnitudeperface (self)
Computes the maximum circulation magnitude about each face and returns the maximum value for the whole mesh.
subroutine spherebvemodule::initlogger (aLog, rank)
Initializes a logger for the BVE module.
Variables
type(polymesh2d) spherebvemodule::bvemesh::mesh
PolyMesh2d for spatial discretization
type(field) spherebvemodule::bvemesh::absvort
scalar Field
type(field) spherebvemodule::bvemesh::relvort
scalar Field
type(field) spherebvemodule::bvemesh::relstream
scalar Field
type(field) spherebvemodule::bvemesh::absstream
scalar Field
type(field) spherebvemodule::bvemesh::velocity
vector Field
type(field), dimension(:),
allocatable spherebvemodule::bvemesh::tracers
allocatable array of scalar and vector Field objects
real(kreal) spherebvemodule::bvemesh::radius = 1.0_kreal
radius of sphere
real(kreal) spherebvemodule::bvemesh::rotationrate = 0.0_kreal
background rotation rate (angular velocity)
type(mpisetup) spherebvemodule::bvemesh::mpiparticles
MPISetup to distribute all particles over the available MPI ranks
logical(klog), save spherebvemodule::loginit = .FALSE.
type(logger) spherebvemodule::log
character(len=28), save spherebvemodule::logkey = 'BVE'
integer(kint), parameter spherebvemodule::loglevel = DEBUG_LOGGING_LEVEL
Function/Subroutine Documentation
subroutine, public spherebvemodule::addtracers (type(bvemesh), intent(inout) self, integer(kint), intent(in) nTracers, integer(kint), dimension(:), intent(in) tracerDims)
Adds memory for passive tracers to a spherical BVE mesh.
Parameters
[in,out] self Target BVE mesh
[in] nTracers number of tracers to add
[in] tracerDims array of values (each 1, 2, or 3) corresponding to the dimensions of each tracer. Scalar tracers will have dimension 1, vector tracers will have dimension 2 or 3, depending on their coordinate system.
Definition at line 229 of file SphereBVE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine spherebvemodule::copyprivate (type(bvemesh), intent(inout) self, type(bvemesh), intent(in) other) private
Performs a deep copy of a BVE mesh and all of its variables. The target mesh must have been allocated prior to calling this subroutine.
Parameters
[in,out] self Target BVE mesh
[in] other Source BVE Mesh
Definition at line 194 of file SphereBVE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, and loggermodule::warning_logging_level.
subroutine spherebvemodule::copy::copyprivate (type(bvemesh), intent(inout) self, type(bvemesh), intent(in) other) private
Performs a deep copy of a BVE mesh and all of its variables. The target mesh must have been allocated prior to calling this subroutine.
Parameters
[in,out] self Target BVE mesh
[in] other Source BVE Mesh
Definition at line 194 of file SphereBVE.f90.
subroutine spherebvemodule::deleteprivate (type(bvemesh), intent(inout) self) private
Deletes and frees memory associated with a spherical BVE Mesh.
Parameters
[in,out] self Target BVE Mesh
Definition at line 170 of file SphereBVE.f90.
final spherebvemodule::bvemesh::deleteprivate () final private
Definition at line 83 of file SphereBVE.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine spherebvemodule::delete::deleteprivate (type(bvemesh), intent(inout) self) private
Deletes and frees memory associated with a spherical BVE Mesh.
Parameters
[in,out] self Target BVE Mesh
Definition at line 170 of file SphereBVE.f90.
subroutine spherebvemodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the BVE module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 545 of file SphereBVE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine spherebvemodule::logstatsprivate (type(bvemesh), intent(in) self, type(logger), intent(inout) aLog) private
Output basic information about a BVE mesh to a Logger module.
Parameters
[in] self BVE mesh
[in,out] aLog Logger module
Definition at line 250 of file SphereBVE.f90.
References loggermodule::trace_logging_level.
subroutine spherebvemodule::logstats::logstatsprivate (type(bvemesh), intent(in) self, type(logger), intent(inout) aLog) private
Output basic information about a BVE mesh to a Logger module.
Parameters
[in] self BVE mesh
[in,out] aLog Logger module
Definition at line 250 of file SphereBVE.f90.
real(kreal) function, public spherebvemodule::maxcirculationmagnitudeperface (type(bvemesh), intent(in) self)
Computes the maximum circulation magnitude about each face and returns the maximum value for the whole mesh.
Parameters
[in] self BVE mesh
Returns
MaximumCirculation magnitude
Definition at line 516 of file SphereBVE.f90.
subroutine spherebvemodule::newprivate (type(bvemesh), intent(out) self, integer(kint), intent(in) meshSeed, integer(kint), intent(in) initNest, integer(kint), intent(in) maxNest, integer(kint), intent(in) amrLimit, real(kreal), intent(in) sphereRadius, real(kreal), intent(in) rotationRate) private
Allocates memory and initializes a spherical mesh for BVE applications.
Parameters
[out] self new BVE mesh
[in] meshSeed mesh seed integer, as defined in NumberKinds
[in] initNest initial level of uniform refinement
[in] maxNest maximum level of uniform refinment
[in] amrLimit maximum number of times an individual face can be divided beyond initNest
[in] sphereRadius radius of sphere
[in] rotationRate background angular velocity of sphere
Definition at line 139 of file SphereBVE.f90.
References numberkindsmodule::cubed_sphere_seed, loggermodule::error_logging_level, numberkindsmodule::icos_tri_sphere_seed, initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, numberkindsmodule::numprocs, and numberkindsmodule::procrank.
subroutine spherebvemodule::new::newprivate (type(bvemesh), intent(out) self, integer(kint), intent(in) meshSeed, integer(kint), intent(in) initNest, integer(kint), intent(in) maxNest, integer(kint), intent(in) amrLimit, real(kreal), intent(in) sphereRadius, real(kreal), intent(in) rotationRate) private
Allocates memory and initializes a spherical mesh for BVE applications.
Parameters
[out] self new BVE mesh
[in] meshSeed mesh seed integer, as defined in NumberKinds
[in] initNest initial level of uniform refinement
[in] maxNest maximum level of uniform refinment
[in] amrLimit maximum number of times an individual face can be divided beyond initNest
[in] sphereRadius radius of sphere
[in] rotationRate background angular velocity of sphere
Definition at line 139 of file SphereBVE.f90.
subroutine, public spherebvemodule::outputtovtk (type(bvemesh), intent(in) self, character(len=*), intent(in) filename)
Writes a BVE mesh to a legacy formatted .vtk file, including all Field data for variables and tracers.
Parameters
[in] self BVE mesh
[in] filename Name of output file
Definition at line 273 of file SphereBVE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, numberkindsmodule::write_unit_1, facesmodule::writefaceareatovtkcelldata(), facesmodule::writefacestovtkpolygons(), fieldmodule::writefieldtovtkpointdata(), particlesmodule::writevtklagcoords(), outputwritermodule::writevtkpointdatasectionheader(), and particlesmodule::writevtkpoints().
subroutine, public spherebvemodule::setinitialvorticityonmesh (type(bvemesh), intent(inout) self, procedure(scalarfnof3dspace) relVortFn)
Defines an initial vorticity distribution on a BVE mesh.
Parameters
[in,out] self BVE mesh
[in] relVortFn Vorticity distribution function. Must have same interface as numberkindsmodule::scalarFnOf3DSpace
Definition at line 314 of file SphereBVE.f90.
subroutine spherebvemodule::setscalartraceronmesh (type(bvemesh), intent(inout) self, integer(kint), intent(in) tracerId, procedure(scalarfnof3dspace) tracerFn) private
Defines an initial tracer distribution on a BVE mesh.
Parameters
[in,out] self BVE mesh
[in] tracerID index of tracer in bveMesh%tracers(:)
[in] tracerFn Vorticity distribution function. Must have same interface as numberkindsmodule::scalarFnOf3DSpace
Definition at line 351 of file SphereBVE.f90.
References fieldmodule::setfieldtozero().
subroutine, public spherebvemodule::setstreamfunctionsonmesh (type(bvemesh), intent(inout) self)
Defines the absolute and relative stream functions on a BVE mesh using the Green's function integral.
Parameters
[in,out] self BVE mesh
Definition at line 425 of file SphereBVE.f90.
References numberkindsmodule::numprocs, particlesmodule::physcoord(), numberkindsmodule::pi, and numberkindsmodule::procrank.
subroutine spherebvemodule::setvectortraceronmesh (type(bvemesh), intent(inout) self, integer(kint), intent(in) tracerID, procedure(vectorfnof3dspace) tracerFn) private
Defines an initial tracer distribution on a BVE mesh.
Parameters
[in,out] self BVE mesh
[in] tracerID index of tracer in bveMesh%tracers(:)
[in] tracerFn Vorticity distribution function. Must have same interface as numberkindsmodule::vectorFnOf3DSpace
Definition at line 370 of file SphereBVE.f90.
References fieldmodule::setfieldtozero().
subroutine spherebvemodule::setvelocityfromfunction (type(bvemesh), intent(inout) self, procedure(vectorfnof3dspace) velFn) private
Defines an initial velocity distribution on a BVE mesh.
Parameters
[in,out] self BVE mesh
[in] velFn Velocity distribution function. Must have same interface as numberkindsmodule::vectorFnOf3DSpace
Definition at line 335 of file SphereBVE.f90.
References fieldmodule::insertvectortofield().
subroutine spherebvemodule::setvelocityonmesh::setvelocityfromfunction (type(bvemesh), intent(inout) self, procedure(vectorfnof3dspace) velFn) private
Defines an initial velocity distribution on a BVE mesh.
Parameters
[in,out] self BVE mesh
[in] velFn Velocity distribution function. Must have same interface as numberkindsmodule::vectorFnOf3DSpace
Definition at line 335 of file SphereBVE.f90.
subroutine spherebvemodule::setvelocityfromvorticity (type(bvemesh), intent(inout) self) private
Defines the velocity distribution on a BVE mesh using the Biot-Savart integral.
Parameters
[in,out] self BVE mesh
Definition at line 469 of file SphereBVE.f90.
References numberkindsmodule::numprocs, particlesmodule::physcoord(), numberkindsmodule::pi, and numberkindsmodule::procrank.
subroutine spherebvemodule::setvelocityonmesh::setvelocityfromvorticity (type(bvemesh), intent(inout) self) private
Defines the velocity distribution on a BVE mesh using the Biot-Savart integral.
Parameters
[in,out] self BVE mesh
Definition at line 469 of file SphereBVE.f90.
real(kreal) function, public spherebvemodule::totalenstrophy (type(bvemesh), intent(in) self)
Computes the total enstrophy (a conserved integral) on a BVE mesh.
Parameters
[in] self BVE mesh
Returns
totalKE total enstrophy
Definition at line 409 of file SphereBVE.f90.
real(kreal) function, public spherebvemodule::totalke (type(bvemesh), intent(in) self)
Computes the total kinetic energy (a conserved integral) on a BVE mesh.
Parameters
[in] self BVE mesh
Returns
totalKE total kinetic energy
Definition at line 390 of file SphereBVE.f90.
Variable Documentation
type(field) spherebvemodule::bvemesh::absstream private
scalar Field
Definition at line 75 of file SphereBVE.f90.
type(field) spherebvemodule::bvemesh::absvort private
scalar Field
Definition at line 72 of file SphereBVE.f90.
type(logger) spherebvemodule::log private
Definition at line 119 of file SphereBVE.f90.
logical(klog), save spherebvemodule::loginit = .FALSE. private
Definition at line 118 of file SphereBVE.f90.
character(len=28), save spherebvemodule::logkey = 'BVE' private
Definition at line 120 of file SphereBVE.f90.
integer(kint), parameter spherebvemodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 121 of file SphereBVE.f90.
type(polymesh2d) spherebvemodule::bvemesh::mesh private
PolyMesh2d for spatial discretization
Definition at line 71 of file SphereBVE.f90.
type(mpisetup) spherebvemodule::bvemesh::mpiparticles private
MPISetup to distribute all particles over the available MPI ranks
Definition at line 80 of file SphereBVE.f90.
real(kreal) spherebvemodule::bvemesh::radius = 1.0_kreal private
radius of sphere
Definition at line 78 of file SphereBVE.f90.
type(field) spherebvemodule::bvemesh::relstream private
scalar Field
Definition at line 74 of file SphereBVE.f90.
type(field) spherebvemodule::bvemesh::relvort private
scalar Field
Definition at line 73 of file SphereBVE.f90.
real(kreal) spherebvemodule::bvemesh::rotationrate = 0.0_kreal private
background rotation rate (angular velocity)
Definition at line 79 of file SphereBVE.f90.
type(field), dimension(:), allocatable spherebvemodule::bvemesh::tracers private
allocatable array of scalar and vector Field objects
Definition at line 77 of file SphereBVE.f90.
type(field) spherebvemodule::bvemesh::velocity private
vector Field
Definition at line 76 of file SphereBVE.f90.