LPM: Lagrangian Particle Methods: Refinement
Refinement
Data structure and methods for adaptively refining PolyMesh2d objects.
Detailed Description
Data structure and methods for adaptively refining PolyMesh2d objects.
Data Types
interface refinementmodule::new
interface refinementmodule::delete
interface refinementmodule::FlagFunction
Generic interface to a function that flags Faces for refinement.
Functions/Subroutines
final refinementmodule::refinesetup::deleteprivate
subroutine refinementmodule::new::newprivate (self, nMaxFaces)
Allocates memory for a RefineSetup object.
subroutine refinementmodule::delete::deleteprivate (self)
Deletes and frees memory associated with a RefineSetup object.
logical(klog) function refinementmodule::FlagFunction::flagfunction (mesh, dataField, tolerance, faceIndex)
subroutine refinementmodule::newprivate (self, nMaxFaces)
Allocates memory for a RefineSetup object.
subroutine refinementmodule::deleteprivate (self)
Deletes and frees memory associated with a RefineSetup object.
subroutine refinementmodule::divideflaggedfaces (self, mesh)
Calls the appropriate divide face subroutine on every flagged face. Note: New Field values will need to be set after calling this routine for every new particle added here.
subroutine, public refinementmodule::iteratemeshrefinementonevariable (self, aMesh, aField, flagFn, tol, desc, nParticlesStart, nParticlesEnd)
Performs one iteration of mesh refinement using one criterion for one field variable.
subroutine, public refinementmodule::iteratemeshrefinementtwovariables (self, aMesh, field1, flagFn1, tol1, desc1, field2, flagFn2, tol2, desc2, nParticlesStart, nParticlesEnd)
Performs one iteration of mesh refinement using two criteria with two field variables.
subroutine, public refinementmodule::iteratemeshrefinementtwovariablesandflowmap (self, aMesh, field1, flagFn1, tol1, desc1, field2, flagFn2, tol2, desc2, flowMapVarTol, nParticlesStart, nParticlesEnd)
Performs one iteration of mesh refinement using two criteria with two field variables and flow map refinement.
subroutine, public refinementmodule::iteratemeshrefinementonevariableandflowmap (self, aMesh, aField, flagFn, tol, desc, flowMapVarTol, nParticlesStart, nParticlesEnd)
Performs one iteration of mesh refinement using one criterion for one field variable and flow map refinement.
subroutine, public refinementmodule::iteratemeshrefinementforflowmap (self, aMesh, flowMapVarTol, nParticlesStart, nParticlesEnd)
Performs one iteration of mesh refinement using flow map refinement.
logical(klog) function, public refinementmodule::scalarintegralrefinement (mesh, dataField, tol, faceIndex)
Example Flag Function to refine panels whose scalar Field integrals exceed a given tolerance.
logical(klog) function, public refinementmodule::scalarvariationrefinement (mesh, dataField, tol, faceIndex)
Example Flag Function to refine panels whose scalar Field variation per face exceed a given tolerance.
logical(klog) function refinementmodule::flowmapvariationrefinement (mesh, tol, faceIndex)
Flag Function to refine panels whose Lagrangian coordinate variation per face exceed a given tolerance.
subroutine refinementmodule::initlogger (aLog, rank)
Initializes a logger for the Refinement module.
Variables
logical(klog), dimension(:),
pointer refinementmodule::refinesetup::refineflag => null()
Face i will be refined if refineSetup%refineFlag(i) = .TRUE.
type(logger) refinementmodule::log
character(len=28), save refinementmodule::logkey = 'Refine'
character(len=max_string_length) refinementmodule::logstring
integer(kint), parameter refinementmodule::loglevel = DEBUG_LOGGING_LEVEL
Function/Subroutine Documentation
subroutine refinementmodule::deleteprivate (type(refinesetup), intent(inout) self) private
Deletes and frees memory associated with a RefineSetup object.
Parameters
[in,out] self Target RefineSetup object
Definition at line 103 of file Refinement.f90.
final refinementmodule::refinesetup::deleteprivate () final private
Definition at line 41 of file Refinement.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine refinementmodule::delete::deleteprivate (type(refinesetup), intent(inout) self) private
Deletes and frees memory associated with a RefineSetup object.
Parameters
[in,out] self Target RefineSetup object
Definition at line 103 of file Refinement.f90.
subroutine refinementmodule::divideflaggedfaces (type(refinesetup), intent(in) self, type(polymesh2d), intent(inout) mesh) private
Calls the appropriate divide face subroutine on every flagged face. Note: New Field values will need to be set after calling this routine for every new particle added here.
Parameters
[in] self Target RefineSetup object
[in,out] mesh PolyMesh2d to be refined
Definition at line 113 of file Refinement.f90.
References facesmodule::dividequadface(), facesmodule::dividetriface(), betaplanemeshmodule::betaplanemesh::mesh, numberkindsmodule::quad_panel, and numberkindsmodule::tri_panel.
logical(klog) function refinementmodule::FlagFunction::flagfunction (type(polymesh2d), intent(in) mesh, type(field), intent(in) dataField, real(kreal), intent(in) tolerance, integer(kint), intent(in) faceIndex) private
Definition at line 58 of file Refinement.f90.
logical(klog) function refinementmodule::flowmapvariationrefinement (type(polymesh2d), intent(in) mesh, real(kreal), intent(in) tol, integer(kint), intent(in) faceIndex) private
Flag Function to refine panels whose Lagrangian coordinate variation per face exceed a given tolerance.
The variation of the Lagrangian coordinates in face F_j is computed as \(\sum_{i=1}^3 \left(\max_{F_j} x0_i - \min_{F_j} x0_i\right) \), where the max and min are simply the maximum and minimum values of the Lagrangian coordinate components carried by all particles associated with face F_j (center and vertices).
Parameters
[in] mesh PolyMesh2d
[in] tol tolerance value
[in] faceIndex face to flag, if tolerance is exceeded
Returns
Flag value
Definition at line 521 of file Refinement.f90.
References particlesmodule::lagcoord(), and betaplanemeshmodule::betaplanemesh::mesh.
subroutine refinementmodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the Refinement module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 557 of file Refinement.f90.
subroutine, public refinementmodule::iteratemeshrefinementforflowmap (type(refinesetup), intent(inout) self, type(polymesh2d), intent(inout) aMesh, real(kreal), intent(in) flowMapVarTol, integer(kint), intent(out) nParticlesStart, integer(kint), intent(out) nParticlesEnd)
Performs one iteration of mesh refinement using flow map refinement.
One iteration of mesh refinement is performed in the following steps:
Loops over all active faces in a PolyMesh2d, records faces flagged by the flag function
Divides flagged faces
Following a call to this routine, all Field objects that accompany the PolyMesh2d that was refined need to be updated with new values at all new particles.
Parameters
[in,out] self target RefineSetup object
[in,out] aMesh target PolyMesh2d mesh to be refined
[in] flowMapVarTol tolerance for maximum Lagrangian coordinate variation per face
[out] nParticlesStart the number of particles in the mesh upon entry to this subroutine
[out] nParticlesEnd the number of particles in the mesh upon exit from this subroutine
Definition at line 427 of file Refinement.f90.
References refinementmodule::divideflaggedfaces(), and refinementmodule::flowmapvariationrefinement().
subroutine, public refinementmodule::iteratemeshrefinementonevariable (type(refinesetup), intent(inout) self, type(polymesh2d), intent(inout) aMesh, type(field), intent(in) aField, procedure(flagfunction) flagFn, real(kreal), intent(in) tol, character(len=*), intent(in) desc, integer(kint), intent(out) nParticlesStart, integer(kint), intent(out) nParticlesEnd)
Performs one iteration of mesh refinement using one criterion for one field variable.
One iteration of mesh refinement is performed in the following steps:
Loops over all active faces in a PolyMesh2d, records faces flagged by the flag function
Divides flagged faces
Following a call to this routine, all Field objects that accompany the PolyMesh2d that was refined need to be updated with new values at all new particles.
Parameters
[in,out] self target RefineSetup object
[in,out] aMesh target PolyMesh2d mesh to be refined
[in] aField Field whose values will be used to flag faces
[in] flagFn Flag function, must have same interface as refinementmodule::FlagFunction
[in] tol tolerance value for use with Flag Function
[in] desc String describing the type of refinement
[out] nParticlesStart the number of particles in the mesh upon entry to this subroutine
[out] nParticlesEnd the number of particles in the mesh upon exit from this subroutine
Definition at line 176 of file Refinement.f90.
References refinementmodule::divideflaggedfaces(), and refinementmodule::FlagFunction::flagfunction().
subroutine, public refinementmodule::iteratemeshrefinementonevariableandflowmap (type(refinesetup), intent(inout) self, type(polymesh2d), intent(inout) aMesh, type(field), intent(in) aField, procedure(flagfunction) flagFn, real(kreal), intent(in) tol, character(len=*), intent(in) desc, real(kreal), intent(in) flowMapVarTol, integer(kint), intent(out) nParticlesStart, integer(kint), intent(out) nParticlesEnd)
Performs one iteration of mesh refinement using one criterion for one field variable and flow map refinement.
One iteration of mesh refinement is performed in the following steps:
Loops over all active faces in a PolyMesh2d, records faces flagged by the flag function
Divides flagged faces
Following a call to this routine, all Field objects that accompany the PolyMesh2d that was refined need to be updated with new values at all new particles.
Parameters
[in,out] self target RefineSetup object
[in,out] aMesh target PolyMesh2d mesh to be refined
[in] aField Field whose values will be used to flag faces
[in] flagFn Flag function, must have same interface as refinementmodule::FlagFunction
[in] tol tolerance value for use with Flag Function
[in] desc String describing the type of refinement
[in] flowMapVarTol tolerance for maximum Lagrangian coordinate variation per face
[out] nParticlesStart the number of particles in the mesh upon entry to this subroutine
[out] nParticlesEnd the number of particles in the mesh upon exit from this subroutine
Definition at line 367 of file Refinement.f90.
References refinementmodule::divideflaggedfaces(), refinementmodule::FlagFunction::flagfunction(), and refinementmodule::flowmapvariationrefinement().
subroutine, public refinementmodule::iteratemeshrefinementtwovariables (type(refinesetup), intent(inout) self, type(polymesh2d), intent(inout) aMesh, type(field), intent(in) field1, procedure(flagfunction) flagFn1, real(kreal), intent(in) tol1, character(len=*), intent(in) desc1, type(field), intent(in) field2, procedure(flagfunction) flagFn2, real(kreal), intent(in) tol2, character(len=*), intent(in) desc2, integer(kint), intent(out) nParticlesStart, integer(kint), intent(out) nParticlesEnd)
Performs one iteration of mesh refinement using two criteria with two field variables.
One iteration of mesh refinement is performed in the following steps:
Loops over all active faces in a PolyMesh2d, records faces flagged by the flag functions
Divides flagged faces
Following a call to this routine, all Field objects that accompany the PolyMesh2d that was refined need to be updated with new values at all new particles.
Parameters
[in,out] self target RefineSetup object
[in,out] aMesh target PolyMesh2d mesh to be refined
[in] field1 First Field whose values will be used to flag faces
[in] flagFn1 Flag function for use with field1, must have same interface as refinementmodule::FlagFunction
[in] tol1 tolerance value for use with first Flag Function
[in] desc1 String describing the first type of refinement
[in] field2 Second Field whose values will be used to flag faces
[in] flagFn2 Flag function for use with field2, must have same interface as refinementmodule::FlagFunction
[in] tol2 tolerance value for use with second Flag Function
[in] desc2 String describing the second type of refinement
[out] nParticlesStart the number of particles in the mesh upon entry to this subroutine
[out] nParticlesEnd the number of particles in the mesh upon exit from this subroutine
Definition at line 228 of file Refinement.f90.
References refinementmodule::divideflaggedfaces(), and refinementmodule::FlagFunction::flagfunction().
subroutine, public refinementmodule::iteratemeshrefinementtwovariablesandflowmap (type(refinesetup), intent(inout) self, type(polymesh2d), intent(inout) aMesh, type(field), intent(in) field1, procedure(flagfunction) flagFn1, real(kreal), intent(in) tol1, character(len=*), intent(in) desc1, type(field), intent(in) field2, procedure(flagfunction) flagFn2, real(kreal), intent(in) tol2, character(len=*), intent(in) desc2, real(kreal), intent(in) flowMapVarTol, integer(kint), intent(out) nParticlesStart, integer(kint), intent(out) nParticlesEnd)
Performs one iteration of mesh refinement using two criteria with two field variables and flow map refinement.
One iteration of mesh refinement is performed in the following steps:
Loops over all active faces in a PolyMesh2d, records faces flagged by the flag functions
Divides flagged faces
Following a call to this routine, all Field objects that accompany the PolyMesh2d that was refined need to be updated with new values at all new particles.
Parameters
[in,out] self target RefineSetup object
[in,out] aMesh target PolyMesh2d mesh to be refined
[in] field1 First Field whose values will be used to flag faces
[in] flagFn1 Flag function for use with field1, must have same interface as refinementmodule::FlagFunction
[in] tol1 tolerance value for use with first Flag Function
[in] desc1 String describing the first type of refinement
[in] field2 Second Field whose values will be used to flag faces
[in] flagFn2 Flag function for use with field2, must have same interface as refinementmodule::FlagFunction
[in] tol2 tolerance value for use with second Flag Function
[in] desc2 String describing the second type of refinement
[in] flowMapVarTol tolerance for maximum Lagrangian coordinate variation per face
[out] nParticlesStart the number of particles in the mesh upon entry to this subroutine
[out] nParticlesEnd the number of particles in the mesh upon exit from this subroutine
Definition at line 293 of file Refinement.f90.
References refinementmodule::divideflaggedfaces(), refinementmodule::FlagFunction::flagfunction(), and refinementmodule::flowmapvariationrefinement().
subroutine refinementmodule::newprivate (type(refinesetup), intent(out) self, integer(kint), intent(in) nMaxFaces) private
Allocates memory for a RefineSetup object.
Parameters
[out] self Target RefineSetup object
[in] nMaxFaces number of maximum faces allowed in memory
Definition at line 91 of file Refinement.f90.
References initlogger(), and numberkindsmodule::procrank.
subroutine refinementmodule::new::newprivate (type(refinesetup), intent(out) self, integer(kint), intent(in) nMaxFaces) private
Allocates memory for a RefineSetup object.
Parameters
[out] self Target RefineSetup object
[in] nMaxFaces number of maximum faces allowed in memory
Definition at line 91 of file Refinement.f90.
logical(klog) function, public refinementmodule::scalarintegralrefinement (type(polymesh2d), intent(in) mesh, type(field), intent(in) dataField, real(kreal), intent(in) tol, integer(kint), intent(in) faceIndex)
Example Flag Function to refine panels whose scalar Field integrals exceed a given tolerance.
Scalar integrals on face i are approximated using the midpoint rule \(\int_{F_i} f(x)\,dx \approx \) field%scalar(i) * field%area(i). If this value exceeds the tolerance, this function returns .TRUE.
Parameters
[in] mesh PolyMesh2d
[in] dataField scalar Field
[in] tol tolerance value
[in] faceIndex face to flag, if tolerance is exceeded
Returns
Flag value
Definition at line 466 of file Refinement.f90.
References betaplanemeshmodule::betaplanemesh::mesh.
logical(klog) function, public refinementmodule::scalarvariationrefinement (type(polymesh2d), intent(in) mesh, type(field), intent(in) dataField, real(kreal), intent(in) tol, integer(kint), intent(in) faceIndex)
Example Flag Function to refine panels whose scalar Field variation per face exceed a given tolerance.
The scalar variation scalar f(x) of face F_i is computed as \(\max_{F_i} f(x) - \min_{F_i} f(x) \), where the max and min are simply the maximum and minimum values of the scalar field carried by all particles associated with face F_i (center and vertices).
Parameters
[in] mesh PolyMesh2d
[in] dataField scalar Field
[in] tol tolerance value
[in] faceIndex face to flag, if tolerance is exceeded
Returns
Flag value
Definition at line 489 of file Refinement.f90.
References polymesh2dmodule::ccwverticesaroundface(), and betaplanemeshmodule::betaplanemesh::mesh.
Variable Documentation
type(logger) refinementmodule::log private
Definition at line 76 of file Refinement.f90.
character(len=28), save refinementmodule::logkey = 'Refine' private
Definition at line 77 of file Refinement.f90.
integer(kint), parameter refinementmodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 79 of file Refinement.f90.
character(len=max_string_length) refinementmodule::logstring private
Definition at line 78 of file Refinement.f90.
logical(klog), dimension(:), pointer refinementmodule::refinesetup::refineflag => null() private
Face i will be refined if refineSetup%refineFlag(i) = .TRUE.
Definition at line 39 of file Refinement.f90.