LPM: Lagrangian Particle Methods: SphereBVESolver
SphereBVESolver
Data structure for solving the Barotropic Vorticity Equation (BVE) on the surface of a rotating sphere. Used with the SphereBVE module.
Detailed Description
Data structure for solving the Barotropic Vorticity Equation (BVE) on the surface of a rotating sphere. Used with the SphereBVE module.
Data Types
interface spherebvesolvermodule::new
interface spherebvesolvermodule::delete
interface spherebvesolvermodule::timestep
Functions/Subroutines
final spherebvesolvermodule::bvesolver::deleteprivate
subroutine spherebvesolvermodule::new::newprivate (self, sphereBVE)
Allocates memory for a new BVE Solver. Initializes the solver to match the current mesh.
subroutine spherebvesolvermodule::delete::deleteprivate (self)
Deletes and frees memory associated with a BVE Solver.
subroutine spherebvesolvermodule::timestep::timestepprivate (self, sphereBVE, dt)
Advances a BVE mesh forward in time by one timestep using 4th order Runge-Kutta.
subroutine spherebvesolvermodule::newprivate (self, sphereBVE)
Allocates memory for a new BVE Solver. Initializes the solver to match the current mesh.
subroutine spherebvesolvermodule::deleteprivate (self)
Deletes and frees memory associated with a BVE Solver.
subroutine spherebvesolvermodule::timestepprivate (self, sphereBVE, dt)
Advances a BVE mesh forward in time by one timestep using 4th order Runge-Kutta.
subroutine spherebvesolvermodule::bvespherevelocity (u, v, w, x, y, z, relVortIn, areaIn, sphereRadius, rotationRate, activeMask, mpiParticles)
Computes velocity based on the given vorticity of all point vortices (particles) using the Biot-Savart integral. Integral is computed in parallel as a direct summation.
subroutine spherebvesolvermodule::initlogger (aLog, rank)
Initializes a logger for the SphereBVE solver module.
Variables
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::xstart
starting x-coordinate of each particle
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::ystart
starting y-coordinate of each particle
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::zstart
starting z-coordinate of each particle
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::relvortstart
starting vorticity carried by each particle
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::area
area represented by each particle (passive particles represent zero area)
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::u
x-component of velocity for each particle
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::v
y-component of velocity for each particle
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::w
w-component of velocity for each particle
logical(klog), dimension(:),
allocatable spherebvesolvermodule::bvesolver::mask
mask(i) is .TRUE. if particle i is active
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::xin
x-coordinate input to RK4
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::xstage1
x-coordinates of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::xstage2
x-coordinates of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::xstage3
x-coordinates of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::xstage4
x-coordinates of each particle at RK4 stage 4
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::yin
y-coordinate input to RK4
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::ystage1
y-coordinates of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::ystage2
y-coordinates of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::ystage3
y-coordinates of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::ystage4
y-coordinates of each particle at RK4 stage 4
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::zin
z-coordinate input to RK4
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::zstage1
z-coordinates of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::zstage2
z-coordinates of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::zstage3
z-coordinates of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::zstage4
z-coordinates of each particle at RK4 stage 4
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::relvortin
relative vorticity input to RK4
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::relvortstage1
relative vorticity of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::relvortstage2
relative vorticity of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::relvortstage3
relative vorticity of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable spherebvesolvermodule::bvesolver::relvortstage4
relative vorticity of each particle at RK4 stage 4
logical(klog), save spherebvesolvermodule::loginit = .FALSE.
type(logger) spherebvesolvermodule::log
character(len=28), save spherebvesolvermodule::logkey = 'BVESolver'
integer(kint), parameter spherebvesolvermodule::loglevel = DEBUG_LOGGING_LEVEL
Function/Subroutine Documentation
subroutine spherebvesolvermodule::bvespherevelocity (real(kreal), dimension(:), intent(out) u, real(kreal), dimension(:), intent(out) v, real(kreal), dimension(:), intent(out) w, real(kreal), dimension(:), intent(in) x, real(kreal), dimension(:), intent(in) y, real(kreal), dimension(:), intent(in) z, real(kreal), dimension(:), intent(in) relVortIn, real(kreal), dimension(:), intent(in) areaIn, real(kreal), intent(in) sphereRadius, real(kreal), intent(in) rotationRate, logical(klog), dimension(:), intent(in) activeMask, type(mpisetup), intent(in) mpiParticles) private
Computes velocity based on the given vorticity of all point vortices (particles) using the Biot-Savart integral. Integral is computed in parallel as a direct summation.
Parameters
[out] u x-component of velocity at each particle
[out] v y-component of velocity at each particle
[out] w z-component of velocity at each particle
[in] x x-coordinate of each particle
[in] y y-coordinate of each particle
[in] z y-coordinate of each particle
[in] relVortIn vorticity carried by each particle
[in] areaIn area carried by each particle
[in] sphereRadius radius of sphere
[in] rotationRate background angular velocity of sphere
[in] activeMask .TRUE. for active particles, .FALSE. for passive particles
[in] mpiParticles MPISetup object to distribute integral over MPI processes
Definition at line 370 of file SphereBVESolver.f90.
References numberkindsmodule::numprocs, numberkindsmodule::pi, and numberkindsmodule::procrank.
subroutine spherebvesolvermodule::deleteprivate (type(bvesolver), intent(inout) self) private
Deletes and frees memory associated with a BVE Solver.
Parameters
[in,out] self
Definition at line 172 of file SphereBVESolver.f90.
final spherebvesolvermodule::bvesolver::deleteprivate () final private
Definition at line 71 of file SphereBVESolver.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine spherebvesolvermodule::delete::deleteprivate (type(bvesolver), intent(inout) self) private
Deletes and frees memory associated with a BVE Solver.
Parameters
[in,out] self
Definition at line 172 of file SphereBVESolver.f90.
subroutine spherebvesolvermodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the SphereBVE solver module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 430 of file SphereBVESolver.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine spherebvesolvermodule::newprivate (type(bvesolver), intent(out) self, type(bvemesh), intent(in) sphereBVE) private
Allocates memory for a new BVE Solver. Initializes the solver to match the current mesh.
Parameters
[out] self Target BVE Solver
[in] sphereBVE BVE Mesh
Definition at line 112 of file SphereBVESolver.f90.
References initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, and numberkindsmodule::procrank.
subroutine spherebvesolvermodule::new::newprivate (type(bvesolver), intent(out) self, type(bvemesh), intent(in) sphereBVE) private
Allocates memory for a new BVE Solver. Initializes the solver to match the current mesh.
Parameters
[out] self Target BVE Solver
[in] sphereBVE BVE Mesh
Definition at line 112 of file SphereBVESolver.f90.
subroutine spherebvesolvermodule::timestepprivate (type(bvesolver), intent(inout) self, type(bvemesh), intent(inout) sphereBVE, real(kreal), intent(in) dt) private
Advances a BVE mesh forward in time by one timestep using 4th order Runge-Kutta.
Parameters
[in,out] self BVE solver
[in,out] sphereBVE BVE mesh
[in] dt timestep increment
Definition at line 219 of file SphereBVESolver.f90.
References spherebvesolvermodule::bvespherevelocity(), and betaplanemeshmodule::setstreamfunctionsonmesh().
subroutine spherebvesolvermodule::timestep::timestepprivate (type(bvesolver), intent(inout) self, type(bvemesh), intent(inout) sphereBVE, real(kreal), intent(in) dt) private
Advances a BVE mesh forward in time by one timestep using 4th order Runge-Kutta.
Parameters
[in,out] self BVE solver
[in,out] sphereBVE BVE mesh
[in] dt timestep increment
Definition at line 219 of file SphereBVESolver.f90.
Variable Documentation
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::area private
area represented by each particle (passive particles represent zero area)
Definition at line 43 of file SphereBVESolver.f90.
type(logger) spherebvesolvermodule::log private
Definition at line 98 of file SphereBVESolver.f90.
logical(klog), save spherebvesolvermodule::loginit = .FALSE. private
Definition at line 97 of file SphereBVESolver.f90.
character(len=28), save spherebvesolvermodule::logkey = 'BVESolver' private
Definition at line 99 of file SphereBVESolver.f90.
integer(kint), parameter spherebvesolvermodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 100 of file SphereBVESolver.f90.
logical(klog), dimension(:), allocatable spherebvesolvermodule::bvesolver::mask private
mask(i) is .TRUE. if particle i is active
Definition at line 47 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::relvortin private
relative vorticity input to RK4
Definition at line 64 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::relvortstage1 private
relative vorticity of each particle at RK4 stage 1
Definition at line 65 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::relvortstage2 private
relative vorticity of each particle at RK4 stage 2
Definition at line 66 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::relvortstage3 private
relative vorticity of each particle at RK4 stage 3
Definition at line 67 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::relvortstage4 private
relative vorticity of each particle at RK4 stage 4
Definition at line 68 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::relvortstart private
starting vorticity carried by each particle
Definition at line 42 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::u private
x-component of velocity for each particle
Definition at line 44 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::v private
y-component of velocity for each particle
Definition at line 45 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::w private
w-component of velocity for each particle
Definition at line 46 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::xin private
x-coordinate input to RK4
Definition at line 49 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::xstage1 private
x-coordinates of each particle at RK4 stage 1
Definition at line 50 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::xstage2 private
x-coordinates of each particle at RK4 stage 2
Definition at line 51 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::xstage3 private
x-coordinates of each particle at RK4 stage 3
Definition at line 52 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::xstage4 private
x-coordinates of each particle at RK4 stage 4
Definition at line 53 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::xstart private
starting x-coordinate of each particle
Definition at line 39 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::yin private
y-coordinate input to RK4
Definition at line 54 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::ystage1 private
y-coordinates of each particle at RK4 stage 1
Definition at line 55 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::ystage2 private
y-coordinates of each particle at RK4 stage 2
Definition at line 56 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::ystage3 private
y-coordinates of each particle at RK4 stage 3
Definition at line 57 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::ystage4 private
y-coordinates of each particle at RK4 stage 4
Definition at line 58 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::ystart private
starting y-coordinate of each particle
Definition at line 40 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::zin private
z-coordinate input to RK4
Definition at line 59 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::zstage1 private
z-coordinates of each particle at RK4 stage 1
Definition at line 60 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::zstage2 private
z-coordinates of each particle at RK4 stage 2
Definition at line 61 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::zstage3 private
z-coordinates of each particle at RK4 stage 3
Definition at line 62 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::zstage4 private
z-coordinates of each particle at RK4 stage 4
Definition at line 63 of file SphereBVESolver.f90.
real(kreal), dimension(:), allocatable spherebvesolvermodule::bvesolver::zstart private
starting z-coordinate of each particle
Definition at line 41 of file SphereBVESolver.f90.