LPM: Lagrangian Particle Method: PlanarIncompressible
PlanarIncompressible
Data structure for solving the fluid equations for two-dimensional (in the plane) inviscid, incompressible flow.
Detailed Description
Data structure for solving the fluid equations for two-dimensional (in the plane) inviscid, incompressible flow.
Inviscid planar incompressible flow may be characterized completely by the flow's vorticity and stream function. This module provides a data structure for discretizing the flow using a collection of point vortices. Each point vortex carries vorticity and is advected by the velocity induced by all other vortices.
The spatial domain is discretized in space and time by a PolyMesh2d object. Associated Field objects for vorticity, velocity, and the stream function are provided, as well as a set of optional Field objects for passive tracers carried by the flow.
Currently, only free boundary conditions are supported. The flow is integrated in time using a PlanarIncompressibleSolver object.
The data structure is designed to use a replicated data algorithm (via the MPISetup module) for efficiency in parallel computing environments.
Output routines suitable for reading/dispaly with Paraview are provided.
Data Types
interface planarincompressiblemodule::new
interface planarincompressiblemodule::delete
interface planarincompressiblemodule::copy
interface planarincompressiblemodule::logstats
interface planarincompressiblemodule::setvelocityonmesh
Functions/Subroutines
final planarincompressiblemodule::planemeshincompressible::deleteprivate
subroutine planarincompressiblemodule::new::newprivate (self, initNest, maxNest, meshSeed, amrLimit, meshRadius)
Allocates memory and initializes a PlanarIncompressible mesh with accompanying Field objects for physical variables. Tracers must be added separately, if desired.
subroutine planarincompressiblemodule::delete::deleteprivate (self)
Deletes and frees memory associated with a PlanarIncompressible mesh.
subroutine planarincompressiblemodule::copy::copyprivate (self, other)
Performs a deep copy of one PlanarIncompressible mesh into another. Both objects must have already been allocated.
subroutine planarincompressiblemodule::logstats::logstatsprivate (self, alog)
Output basic information about a PlanarIncompressible mesh to a Logger module.
subroutine planarincompressiblemodule::setvelocityonmesh::setvelocityfromfunction (self, velFn)
Defines an initial velocity distribution on a PlanarIncompressible mesh.
subroutine planarincompressiblemodule::setvelocityonmesh::setvelocityfromvorticity (self)
Defines the velocity distribution on a PlanarIncompressible mesh using the Biot-Savart integral.
subroutine planarincompressiblemodule::newprivate (self, initNest, maxNest, meshSeed, amrLimit, meshRadius)
Allocates memory and initializes a PlanarIncompressible mesh with accompanying Field objects for physical variables. Tracers must be added separately, if desired.
subroutine planarincompressiblemodule::deleteprivate (self)
Deletes and frees memory associated with a PlanarIncompressible mesh.
subroutine planarincompressiblemodule::copyprivate (self, other)
Performs a deep copy of one PlanarIncompressible mesh into another. Both objects must have already been allocated.
subroutine, public planarincompressiblemodule::addtracers (self, nTracers, tracerDims)
Adds memory for passive tracers to a PlanarIncompressible mesh.
subroutine planarincompressiblemodule::logstatsprivate (self, alog)
Output basic information about a PlanarIncompressible mesh to a Logger module.
subroutine, public planarincompressiblemodule::setabsolutetolerances (self, circTol, lagVarTol)
Sets absolute tolerances for AMR criteria based on an initially uniform mesh with corresponding vorticity distribution.
subroutine, public planarincompressiblemodule::outputtovtk (self, filename)
Writes a PlanarIncompressible mesh to a legacy formatted .vtk file, including all Field data for variables and tracers.
subroutine, public planarincompressiblemodule::setinitialvorticityonmesh (self, vortFn)
Defines an initial vorticity distribution on a PlanarIncompressible mesh.
subroutine planarincompressiblemodule::setvelocityfromfunction (self, velFn)
Defines an initial velocity distribution on a PlanarIncompressible mesh.
subroutine planarincompressiblemodule::setscalartraceronmesh (self, tracerID, tracerFn)
Defines an initial scalar tracer distribution on a PlanarIncompressible mesh.
subroutine planarincompressiblemodule::setvectortraceronmesh (self, tracerID, tracerFn)
Defines an initial scalar tracer distribution on a PlanarIncompressible mesh.
real(kreal) function, public planarincompressiblemodule::totalke (self)
Computes the total kinetic engery (a conserved integral) on a PlanarIncompressible mesh.
real(kreal) function, public planarincompressiblemodule::totalenstrophy (self)
Computes the total enstrophy (a conserved integral) on a PlanarIncompressible mesh.
real(kreal) function, public planarincompressiblemodule::maxcirculationperface (self)
Computes the maximum circulation magnitude about each face and returns the maximum value for the whole mesh.
subroutine planarincompressiblemodule::setvelocityfromvorticity (self)
Defines the velocity distribution on a PlanarIncompressible mesh using the Biot-Savart integral.
subroutine, public planarincompressiblemodule::setstreamfunctiononmesh (self)
Defines the stream function on a PlanarIncompressible mesh using the Green's function integral.
subroutine planarincompressiblemodule::initlogger (aLog, rank)
Initializes a logger for the PlanarIncompressible module.
Variables
type(polymesh2d) planarincompressiblemodule::planemeshincompressible::mesh
PolyMesh2d for spatial discretization
type(field) planarincompressiblemodule::planemeshincompressible::vorticity
scalar Field
type(field) planarincompressiblemodule::planemeshincompressible::streamfn
scalar Field
type(field) planarincompressiblemodule::planemeshincompressible::velocity
vector Field
type(field), dimension(:),
allocatable planarincompressiblemodule::planemeshincompressible::tracers
allocatable array of scalar and vector Field objects
type(mpisetup) planarincompressiblemodule::planemeshincompressible::mpiparticles
MPISetup to distribute all particles over the available MPI ranks
logical(klog) planarincompressiblemodule::planemeshincompressible::useamr = .FALSE.
.TRUE. if mesh will be adaptively refined
logical(klog), save planarincompressiblemodule::loginit = .FALSE.
type(logger) planarincompressiblemodule::log
character(len=28), save planarincompressiblemodule::logkey = 'PlaneIncomp'
integer(kint), parameter planarincompressiblemodule::loglevel = DEBUG_LOGGING_LEVEL
character(len=max_string_length) planarincompressiblemodule::logstring
Function/Subroutine Documentation
subroutine, public planarincompressiblemodule::addtracers (type(planemeshincompressible), intent(inout) self, integer(kint), intent(in) nTracers, integer(kint), dimension(:), intent(in) tracerDims)
Adds memory for passive tracers to a PlanarIncompressible mesh.
Parameters
[in,out] self PlanarIncompressible mesh
[in] nTracers number of tracers to add
[in] tracerDims array of values (either 1 or 2) corresponding to the dimensions of each tracer. Scalar tracers will have dimension 1, vector tracers will have dimension 2.
Definition at line 188 of file PlanarIncompressible.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine planarincompressiblemodule::copyprivate (type(planemeshincompressible), intent(inout) self, type(planemeshincompressible), intent(in) other) private
Performs a deep copy of one PlanarIncompressible mesh into another. Both objects must have already been allocated.
Parameters
[out] self Target PlanarIncompressible mesh
[in] other Source PlanarIncompressible mesh
Definition at line 166 of file PlanarIncompressible.f90.
subroutine planarincompressiblemodule::copy::copyprivate (type(planemeshincompressible), intent(inout) self, type(planemeshincompressible), intent(in) other) private
Performs a deep copy of one PlanarIncompressible mesh into another. Both objects must have already been allocated.
Parameters
[out] self Target PlanarIncompressible mesh
[in] other Source PlanarIncompressible mesh
Definition at line 166 of file PlanarIncompressible.f90.
subroutine planarincompressiblemodule::deleteprivate (type(planemeshincompressible), intent(inout) self) private
Deletes and frees memory associated with a PlanarIncompressible mesh.
Parameters
self Planar Incompressible mesh
Definition at line 145 of file PlanarIncompressible.f90.
final planarincompressiblemodule::planemeshincompressible::deleteprivate () final private
Definition at line 67 of file PlanarIncompressible.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine planarincompressiblemodule::delete::deleteprivate (type(planemeshincompressible), intent(inout) self) private
Deletes and frees memory associated with a PlanarIncompressible mesh.
Parameters
self Planar Incompressible mesh
Definition at line 145 of file PlanarIncompressible.f90.
subroutine planarincompressiblemodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the PlanarIncompressible module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 501 of file PlanarIncompressible.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine planarincompressiblemodule::logstatsprivate (type(planemeshincompressible), intent(in) self, type(logger), intent(inout) alog) private
Output basic information about a PlanarIncompressible mesh to a Logger module.
Parameters
[in] self PlanarIncompressible mesh
[in,out] aLog Logger module
Definition at line 210 of file PlanarIncompressible.f90.
subroutine planarincompressiblemodule::logstats::logstatsprivate (type(planemeshincompressible), intent(in) self, type(logger), intent(inout) alog) private
Output basic information about a PlanarIncompressible mesh to a Logger module.
Parameters
[in] self PlanarIncompressible mesh
[in,out] aLog Logger module
Definition at line 210 of file PlanarIncompressible.f90.
real(kreal) function, public planarincompressiblemodule::maxcirculationperface (type(planemeshincompressible), intent(in) self)
Computes the maximum circulation magnitude about each face and returns the maximum value for the whole mesh.
Parameters
[in] self PlanarIncompressible mesh
Returns
MaximumCirculation magnitude
Definition at line 390 of file PlanarIncompressible.f90.
subroutine planarincompressiblemodule::newprivate (type(planemeshincompressible), intent(out) self, integer(kint), intent(in) initNest, integer(kint), intent(in) maxNest, integer(kint), intent(in) meshSeed, integer(kint), intent(in) amrLimit, real(kreal), intent(in) meshRadius) private
Allocates memory and initializes a PlanarIncompressible mesh with accompanying Field objects for physical variables. Tracers must be added separately, if desired.
Parameters
[out] self PlanarIncompressible mesh
[in] initNest initial recursion level for PolyMesh2d
[in] maxNest maximum recursion level for PolyMesh2d
[in] meshSeed mesh seed integer as defined by NumberKinds
[in] amrLimit maximum number of refinements beyond initNest allowed
[in] meshRadius maximum spatial extent of mesh from origin
Definition at line 123 of file PlanarIncompressible.f90.
References initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, numberkindsmodule::numprocs, and numberkindsmodule::procrank.
subroutine planarincompressiblemodule::new::newprivate (type(planemeshincompressible), intent(out) self, integer(kint), intent(in) initNest, integer(kint), intent(in) maxNest, integer(kint), intent(in) meshSeed, integer(kint), intent(in) amrLimit, real(kreal), intent(in) meshRadius) private
Allocates memory and initializes a PlanarIncompressible mesh with accompanying Field objects for physical variables. Tracers must be added separately, if desired.
Parameters
[out] self PlanarIncompressible mesh
[in] initNest initial recursion level for PolyMesh2d
[in] maxNest maximum recursion level for PolyMesh2d
[in] meshSeed mesh seed integer as defined by NumberKinds
[in] amrLimit maximum number of refinements beyond initNest allowed
[in] meshRadius maximum spatial extent of mesh from origin
Definition at line 123 of file PlanarIncompressible.f90.
subroutine, public planarincompressiblemodule::outputtovtk (type(planemeshincompressible), intent(in) self, character(len=*), intent(in) filename)
Writes a PlanarIncompressible mesh to a legacy formatted .vtk file, including all Field data for variables and tracers.
Parameters
[in] self PlanarIncompressible mesh
[in] filename Name of output file
Definition at line 238 of file PlanarIncompressible.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, numberkindsmodule::write_unit_1, facesmodule::writefaceareatovtkcelldata(), facesmodule::writefacestovtkpolygons(), fieldmodule::writefieldtovtkpointdata(), particlesmodule::writevtklagcoords(), outputwritermodule::writevtkpointdatasectionheader(), and particlesmodule::writevtkpoints().
subroutine, public planarincompressiblemodule::setabsolutetolerances (type(planemeshincompressible), intent(in) self, real(kreal), intent(inout) circTol, real(kreal), intent(inout) lagVarTol)
Sets absolute tolerances for AMR criteria based on an initially uniform mesh with corresponding vorticity distribution.
Parameters
[in] self PlanarIncompressible mesh
[in,out] circTol On input, relative tolerance (between 0 and 1). On output, absolute tolerance for circulation magnitude about a face.
[in,out] lagVarTol On input, relative tolerance (between 0 and 1). On output, absolute tolerance for Lagrangian variation magnitude on each face.
Definition at line 226 of file PlanarIncompressible.f90.
References planarincompressiblemodule::maxcirculationperface(), and polymesh2dmodule::maxlagrangianvariationperface().
subroutine, public planarincompressiblemodule::setinitialvorticityonmesh (type(planemeshincompressible), intent(inout) self, procedure(scalarfnof2dspace) vortFn)
Defines an initial vorticity distribution on a PlanarIncompressible mesh.
Parameters
[in,out] self PlanarIncompressible mesh
[in] vortFn Vorticity distribution function. Must have same interface as numberkindsmodule::scalarFnOf2DSpace
Definition at line 279 of file PlanarIncompressible.f90.
subroutine planarincompressiblemodule::setscalartraceronmesh (type(planemeshincompressible), intent(inout) self, integer(kint), intent(in) tracerID, procedure(scalarfnof2dspace) tracerFn) private
Defines an initial scalar tracer distribution on a PlanarIncompressible mesh.
Parameters
[in,out] self PlanarIncompressible mesh
[in] tracerID index of tracer in PlanarIncompressiblMesh%tracers(:)
[in] tracerFn Tracer distribution function. Must have same interface as numberkindsmodule::scalarFnOf2DSpace
Definition at line 315 of file PlanarIncompressible.f90.
subroutine, public planarincompressiblemodule::setstreamfunctiononmesh (type(planemeshincompressible), intent(inout) self)
Defines the stream function on a PlanarIncompressible mesh using the Green's function integral.
Parameters
[in,out] self PlanarIncompressible mesh
Definition at line 454 of file PlanarIncompressible.f90.
References numberkindsmodule::numprocs, numberkindsmodule::pi, and numberkindsmodule::procrank.
subroutine planarincompressiblemodule::setvectortraceronmesh (type(planemeshincompressible), intent(inout) self, integer(kint), intent(in) tracerID, procedure(vectorfnof2dspace) tracerFn) private
Defines an initial scalar tracer distribution on a PlanarIncompressible mesh.
Parameters
[in,out] self PlanarIncompressible mesh
[in] tracerID index of tracer in PlanarIncompressiblMesh%tracers(:)
[in] tracerFn Tracer distribution function. Must have same interface as numberkindsmodule::vectorFnOf2DSpace
Definition at line 333 of file PlanarIncompressible.f90.
subroutine planarincompressiblemodule::setvelocityfromfunction (type(planemeshincompressible), intent(inout) self, procedure(vectorfnof2dspace) velFn) private
Defines an initial velocity distribution on a PlanarIncompressible mesh.
Parameters
[in,out] self PlanarIncompressible mesh
[in] velFn Velocity distribution function. Must have same interface as numberkindsmodule::vectorFnOf2DSpace
Definition at line 295 of file PlanarIncompressible.f90.
subroutine planarincompressiblemodule::setvelocityonmesh::setvelocityfromfunction (type(planemeshincompressible), intent(inout) self, procedure(vectorfnof2dspace) velFn) private
Defines an initial velocity distribution on a PlanarIncompressible mesh.
Parameters
[in,out] self PlanarIncompressible mesh
[in] velFn Velocity distribution function. Must have same interface as numberkindsmodule::vectorFnOf2DSpace
Definition at line 295 of file PlanarIncompressible.f90.
subroutine planarincompressiblemodule::setvelocityfromvorticity (type(planemeshincompressible), intent(inout) self) private
Defines the velocity distribution on a PlanarIncompressible mesh using the Biot-Savart integral.
Parameters
[in,out] self PlanarIncompressible mesh
Definition at line 410 of file PlanarIncompressible.f90.
References numberkindsmodule::numprocs, numberkindsmodule::pi, and numberkindsmodule::procrank.
subroutine planarincompressiblemodule::setvelocityonmesh::setvelocityfromvorticity (type(planemeshincompressible), intent(inout) self) private
Defines the velocity distribution on a PlanarIncompressible mesh using the Biot-Savart integral.
Parameters
[in,out] self PlanarIncompressible mesh
Definition at line 410 of file PlanarIncompressible.f90.
real(kreal) function, public planarincompressiblemodule::totalenstrophy (type(planemeshincompressible), intent(in) self)
Computes the total enstrophy (a conserved integral) on a PlanarIncompressible mesh.
Parameters
[in] self PlanarIncompressible mesh
Returns
totalEnstrophy
Definition at line 372 of file PlanarIncompressible.f90.
real(kreal) function, public planarincompressiblemodule::totalke (type(planemeshincompressible), intent(in) self)
Computes the total kinetic engery (a conserved integral) on a PlanarIncompressible mesh.
Parameters
[in] self PlanarIncompressible mesh
Returns
totalKE total kinetic energy
Definition at line 352 of file PlanarIncompressible.f90.
Variable Documentation
type(logger) planarincompressiblemodule::log private
Definition at line 102 of file PlanarIncompressible.f90.
logical(klog), save planarincompressiblemodule::loginit = .FALSE. private
Definition at line 101 of file PlanarIncompressible.f90.
character(len=28), save planarincompressiblemodule::logkey = 'PlaneIncomp' private
Definition at line 103 of file PlanarIncompressible.f90.
integer(kint), parameter planarincompressiblemodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 104 of file PlanarIncompressible.f90.
character(len=max_string_length) planarincompressiblemodule::logstring private
Definition at line 105 of file PlanarIncompressible.f90.
type(polymesh2d) planarincompressiblemodule::planemeshincompressible::mesh private
PolyMesh2d for spatial discretization
Definition at line 58 of file PlanarIncompressible.f90.
type(mpisetup) planarincompressiblemodule::planemeshincompressible::mpiparticles private
MPISetup to distribute all particles over the available MPI ranks
Definition at line 63 of file PlanarIncompressible.f90.
type(field) planarincompressiblemodule::planemeshincompressible::streamfn private
scalar Field
Definition at line 60 of file PlanarIncompressible.f90.
type(field), dimension(:), allocatable planarincompressiblemodule::planemeshincompressible::tracers private
allocatable array of scalar and vector Field objects
Definition at line 62 of file PlanarIncompressible.f90.
logical(klog) planarincompressiblemodule::planemeshincompressible::useamr = .FALSE. private
.TRUE. if mesh will be adaptively refined
Definition at line 64 of file PlanarIncompressible.f90.
type(field) planarincompressiblemodule::planemeshincompressible::velocity private
vector Field
Definition at line 61 of file PlanarIncompressible.f90.
type(field) planarincompressiblemodule::planemeshincompressible::vorticity private
scalar Field
Definition at line 59 of file PlanarIncompressible.f90.