LPM: Lagrangian Particle Methods: BIVARRemesh
BIVARRemesh
Data structure and methods for remapping planar LPM data using the BIVAR package. Uses the interfaces provided by BIVARInterface.
Detailed Description
Data structure and methods for remapping planar LPM data using the BIVAR package. Uses the interfaces provided by BIVARInterface.
For references describing the BIVAR package, see the BIVARInterface module's detailed description.
Functions/Subroutines
subroutine, public bivarremeshmodule::directremeshbetaplane (oldBetaPlane, newBetaPlane, AMR, vortFlagFn1, tol1, desc1, flagFn2, tol2, desc2, field2)
Performs a remesh/remap of an LPM simulation using direct interpolation of all variables in a BetaPlane mesh.
subroutine, public bivarremeshmodule::lagrangianremeshbetaplanewithvorticityfunction (oldBetaPlane, newBetaPlane, AMR, relVortFn, flagFn1, tol1, desc1, flagFn2, tol2, desc2, RefineFLowMapYN, flowMapVarTol, nLagTracers, tracerFn1, tracerFn2)
Performs a remesh/remap of an LPM simulation using indirect interpolation of all variables in a BetaPlane mesh. Remaps to reference time t = 0.
subroutine, public bivarremeshmodule::lagrangianremeshplanarincompressiblewithvorticityfunction (newPlane, oldPlane, vortFn, flagFn1, tol1, desc1, flagFn2, tol2, desc2, RefineFLowMapYN, flowMapVarTol, nLagTracers, tracerFn1, tracerFn2)
Performs a remesh/remap of an LPM simulation using indirect interpolation of all variables in a PlanarIncompressible mesh. Remaps to reference time t = 0.
subroutine, public bivarremeshmodule::lagrangianremeshplanarincompressibletoreferencemesh (newPlane, oldPlane, refPlane, flagFn1, tol1, desc1, flagFn2, tol2, desc2, RefineFLowMapYN, flowMapVarTol)
Performs a remesh/remap of an LPM simulation using indirect interpolation of all variables in a PlanarIncompressible mesh. Remaps to reference time t = t_{rm}, where t_{rm} is time of definition for a reference mesh (numerical solution). Note that the reference mesh's Lagrangian parameter has been reset, so that x = x0, y = y0 at t = t_{rm}.
subroutine bivarremeshmodule::initlogger (aLog, rank)
Initializes a logger for the BIVARRemesh module.
Variables
type(logger) bivarremeshmodule::log
character(len=28), save bivarremeshmodule::logkey = 'BIVARRemesh'
integer(kint), parameter bivarremeshmodule::loglevel = DEBUG_LOGGING_LEVEL
character(len=max_string_length) bivarremeshmodule::logstring
Function/Subroutine Documentation
subroutine, public bivarremeshmodule::directremeshbetaplane (type(betaplanemesh), intent(in) oldBetaPlane, type(betaplanemesh), intent(inout) newBetaPlane, logical(klog), intent(in) AMR, procedure(flagfunction), optional vortFlagFn1, real(kreal), intent(in), optional tol1, character(len=*), intent(in), optional desc1, procedure(flagfunction), optional flagFn2, real(kreal), intent(in), optional tol2, character(len=*), intent(in), optional desc2, type(field), intent(inout), optional field2)
Performs a remesh/remap of an LPM simulation using direct interpolation of all variables in a BetaPlane mesh.
Parameters
[in] oldBetaPlane BetaPlane source
[in,out] newBetaPlane BetaPlane target
[in] AMR .TRUE. if adaptive refinement will be used
[in] vortFlagFn1 Flag function for vorticity, must have same interface as refinementmodule::FlagFunction
[in] tol1 tolerance for first flag function
[in] desc1 description of first type of refinement
[in] flagFn2 Flag function for field2, must have same interface as refinementmodule::FlagFunction
[in] tol2 tolerance for second flag function
[in] desc2 description of second type of refinement
[in] field2 Field to use for second type of refinement
Definition at line 80 of file BIVARRemesh.f90.
References initlogger(), bivarinterfacemodule::interpolatelagparam(), bivarinterfacemodule::interpolatescalar(), bivarinterfacemodule::interpolatevector(), refinementmodule::iteratemeshrefinementonevariable(), refinementmodule::iteratemeshrefinementtwovariables(), mpisetupmodule::loadbalance(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, numberkindsmodule::numprocs, numberkindsmodule::procrank, and betaplanemeshmodule::setstreamfunctionsonmesh().
subroutine bivarremeshmodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the BIVARRemesh module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 794 of file BIVARRemesh.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine, public bivarremeshmodule::lagrangianremeshbetaplanewithvorticityfunction (type(betaplanemesh), intent(in) oldBetaPlane, type(betaplanemesh), intent(inout) newBetaPlane, logical(klog), intent(in) AMR, procedure(scalarfnof2dspace) relVortFn, procedure(flagfunction) flagFn1, real(kreal), intent(in) tol1, character(len=*), intent(in) desc1, procedure(flagfunction), optional flagFn2, real(kreal), intent(in), optional tol2, character(len=*), intent(in), optional desc2, logical(klog), intent(in), optional RefineFLowMapYN, real(kreal), intent(in), optional flowMapVarTol, integer(kint), intent(in), optional nLagTracers, procedure(scalarfnof2dspace), optional tracerFn1, procedure(scalarfnof2dspace), optional tracerFn2)
Performs a remesh/remap of an LPM simulation using indirect interpolation of all variables in a BetaPlane mesh. Remaps to reference time t = 0.
Parameters
[in] oldBetaPlane BetaPlane source
[in,out] newBetaPlane BetaPlane target
[in] AMR .TRUE. if adaptive refinement will be used
[in] relVortFn Vorticity distribution function, must have same interface as numberkindsmodule::scalarFnOf2DSpace
[in] flagFn1 Flag function for vorticity, must have same interface as refinementmodule::FlagFunction
[in] tol1 tolerance for first flag function
[in] desc1 description of first type of refinement
[in] flagFn2 Flag function for field2, must have same interface as refinementmodule::FlagFunction
[in] tol2 tolerance for second flag function
[in] desc2 description of second type of refinement
[in] RefineFLowMapYN True if refinement of the flow map will be used
[in] flowMapVarTol tolerance value for Lagrangian coordinate variation per face
[in] nLagTracers number of Lagrangian passive tracers (currently 0, 1, or 2 are only values allowed)
[in] tracerFn1 tracer distribution function, must have same interface as numberkindsmodule::scalarFnOf2DSpace
[in] tracerFn2 tracer distribution function, must have same interface as numberkindsmodule::scalarFnOf2DSpace
Definition at line 235 of file BIVARRemesh.f90.
References initlogger(), bivarinterfacemodule::interpolatelagparam(), bivarinterfacemodule::interpolatescalar(), bivarinterfacemodule::interpolatevector(), refinementmodule::iteratemeshrefinementonevariable(), refinementmodule::iteratemeshrefinementonevariableandflowmap(), refinementmodule::iteratemeshrefinementtwovariables(), refinementmodule::iteratemeshrefinementtwovariablesandflowmap(), mpisetupmodule::loadbalance(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, numberkindsmodule::numprocs, numberkindsmodule::procrank, and betaplanemeshmodule::setstreamfunctionsonmesh().
subroutine, public bivarremeshmodule::lagrangianremeshplanarincompressibletoreferencemesh (type(planemeshincompressible), intent(inout) newPlane, type(planemeshincompressible), intent(in) oldPlane, type(planemeshincompressible), intent(in) refPlane, procedure(flagfunction) flagFn1, real(kreal), intent(in) tol1, character(len=*), intent(in) desc1, procedure(flagfunction), optional flagFn2, real(kreal), intent(in), optional tol2, character(len=*), intent(in), optional desc2, logical(klog), intent(in), optional RefineFLowMapYN, real(kreal), intent(in), optional flowMapVarTol)
Performs a remesh/remap of an LPM simulation using indirect interpolation of all variables in a PlanarIncompressible mesh. Remaps to reference time t = t_{rm}, where t_{rm} is time of definition for a reference mesh (numerical solution). Note that the reference mesh's Lagrangian parameter has been reset, so that x = x0, y = y0 at t = t_{rm}.
Parameters
[in,out] newPlane PlanarIncompressible target
[in] oldPlane PlanarIncompressible source
[in] refPlane PlanarIncompressible reference
[in] flagFn1 Flag function for vorticity, must have same interface as refinementmodule::FlagFunction
[in] tol1 tolerance for first flag function
[in] desc1 description of first type of refinement
[in] flagFn2 Flag function for field2, must have same interface as refinementmodule::FlagFunction
[in] tol2 tolerance for second flag function
[in] desc2 description of second type of refinement
[in] RefineFLowMapYN True if refinement of the flow map will be used
[in] flowMapVarTol tolerance value for Lagrangian coordinate variation per face
Definition at line 625 of file BIVARRemesh.f90.
References bivarinterfacemodule::interpolatelagparam(), bivarinterfacemodule::interpolatescalar(), bivarinterfacemodule::interpolatevector(), refinementmodule::iteratemeshrefinementonevariable(), refinementmodule::iteratemeshrefinementonevariableandflowmap(), refinementmodule::iteratemeshrefinementtwovariables(), refinementmodule::iteratemeshrefinementtwovariablesandflowmap(), mpisetupmodule::loadbalance(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, numberkindsmodule::numprocs, bivarinterfacemodule::setbivarmd(), and planarincompressiblemodule::setstreamfunctiononmesh().
subroutine, public bivarremeshmodule::lagrangianremeshplanarincompressiblewithvorticityfunction (type(planemeshincompressible), intent(inout) newPlane, type(planemeshincompressible), intent(in) oldPlane, procedure(scalarfnof2dspace) vortFn, procedure(flagfunction) flagFn1, real(kreal), intent(in) tol1, character(len=*), intent(in) desc1, procedure(flagfunction), optional flagFn2, real(kreal), intent(in), optional tol2, character(len=*), intent(in), optional desc2, logical(klog), intent(in), optional RefineFLowMapYN, real(kreal), intent(in), optional flowMapVarTol, integer(kint), intent(in), optional nLagTracers, procedure(scalarfnof2dspace), optional tracerFn1, procedure(scalarfnof2dspace), optional tracerFn2)
Performs a remesh/remap of an LPM simulation using indirect interpolation of all variables in a PlanarIncompressible mesh. Remaps to reference time t = 0.
Parameters
[in,out] newPlane PlanarIncompressible target
[in] oldPlane PlanarIncompressible source
[in] vortFn Vorticity distribution function, must have same interface as numberkindsmodule::scalarFnOf2DSpace
[in] flagFn1 Flag function for vorticity, must have same interface as refinementmodule::FlagFunction
[in] tol1 tolerance for first flag function
[in] desc1 description of first type of refinement
[in] flagFn2 Flag function for field2, must have same interface as refinementmodule::FlagFunction
[in] tol2 tolerance for second flag function
[in] desc2 description of second type of refinement
[in] RefineFLowMapYN True if refinement of the flow map will be used
[in] flowMapVarTol tolerance value for Lagrangian coordinate variation per face
[in] nLagTracers number of Lagrangian passive tracers (currently 0, 1, or 2 are only values allowed)
[in] tracerFn1 tracer distribution function, must have same interface as numberkindsmodule::scalarFnOf2DSpace
[in] tracerFn2 tracer distribution function, must have same interface as numberkindsmodule::scalarFnOf2DSpace
Definition at line 438 of file BIVARRemesh.f90.
References initlogger(), bivarinterfacemodule::interpolatelagparam(), bivarinterfacemodule::interpolatescalar(), bivarinterfacemodule::interpolatevector(), refinementmodule::iteratemeshrefinementonevariable(), refinementmodule::iteratemeshrefinementonevariableandflowmap(), refinementmodule::iteratemeshrefinementtwovariables(), refinementmodule::iteratemeshrefinementtwovariablesandflowmap(), mpisetupmodule::loadbalance(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, numberkindsmodule::numprocs, numberkindsmodule::procrank, bivarinterfacemodule::setbivarmd(), and planarincompressiblemodule::setstreamfunctiononmesh().
Variable Documentation
type(logger) bivarremeshmodule::log private
Definition at line 56 of file BIVARRemesh.f90.
character(len=28), save bivarremeshmodule::logkey = 'BIVARRemesh' private
Definition at line 57 of file BIVARRemesh.f90.
integer(kint), parameter bivarremeshmodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 58 of file BIVARRemesh.f90.
character(len=max_string_length) bivarremeshmodule::logstring private
Definition at line 59 of file BIVARRemesh.f90.