LPM: Lagrangian Particle Methods: ssrfpackInterface
ssrfpackInterface
Interface and workspace for interpolation of LPM data in spherical domains using the STRIPACK and SSRFPACK libraries.
Detailed Description
Interface and workspace for interpolation of LPM data in spherical domains using the STRIPACK and SSRFPACK libraries.
STRIPACK produces a Delaunay triangulation of scattered data points on the surface of a unit sphere.
SSRFPACK performs interpolation on that triangulation using a linear combination of cubic Hermite splines with exponential tension factors. Derivatives for the Hermite interpolating polynomials are estimated using a least-squares projection onto local quadratic polynomials.
For more information, see
R. Renka, Algorithm 772: STRIPACK: Delaunay triangulation and Voronoi diagram on the surface of a sphere, ACM TOMS 23, 1997. (stripack.f)
R. Renka, Algorithm 773: SSRFPACK: Interpolation scattered data on the surface of a sphere with a surface under tension, ACM TOMS 23, 1997. (ssrfpack.f)
Data Types
type ssrfpackinterfacemodule::ssrfpackinterface
Consolidated interface for interpolation of one data field, scalar or vector, from a set of LPM particles on a sphere.
interface ssrfpackinterfacemodule::new
interface ssrfpackinterfacemodule::delete
Functions/Subroutines
final ssrfpackinterfacemodule::delaunaytriangulation::deletedeltri
final ssrfpackinterfacemodule::ssrfpackinterface::deleteprivate
subroutine ssrfpackinterfacemodule::new::newprivate (self, aMesh, nDim)
Allocates memory for an SsrfpackInterface object.
subroutine ssrfpackinterfacemodule::new::newdeltri (self, aMesh)
Allocates memory for STRIPACK's Delaunay triangulation data structure, constructs Delaunay triangulation.
subroutine ssrfpackinterfacemodule::delete::deleteprivate (self)
Deletes and frees memory associated with an SSRFPACKInterface object.
subroutine ssrfpackinterfacemodule::delete::deletedeltri (self)
Deletes and frees memory associated with a Delaunay triangulation.
subroutine ssrfpackinterfacemodule::newprivate (self, aMesh, nDim)
Allocates memory for an SsrfpackInterface object.
subroutine ssrfpackinterfacemodule::newdeltri (self, aMesh)
Allocates memory for STRIPACK's Delaunay triangulation data structure, constructs Delaunay triangulation.
subroutine ssrfpackinterfacemodule::deletedeltri (self)
Deletes and frees memory associated with a Delaunay triangulation.
subroutine ssrfpackinterfacemodule::deleteprivate (self)
Deletes and frees memory associated with an SSRFPACKInterface object.
subroutine, public ssrfpackinterfacemodule::setvectorsourcedata (self, aMesh, delTri, vectorField)
Sets up an SSRFPACKInterface object for interpolation.
subroutine, public ssrfpackinterfacemodule::setscalarsourcedata (self, aMesh, delTri, scalarField)
Sets up an SSRFPACKInterface object for interpolation.
subroutine, public ssrfpackinterfacemodule::setsourcelagrangianparameter (self, aMesh, delTri)
Sets up an SSRFPACKInterface object for interpolation of the Lagrangian parameter.
real(kreal) function, public ssrfpackinterfacemodule::interpolatescalar (lon, lat, self, aMesh, delTri, scalarField)
Performs interpolation of a scalar field at a single point.
subroutine, public ssrfpackinterfacemodule::interpolatescalartouniflatlongrid (self, aMesh, delTri, scalarField, lons, lats, interpOut)
Performs parallel interpolation of a scalar field from an LPM particle set to a uniform latitude-longitude grid.
real(kreal) function,
dimension(3), public ssrfpackinterfacemodule::interpolatevector (lon, lat, self, aMesh, delTri, vectorField)
Performs interpolation of a vector field at a single point.
subroutine, public ssrfpackinterfacemodule::interpolatevectortouniflatlongrid (self, aMesh, delTri, vectorField, lons, lats, interpX, interpY, interpZ)
Performs parallel interpolation of a vector field from an LPM particle set to a uniform latitude-longitude grid.
real(kreal) function,
dimension(3), public ssrfpackinterfacemodule::interpolatelagparam (lon, lat, self, aMesh, delTri)
Interpolates the Lagrangian parameter from a set of LPM particles to a desired location on the sphere.
subroutine, public ssrfpackinterfacemodule::setsigmaflag (newVal)
subroutine ssrfpackinterfacemodule::builddelaunaytriangulation (self, aMesh)
Builds a Delaunay triangulation of a set of LPM Particles on the surface of the unit sphere using stripack.f.
subroutine ssrfpackinterfacemodule::initlogger (aLog, rank)
Initializes a logger for the SSRFPACKInterface module.
Variables
integer(kint), dimension(:),
allocatable ssrfpackinterfacemodule::delaunaytriangulation::list
Stripack data structure, see stripack.f for more details.
integer(kint), dimension(:),
allocatable ssrfpackinterfacemodule::delaunaytriangulation::lptr
Stripack data structure, see stripack.f for more details.
integer(kint), dimension(:),
allocatable ssrfpackinterfacemodule::delaunaytriangulation::lend
Stripack data structure, see stripack.f for more details.
real(kreal), dimension(:,:),
allocatable ssrfpackinterfacemodule::ssrfpackinterface::grad1
Storage for estimated gradient vectors.
real(kreal), dimension(:,:),
allocatable ssrfpackinterfacemodule::ssrfpackinterface::grad2
Storage for estimated gradient vectors.
real(kreal), dimension(:,:),
allocatable ssrfpackinterfacemodule::ssrfpackinterface::grad3
Storage for estimated gradient vectors.
real(kreal), dimension(:),
allocatable ssrfpackinterfacemodule::ssrfpackinterface::sigma1
Storage for smoothing factors.
real(kreal), dimension(:),
allocatable ssrfpackinterfacemodule::ssrfpackinterface::sigma2
Storage for smoothing factors.
real(kreal), dimension(:),
allocatable ssrfpackinterfacemodule::ssrfpackinterface::sigma3
Storage for smoothing factors.
integer(kint), save ssrfpackinterfacemodule::sigma_flag = 0
Determines type of tension factors to use, see ssrfpack.f for more details.
integer(kint), parameter ssrfpackinterfacemodule::grad_flag = 1
Indicates that gradient estimation is performed explicitly by the LPM routines.
integer(kint), save ssrfpackinterfacemodule::starttriangle = 1
real(kreal), save ssrfpackinterfacemodule::sigmatol = 0.01_kreal
logical(klog), save ssrfpackinterfacemodule::loginit = .FALSE.
type(logger) ssrfpackinterfacemodule::log
character(len=28), save ssrfpackinterfacemodule::logkey = 'SSRFPACK'
integer(kint), parameter ssrfpackinterfacemodule::loglevel = DEBUG_LOGGING_LEVEL
character(len=max_string_length) ssrfpackinterfacemodule::logstring
Function/Subroutine Documentation
subroutine ssrfpackinterfacemodule::builddelaunaytriangulation (type(delaunaytriangulation), intent(inout) self, type(polymesh2d), intent(in) aMesh) private
Builds a Delaunay triangulation of a set of LPM Particles on the surface of the unit sphere using stripack.f.
Parameters
[in,out] self STRIPACK data structures for Delaunay triangulation
[in] aMesh spherical PolyMesh2d
Definition at line 492 of file ssrfpackInterface.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, and trmesh().
subroutine ssrfpackinterfacemodule::deletedeltri (type(delaunaytriangulation), intent(inout) self) private
Deletes and frees memory associated with a Delaunay triangulation.
Parameters
[in,out] self Target Del. tri.
Definition at line 162 of file ssrfpackInterface.f90.
final ssrfpackinterfacemodule::delaunaytriangulation::deletedeltri () final private
Definition at line 55 of file ssrfpackInterface.f90.
subroutine ssrfpackinterfacemodule::delete::deletedeltri (type(delaunaytriangulation), intent(inout) self) private
Deletes and frees memory associated with a Delaunay triangulation.
Parameters
[in,out] self Target Del. tri.
Definition at line 162 of file ssrfpackInterface.f90.
subroutine ssrfpackinterfacemodule::deleteprivate (type(ssrfpackinterface), intent(inout) self) private
Deletes and frees memory associated with an SSRFPACKInterface object.
Parameters
[in,out] self Target SSRFPACKInterface
Definition at line 173 of file ssrfpackInterface.f90.
final ssrfpackinterfacemodule::ssrfpackinterface::deleteprivate () final private
Definition at line 69 of file ssrfpackInterface.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine ssrfpackinterfacemodule::delete::deleteprivate (type(ssrfpackinterface), intent(inout) self) private
Deletes and frees memory associated with an SSRFPACKInterface object.
Parameters
[in,out] self Target SSRFPACKInterface
Definition at line 173 of file ssrfpackInterface.f90.
subroutine ssrfpackinterfacemodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the SSRFPACKInterface module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 528 of file ssrfpackInterface.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
real(kreal) function, dimension(3), public ssrfpackinterfacemodule::interpolatelagparam (real(kreal), intent(in) lon, real(kreal), intent(in) lat, type(ssrfpackinterface), intent(in) self, type(polymesh2d), intent(in) aMesh, type(delaunaytriangulation), intent(in) delTri)
Interpolates the Lagrangian parameter from a set of LPM particles to a desired location on the sphere.
Parameters
[in] lon longitude of interpolation output
[in] lat latitude of interpolation output
[in,out] self SSRFPACKInterface ready for interpolation (a SetSourceLagrangianParameter subroutine has already been called)
[in] aMesh source PolyMesh2d
[in] delTri Delaunay triangulation
Definition at line 457 of file ssrfpackInterface.f90.
References ssrfpackinterfacemodule::grad_flag, intrc1(), ssrfpackinterfacemodule::sigma_flag, and ssrfpackinterfacemodule::starttriangle.
real(kreal) function, public ssrfpackinterfacemodule::interpolatescalar (real(kreal), intent(in) lon, real(kreal), intent(in) lat, type(ssrfpackinterface), intent(in) self, type(polymesh2d), intent(in) aMesh, type(delaunaytriangulation), intent(in) delTri, type(field), intent(in) scalarField)
Performs interpolation of a scalar field at a single point.
Locates (lat, lon) in Delaunay triangulation
Computes interpolated value using cubic Hermite polynomial on triangle containing (lat,lon)
Parameters
[in] lon Longitude of interpolation output
[in] lat Latitude of interpolation output
[in] self SSRFPACKInterface ready for interpolation (a SetSource* subroutine has already been called)
[in] aMesh PolyMesh2d spherical mesh
[in] delTri Delaunay triangulation
[in] scalarField source data
Returns
interpolated scalar value
Definition at line 300 of file ssrfpackInterface.f90.
References ssrfpackinterfacemodule::grad_flag, intrc1(), ssrfpackinterfacemodule::sigma_flag, and ssrfpackinterfacemodule::starttriangle.
subroutine, public ssrfpackinterfacemodule::interpolatescalartouniflatlongrid (type(ssrfpackinterface), intent(inout) self, type(polymesh2d), intent(in) aMesh, type(delaunaytriangulation), intent(in) delTri, type(field), intent(in) scalarField, real(kreal), dimension(:), intent(in) lons, real(kreal), dimension(:), intent(in) lats, real(kreal), dimension(:,:), intent(out) interpOut)
Performs parallel interpolation of a scalar field from an LPM particle set to a uniform latitude-longitude grid.
Distributes work of interpolation across MPI processes by assigning each process a subset of the output points (divided by longitude). Then broadcasts each processes work to the other processes.
Parameters
[in,out] self SSRFPACKInterface
[in] aMesh PolyMesh2d source mesh
[in] delTri Delaunay triangulation
[in] scalarField source data
[in] lons vector of longitudes associated with uniform lat-lon output grid
[in] lats vector of latitudes associated with uniform lat-lon output grid
[out] interpOut interpolated scalar output
Definition at line 327 of file ssrfpackInterface.f90.
References ssrfpackinterfacemodule::grad_flag, intrc1(), numberkindsmodule::numprocs, numberkindsmodule::procrank, ssrfpackinterfacemodule::sigma_flag, and ssrfpackinterfacemodule::starttriangle.
real(kreal) function, dimension(3), public ssrfpackinterfacemodule::interpolatevector (real(kreal), intent(in) lon, real(kreal), intent(in) lat, type(ssrfpackinterface), intent(in) self, type(polymesh2d), intent(in) aMesh, type(delaunaytriangulation), intent(in) delTri, type(field), intent(in) vectorField)
Performs interpolation of a vector field at a single point.
Locates (lat, lon) in Delaunay triangulation
Computes interpolated value using cubic Hermite polynomial on triangle containing (lat,lon)
Parameters
[in] lon Longitude of interpolation output
[in] lat Latitude of interpolation output
[in] self SSRFPACKInterface ready for interpolation (a SetSource* subroutine has already been called)
[in] aMesh PolyMesh2d spherical mesh
[in] delTri Delaunay triangulation
[in] vectorField source data
Returns
interpolated vector value
Definition at line 371 of file ssrfpackInterface.f90.
References ssrfpackinterfacemodule::grad_flag, intrc1(), ssrfpackinterfacemodule::sigma_flag, and ssrfpackinterfacemodule::starttriangle.
subroutine, public ssrfpackinterfacemodule::interpolatevectortouniflatlongrid (type(ssrfpackinterface), intent(inout) self, type(polymesh2d), intent(in) aMesh, type(delaunaytriangulation), intent(in) delTri, type(field), intent(in) vectorField, real(kreal), dimension(:), intent(in) lons, real(kreal), dimension(:), intent(in) lats, real(kreal), dimension(:,:), intent(out) interpX, real(kreal), dimension(:,:), intent(out) interpY, real(kreal), dimension(:,:), intent(out) interpZ)
Performs parallel interpolation of a vector field from an LPM particle set to a uniform latitude-longitude grid.
Distributes work of interpolation across MPI processes by assigning each process a subset of the output points (divided by longitude). Then broadcasts each processes work to the other processes.
Parameters
[in,out] self SSRFPACKInterface ready for interpolation (a SetSource* subroutine has already been called)
[in] aMesh PolyMesh2d source mesh
[in] delTri Delaunay triangulation
[in] vectorField source data
[in] lons vector of longitudes associated with uniform lat-lon output grid
[in] lats vector of latitudes associated with uniform lat-lon output grid
[out] interpX interpolated x component of vector field
[out] interpY interpolated y component of vector field
[out] interpZ interpolated z component of vector field
Definition at line 406 of file ssrfpackInterface.f90.
References ssrfpackinterfacemodule::grad_flag, intrc1(), numberkindsmodule::numprocs, numberkindsmodule::procrank, ssrfpackinterfacemodule::sigma_flag, and ssrfpackinterfacemodule::starttriangle.
subroutine ssrfpackinterfacemodule::newdeltri (type(delaunaytriangulation), intent(out) self, type(polymesh2d), intent(inout) aMesh) private
Allocates memory for STRIPACK's Delaunay triangulation data structure, constructs Delaunay triangulation.
Parameters
[out] self Target Delaunay triangulation of all particles (both centers and vertices)
[in] aMesh PolyMesh2d spherical mesh
Definition at line 145 of file ssrfpackInterface.f90.
References ssrfpackinterfacemodule::builddelaunaytriangulation(), initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, numberkindsmodule::procrank, and polymesh2dmodule::projectparticlestosphere().
subroutine ssrfpackinterfacemodule::new::newdeltri (type(delaunaytriangulation), intent(out) self, type(polymesh2d), intent(inout) aMesh) private
Allocates memory for STRIPACK's Delaunay triangulation data structure, constructs Delaunay triangulation.
Parameters
[out] self Target Delaunay triangulation of all particles (both centers and vertices)
[in] aMesh PolyMesh2d spherical mesh
Definition at line 145 of file ssrfpackInterface.f90.
subroutine ssrfpackinterfacemodule::newprivate (type(ssrfpackinterface), intent(out) self, type(polymesh2d), intent(inout) aMesh, integer(kint), intent(in) nDim) private
Allocates memory for an SsrfpackInterface object.
Parameters
[out] self Target SSRFPACKInterface
[in,out] aMesh PolyMesh2d spherical mesh
[in] nDim Dimension of data to be interpolated
Definition at line 116 of file ssrfpackInterface.f90.
References initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and numberkindsmodule::procrank.
subroutine ssrfpackinterfacemodule::new::newprivate (type(ssrfpackinterface), intent(out) self, type(polymesh2d), intent(inout) aMesh, integer(kint), intent(in) nDim) private
Allocates memory for an SsrfpackInterface object.
Parameters
[out] self Target SSRFPACKInterface
[in,out] aMesh PolyMesh2d spherical mesh
[in] nDim Dimension of data to be interpolated
Definition at line 116 of file ssrfpackInterface.f90.
subroutine, public ssrfpackinterfacemodule::setscalarsourcedata (type(ssrfpackinterface), intent(inout) self, type(polymesh2d), intent(in) aMesh, type(delaunaytriangulation), intent(in) delTri, type(field), intent(in) scalarField)
Sets up an SSRFPACKInterface object for interpolation.
Estimates scalar gradients of a scalar field, or scalar gradients of each component of a vector field
Computes optimal smoothing factors, see ssrfpack.f for more detail
Parameters
[in,out] self target SSRFPACKInterface, on output, target is ready to interpolate data
[in] aMesh PolyMesh2d
[in] delTri Delaunay triangulation
[in] scalarField scalar Field associated with aMesh
Definition at line 232 of file ssrfpackInterface.f90.
References getsig(), gradl(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, ssrfpackinterfacemodule::sigma_flag, and ssrfpackinterfacemodule::sigmatol.
subroutine, public ssrfpackinterfacemodule::setsigmaflag (integer(kint), intent(in) newVal)
Definition at line 477 of file ssrfpackInterface.f90.
References ssrfpackinterfacemodule::sigma_flag.
subroutine, public ssrfpackinterfacemodule::setsourcelagrangianparameter (type(ssrfpackinterface), intent(inout) self, type(polymesh2d), intent(in) aMesh, type(delaunaytriangulation), intent(in) delTri)
Sets up an SSRFPACKInterface object for interpolation of the Lagrangian parameter.
Estimates scalar gradients of each component of the Lagrangian coordinate vector at each particle
Computes optimal smoothing factors, see ssrfpack.f for more detail
Parameters
[in,out] self target SSRFPACKInterface, on output, target is ready to interpolate data
[in] aMesh PolyMesh2d
[in] delTri Delaunay triangulation
Definition at line 262 of file ssrfpackInterface.f90.
References getsig(), gradl(), ssrfpackinterfacemodule::sigma_flag, and ssrfpackinterfacemodule::sigmatol.
subroutine, public ssrfpackinterfacemodule::setvectorsourcedata (type(ssrfpackinterface), intent(inout) self, type(polymesh2d), intent(in) aMesh, type(delaunaytriangulation), intent(in) delTri, type(field), intent(in) vectorField)
Sets up an SSRFPACKInterface object for interpolation.
Estimates scalar gradients of a scalar field, or scalar gradients of each component of a vector field
Computes optimal smoothing factors, see ssrfpack.f for more detail
Parameters
[in,out] self target SSRFPACKInterface, on output, target is ready to interpolate data
[in] aMesh PolyMesh2d
[in] delTri Delaunay triangulation
[in] vectorField vector Field associated with aMesh
Definition at line 196 of file ssrfpackInterface.f90.
References getsig(), gradl(), ssrfpackinterfacemodule::sigma_flag, and ssrfpackinterfacemodule::sigmatol.
Variable Documentation
real(kreal), dimension(:,:), allocatable ssrfpackinterfacemodule::ssrfpackinterface::grad1 private
Storage for estimated gradient vectors.
Definition at line 60 of file ssrfpackInterface.f90.
real(kreal), dimension(:,:), allocatable ssrfpackinterfacemodule::ssrfpackinterface::grad2 private
Storage for estimated gradient vectors.
Definition at line 61 of file ssrfpackInterface.f90.
real(kreal), dimension(:,:), allocatable ssrfpackinterfacemodule::ssrfpackinterface::grad3 private
Storage for estimated gradient vectors.
Definition at line 62 of file ssrfpackInterface.f90.
integer(kint), parameter ssrfpackinterfacemodule::grad_flag = 1 private
Indicates that gradient estimation is performed explicitly by the LPM routines.
Definition at line 73 of file ssrfpackInterface.f90.
integer(kint), dimension(:), allocatable ssrfpackinterfacemodule::delaunaytriangulation::lend private
Stripack data structure, see stripack.f for more details.
Definition at line 51 of file ssrfpackInterface.f90.
integer(kint), dimension(:), allocatable ssrfpackinterfacemodule::delaunaytriangulation::list private
Stripack data structure, see stripack.f for more details.
Definition at line 49 of file ssrfpackInterface.f90.
type(logger) ssrfpackinterfacemodule::log private
Definition at line 99 of file ssrfpackInterface.f90.
logical(klog), save ssrfpackinterfacemodule::loginit = .FALSE. private
Definition at line 98 of file ssrfpackInterface.f90.
character(len=28), save ssrfpackinterfacemodule::logkey = 'SSRFPACK' private
Definition at line 100 of file ssrfpackInterface.f90.
integer(kint), parameter ssrfpackinterfacemodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 101 of file ssrfpackInterface.f90.
character(len=max_string_length) ssrfpackinterfacemodule::logstring private
Definition at line 102 of file ssrfpackInterface.f90.
integer(kint), dimension(:), allocatable ssrfpackinterfacemodule::delaunaytriangulation::lptr private
Stripack data structure, see stripack.f for more details.
Definition at line 50 of file ssrfpackInterface.f90.
real(kreal), dimension(:), allocatable ssrfpackinterfacemodule::ssrfpackinterface::sigma1 private
Storage for smoothing factors.
Definition at line 63 of file ssrfpackInterface.f90.
real(kreal), dimension(:), allocatable ssrfpackinterfacemodule::ssrfpackinterface::sigma2 private
Storage for smoothing factors.
Definition at line 64 of file ssrfpackInterface.f90.
real(kreal), dimension(:), allocatable ssrfpackinterfacemodule::ssrfpackinterface::sigma3 private
Storage for smoothing factors.
Definition at line 65 of file ssrfpackInterface.f90.
integer(kint), save ssrfpackinterfacemodule::sigma_flag = 0 private
Determines type of tension factors to use, see ssrfpack.f for more details.
Definition at line 72 of file ssrfpackInterface.f90.
real(kreal), save ssrfpackinterfacemodule::sigmatol = 0.01_kreal private
Definition at line 75 of file ssrfpackInterface.f90.
integer(kint), save ssrfpackinterfacemodule::starttriangle = 1 private
Definition at line 74 of file ssrfpackInterface.f90.