LPM: Lagrangian Particle Methods: STDIntVector
STDIntVector
Mimics the dynamically allocated C++ std::vector<int> object. Provides array-style access to its elements, and resizes if necessary.
Detailed Description
Mimics the dynamically allocated C++ std::vector<int> object. Provides array-style access to its elements, and resizes if necessary.
Data Types
interface stdintvectormodule::initialize
Functions/Subroutines
procedure stdintvectormodule::stdintvector::defaultinit
procedure stdintvectormodule::stdintvector::initfromarray
procedure stdintvectormodule::stdintvector::initfromcopy
final stdintvectormodule::stdintvector::finalizevector
procedure, public stdintvectormodule::stdintvector::empty
procedure, public stdintvectormodule::stdintvector::int
procedure, public stdintvectormodule::stdintvector::pushback
procedure, public stdintvectormodule::stdintvector::pushbackunique
procedure, public stdintvectormodule::stdintvector::insert
procedure, public stdintvectormodule::stdintvector::replace
procedure, public stdintvectormodule::stdintvector::print
subroutine stdintvectormodule::initialize::defaultinit (self, minSize)
subroutine stdintvectormodule::initialize::initfromarray (self, intArray)
subroutine stdintvectormodule::initialize::initfromcopy (self, other)
subroutine stdintvectormodule::defaultinit (self, minSize)
subroutine stdintvectormodule::initfromarray (self, intArray)
subroutine stdintvectormodule::initfromcopy (self, other)
subroutine stdintvectormodule::assignvectorfromcopy (self, other)
subroutine stdintvectormodule::finalizevector (vec)
Deletes and frees memory associated with a STDIntVector object.
logical(klog) function stdintvectormodule::empty (self)
Returns .TRUE. if a STDIntVector has no content.
integer(kint) function stdintvectormodule::int (self, index)
Returns the integer in the STDIntVector at the desired position.
subroutine stdintvectormodule::pushback (self, int)
Adds a new integer to the end of a vector, resizes if necessary.
subroutine stdintvectormodule::pushbackunique (self, int)
Adds a new integer to the end of a vector, but only if that integer is not already listed somewhere in the vector.
subroutine stdintvectormodule::insert (self, pos, val)
Adds a new integer to a STDIntVector at a desired position; increases the size of the vector.
subroutine stdintvectormodule::replace (self, pos, val)
Replaces the value of an integer at a particular position in the array with a new value. Does not change the size of the STDIntVector.
subroutine stdintvectormodule::doublearrayspace (self)
Doubles the memory assigned to a STDIntVector.
subroutine stdintvectormodule::print (self, name)
Variables
integer(kint), dimension(:),
pointer stdintvectormodule::stdintvector::integers => null()
integer(kint) stdintvectormodule::stdintvector::n = 0
integer(kint), parameter stdintvectormodule::default_vec_size = 20
default size of array
Function/Subroutine Documentation
subroutine stdintvectormodule::assignvectorfromcopy (type(stdintvector), intent(out) self, type(stdintvector), intent(in) other) private
Todo:
Implement assignment operator
Parameters
self Target to be overwritten with content of other
other Source STDIntvector
Definition at line 96 of file STDIntVector.f90.
References stdintvectormodule::stdintvector::initfromcopy().
subroutine stdintvectormodule::defaultinit (class(stdintvector), intent(out) self, integer(kint), intent(in), optional minSize) private
Parameters
self Target to be initialized
minSize minimum size of vector
Definition at line 50 of file STDIntVector.f90.
procedure stdintvectormodule::stdintvector::defaultinit () private
Definition at line 23 of file STDIntVector.f90.
subroutine stdintvectormodule::initialize::defaultinit (class(stdintvector), intent(out) self, integer(kint), intent(in), optional minSize) private
Parameters
self Target to be initialized
minSize minimum size of vector
Definition at line 50 of file STDIntVector.f90.
subroutine stdintvectormodule::doublearrayspace (class(stdintvector), intent(inout) self) private
Doubles the memory assigned to a STDIntVector.
Parameters
self Target STDIntVector
Definition at line 217 of file STDIntVector.f90.
logical(klog) function stdintvectormodule::empty (class(stdintvector), intent(in) self) private
Returns .TRUE. if a STDIntVector has no content.
Parameters
self Target STDIntVector
Returns
.TRUE. if self is empty
Definition at line 112 of file STDIntVector.f90.
procedure, public stdintvectormodule::stdintvector::empty ()
Definition at line 27 of file STDIntVector.f90.
subroutine stdintvectormodule::finalizevector (type(stdintvector), intent(inout) vec) private
Deletes and frees memory associated with a STDIntVector object.
Parameters
vec Target STDIntVector
Definition at line 104 of file STDIntVector.f90.
final stdintvectormodule::stdintvector::finalizevector () final private
Definition at line 26 of file STDIntVector.f90.
subroutine stdintvectormodule::initfromarray (class(stdintvector) self, integer(kint), dimension(:), intent(in) intArray) private
Parameters
self Target to be initialized
intArray integer array with source data
Definition at line 65 of file STDIntVector.f90.
procedure stdintvectormodule::stdintvector::initfromarray () private
Definition at line 24 of file STDIntVector.f90.
subroutine stdintvectormodule::initialize::initfromarray (class(stdintvector) self, integer(kint), dimension(:), intent(in) intArray) private
Parameters
self Target to be initialized
intArray integer array with source data
Definition at line 65 of file STDIntVector.f90.
subroutine stdintvectormodule::initfromcopy (class(stdintvector), intent(out) self, class(stdintvector), intent(in) other) private
Parameters
self Target to be initialized
other STDIntVector with source data
Definition at line 83 of file STDIntVector.f90.
procedure stdintvectormodule::stdintvector::initfromcopy () private
Definition at line 25 of file STDIntVector.f90.
subroutine stdintvectormodule::initialize::initfromcopy (class(stdintvector), intent(out) self, class(stdintvector), intent(in) other) private
Parameters
self Target to be initialized
other STDIntVector with source data
Definition at line 83 of file STDIntVector.f90.
subroutine stdintvectormodule::insert (class(stdintvector), intent(inout) self, integer(kint), intent(in) pos, integer(kint), intent(in) val) private
Adds a new integer to a STDIntVector at a desired position; increases the size of the vector.
Parameters
self Target STDIntVector
pos Position of new integer in array
val Integer to add at new position
Definition at line 168 of file STDIntVector.f90.
References stdintvectormodule::doublearrayspace(), stdintvectormodule::stdintvector::print(), and stdintvectormodule::stdintvector::pushback().
procedure, public stdintvectormodule::stdintvector::insert ()
Definition at line 31 of file STDIntVector.f90.
References insert().
integer(kint) function stdintvectormodule::int (class(stdintvector), intent(in) self, integer(kint), intent(in) index) private
Returns the integer in the STDIntVector at the desired position.
Parameters
self Source STDIntVector
index Location of desired integer in STDIntVector's array
Returns
The integer in the array at the index location
Definition at line 122 of file STDIntVector.f90.
References stdintvectormodule::stdintvector::print().
procedure, public stdintvectormodule::stdintvector::int ()
Definition at line 28 of file STDIntVector.f90.
subroutine stdintvectormodule::print (class(stdintvector), intent(in) self, character(len=*), intent(in), optional name) private
Parameters
self Target STDIntVector
name Name of vector
Definition at line 237 of file STDIntVector.f90.
References fieldmodule::field::name.
procedure, public stdintvectormodule::stdintvector::print ()
Definition at line 33 of file STDIntVector.f90.
subroutine stdintvectormodule::pushback (class(stdintvector), intent(inout) self, integer(kint), intent(in) int) private
Adds a new integer to the end of a vector, resizes if necessary.
Parameters
self STDIntVector to increase in size
int Integer to add to self
Definition at line 137 of file STDIntVector.f90.
References stdintvectormodule::doublearrayspace(), and stdintvectormodule::stdintvector::int().
procedure, public stdintvectormodule::stdintvector::pushback ()
Definition at line 29 of file STDIntVector.f90.
subroutine stdintvectormodule::pushbackunique (class(stdintvector), intent(inout) self, integer(kint), intent(in) int) private
Adds a new integer to the end of a vector, but only if that integer is not already listed somewhere in the vector.
Parameters
self Target STDIntVector
int Integer to add (if it is unique)
Definition at line 150 of file STDIntVector.f90.
References stdintvectormodule::stdintvector::int(), and stdintvectormodule::stdintvector::pushback().
procedure, public stdintvectormodule::stdintvector::pushbackunique ()
Definition at line 30 of file STDIntVector.f90.
subroutine stdintvectormodule::replace (class(stdintvector), intent(inout) self, integer(kint), intent(in) pos, integer(kint), intent(in) val) private
Replaces the value of an integer at a particular position in the array with a new value. Does not change the size of the STDIntVector.
Parameters
self Target STDIntVector
pos Position of integer to replace
val New integer to put into array
Definition at line 203 of file STDIntVector.f90.
References stdintvectormodule::stdintvector::print().
procedure, public stdintvectormodule::stdintvector::replace ()
Definition at line 32 of file STDIntVector.f90.
Variable Documentation
integer(kint), parameter stdintvectormodule::default_vec_size = 20 private
default size of array
Interface to initialize a STDIntVector
Definition at line 36 of file STDIntVector.f90.
integer(kint), dimension(:), pointer stdintvectormodule::stdintvector::integers => null() private
Definition at line 19 of file STDIntVector.f90.
integer(kint) stdintvectormodule::stdintvector::n = 0 private
Definition at line 20 of file STDIntVector.f90.