LPM: Lagrangian Particle Methods: BetaPlane
BetaPlane
Data structure for a planar incompressible flow with a background rotation.
Detailed Description
Data structure for a planar incompressible flow with a background rotation.
Data Types
interface betaplanemeshmodule::new
interface betaplanemeshmodule::delete
interface betaplanemeshmodule::copy
interface betaplanemeshmodule::logstats
interface betaplanemeshmodule::setvelocityonmesh
interface betaplanemeshmodule::resetperiodicbounds
Functions/Subroutines
final betaplanemeshmodule::betaplanemesh::deleteprivate
subroutine betaplanemeshmodule::new::newprivate (self, initNest, maxNest, amrLimit, baseLat, rotRate)
subroutine betaplanemeshmodule::delete::deleteprivate (self)
subroutine betaplanemeshmodule::copy::copyprivate (self, other)
subroutine betaplanemeshmodule::logstats::logstatsprivate (self, aLog)
subroutine betaplanemeshmodule::setvelocityonmesh::setvelocityfromfunction (self, velFn)
subroutine betaplanemeshmodule::setvelocityonmesh::setvelocityfromvorticity (self)
subroutine betaplanemeshmodule::resetperiodicbounds::resetperiodicboundsmesh (self)
subroutine betaplanemeshmodule::resetperiodicbounds::resetperiodicboundsarray (x)
subroutine betaplanemeshmodule::newprivate (self, initNest, maxNest, amrLimit, baseLat, rotRate)
subroutine betaplanemeshmodule::deleteprivate (self)
subroutine betaplanemeshmodule::copyprivate (self, other)
subroutine, public betaplanemeshmodule::addtracers (self, nTracers, tracerDims)
subroutine betaplanemeshmodule::logstatsprivate (self, aLog)
subroutine, public betaplanemeshmodule::outputtovtk (self, filename)
subroutine, public betaplanemeshmodule::setinitialvorticityonmesh (self, relVortFn)
subroutine betaplanemeshmodule::setvelocityfromfunction (self, velFn)
subroutine betaplanemeshmodule::setscalartraceronmesh (self, tracerID, tracerFn)
subroutine betaplanemeshmodule::setvectortraceronmesh (self, tracerID, tracerFn)
real(kreal) function, public betaplanemeshmodule::totalke (self)
real(kreal) function, public betaplanemeshmodule::totalenstrophy (self)
real(kreal) function, public betaplanemeshmodule::maxcirculationmagnitudeperface (self)
subroutine betaplanemeshmodule::setvelocityfromvorticity (self)
subroutine, public betaplanemeshmodule::setstreamfunctionsonmesh (self)
subroutine betaplanemeshmodule::resetperiodicboundsarray (x)
subroutine betaplanemeshmodule::resetperiodicboundsmesh (self)
subroutine betaplanemeshmodule::initlogger (aLog, rank)
Variables
type(polymesh2d) betaplanemeshmodule::betaplanemesh::mesh
type(field) betaplanemeshmodule::betaplanemesh::absvort
type(field) betaplanemeshmodule::betaplanemesh::relvort
type(field) betaplanemeshmodule::betaplanemesh::relstream
type(field) betaplanemeshmodule::betaplanemesh::absstream
type(field) betaplanemeshmodule::betaplanemesh::velocity
type(field), dimension(:),
allocatable betaplanemeshmodule::betaplanemesh::tracers
real(kreal) betaplanemeshmodule::betaplanemesh::f0 = 0.0_kreal
real(kreal) betaplanemeshmodule::betaplanemesh::beta = 0.0_kreal
type(mpisetup) betaplanemeshmodule::betaplanemesh::mpiparticles
logical(klog) betaplanemeshmodule::betaplanemesh::useamr = .FALSE.
logical(klog), save betaplanemeshmodule::loginit = .FALSE.
type(logger) betaplanemeshmodule::log
character(len=28), save betaplanemeshmodule::logkey = 'BetaPlane'
integer(kint), parameter betaplanemeshmodule::loglevel = DEBUG_LOGGING_LEVEL
character(len=max_string_length) betaplanemeshmodule::logstring
Function/Subroutine Documentation
subroutine, public betaplanemeshmodule::addtracers (type(betaplanemesh), intent(inout) self, integer(kint), intent(in) nTracers, integer(kint), dimension(:), intent(in) tracerDims)
Definition at line 178 of file BetaPlane.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine betaplanemeshmodule::copyprivate (type(betaplanemesh), intent(inout) self, type(betaplanemesh), intent(in) other) private
Definition at line 163 of file BetaPlane.f90.
subroutine betaplanemeshmodule::copy::copyprivate (type(betaplanemesh), intent(inout) self, type(betaplanemesh), intent(in) other) private
Definition at line 163 of file BetaPlane.f90.
subroutine betaplanemeshmodule::deleteprivate (type(betaplanemesh), intent(inout) self) private
Definition at line 142 of file BetaPlane.f90.
final betaplanemeshmodule::betaplanemesh::deleteprivate () final private
Definition at line 55 of file BetaPlane.f90.
subroutine betaplanemeshmodule::delete::deleteprivate (type(betaplanemesh), intent(inout) self) private
Definition at line 142 of file BetaPlane.f90.
subroutine betaplanemeshmodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Definition at line 478 of file BetaPlane.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine betaplanemeshmodule::logstatsprivate (type(betaplanemesh), intent(in) self, type(logger), intent(inout) aLog) private
Definition at line 197 of file BetaPlane.f90.
References loggermodule::trace_logging_level.
subroutine betaplanemeshmodule::logstats::logstatsprivate (type(betaplanemesh), intent(in) self, type(logger), intent(inout) aLog) private
Definition at line 197 of file BetaPlane.f90.
real(kreal) function, public betaplanemeshmodule::maxcirculationmagnitudeperface (type(betaplanemesh), intent(in) self)
Definition at line 340 of file BetaPlane.f90.
subroutine betaplanemeshmodule::newprivate (type(betaplanemesh), intent(out) self, integer(kint), intent(in) initNest, integer(kint), intent(in) maxNest, integer(kint), intent(in) amrLimit, real(kreal), intent(in) baseLat, real(kreal), intent(in), optional rotRate) private
Definition at line 106 of file BetaPlane.f90.
References loggermodule::error_logging_level, initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, numberkindsmodule::numprocs, numberkindsmodule::pi, and numberkindsmodule::procrank.
subroutine betaplanemeshmodule::new::newprivate (type(betaplanemesh), intent(out) self, integer(kint), intent(in) initNest, integer(kint), intent(in) maxNest, integer(kint), intent(in) amrLimit, real(kreal), intent(in) baseLat, real(kreal), intent(in), optional rotRate) private
Definition at line 106 of file BetaPlane.f90.
subroutine, public betaplanemeshmodule::outputtovtk (type(betaplanemesh), intent(in) self, character(len=*), intent(in) filename)
Definition at line 209 of file BetaPlane.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, numberkindsmodule::write_unit_1, facesmodule::writefaceareatovtkcelldata(), facesmodule::writefacestovtkpolygons(), fieldmodule::writefieldtovtkpointdata(), particlesmodule::writevtklagcoords(), outputwritermodule::writevtkpointdatasectionheader(), and particlesmodule::writevtkpoints().
subroutine betaplanemeshmodule::resetperiodicboundsarray (real(kreal), dimension(:), intent(inout) x) private
Definition at line 443 of file BetaPlane.f90.
subroutine betaplanemeshmodule::resetperiodicbounds::resetperiodicboundsarray (real(kreal), dimension(:), intent(inout) x) private
Definition at line 443 of file BetaPlane.f90.
subroutine betaplanemeshmodule::resetperiodicboundsmesh (type(betaplanemesh), intent(inout) self) private
Definition at line 458 of file BetaPlane.f90.
subroutine betaplanemeshmodule::resetperiodicbounds::resetperiodicboundsmesh (type(betaplanemesh), intent(inout) self) private
Definition at line 458 of file BetaPlane.f90.
subroutine, public betaplanemeshmodule::setinitialvorticityonmesh (type(betaplanemesh), intent(inout) self, procedure(scalarfnof2dspace) relVortFn)
Definition at line 246 of file BetaPlane.f90.
subroutine betaplanemeshmodule::setscalartraceronmesh (type(betaplanemesh), intent(inout) self, integer(kint), intent(in) tracerID, procedure(scalarfnof2dspace) tracerFn) private
Definition at line 277 of file BetaPlane.f90.
References fieldmodule::setfieldtozero().
subroutine, public betaplanemeshmodule::setstreamfunctionsonmesh (type(betaplanemesh), intent(inout) self)
Definition at line 398 of file BetaPlane.f90.
References numberkindsmodule::numprocs, particlesmodule::physcoord(), numberkindsmodule::pi, and numberkindsmodule::procrank.
subroutine betaplanemeshmodule::setvectortraceronmesh (type(betaplanemesh), intent(inout) self, integer(kint), intent(in) tracerID, procedure(vectorfnof2dspace) tracerFn) private
Definition at line 291 of file BetaPlane.f90.
References fieldmodule::setfieldtozero().
subroutine betaplanemeshmodule::setvelocityfromfunction (type(betaplanemesh), intent(inout) self, procedure(vectorfnof2dspace) velFn) private
Definition at line 262 of file BetaPlane.f90.
subroutine betaplanemeshmodule::setvelocityonmesh::setvelocityfromfunction (type(betaplanemesh), intent(inout) self, procedure(vectorfnof2dspace) velFn) private
Definition at line 262 of file BetaPlane.f90.
subroutine betaplanemeshmodule::setvelocityfromvorticity (type(betaplanemesh), intent(inout) self) private
Definition at line 358 of file BetaPlane.f90.
References numberkindsmodule::numprocs, particlesmodule::physcoord(), numberkindsmodule::pi, and numberkindsmodule::procrank.
subroutine betaplanemeshmodule::setvelocityonmesh::setvelocityfromvorticity (type(betaplanemesh), intent(inout) self) private
Definition at line 358 of file BetaPlane.f90.
real(kreal) function, public betaplanemeshmodule::totalenstrophy (type(betaplanemesh), intent(in) self)
Definition at line 325 of file BetaPlane.f90.
real(kreal) function, public betaplanemeshmodule::totalke (type(betaplanemesh), intent(in) self)
Definition at line 308 of file BetaPlane.f90.
Variable Documentation
type(field) betaplanemeshmodule::betaplanemesh::absstream private
Definition at line 46 of file BetaPlane.f90.
type(field) betaplanemeshmodule::betaplanemesh::absvort private
Definition at line 43 of file BetaPlane.f90.
real(kreal) betaplanemeshmodule::betaplanemesh::beta = 0.0_kreal private
Definition at line 50 of file BetaPlane.f90.
real(kreal) betaplanemeshmodule::betaplanemesh::f0 = 0.0_kreal private
Definition at line 49 of file BetaPlane.f90.
type(logger) betaplanemeshmodule::log private
Definition at line 95 of file BetaPlane.f90.
logical(klog), save betaplanemeshmodule::loginit = .FALSE. private
Definition at line 94 of file BetaPlane.f90.
character(len=28), save betaplanemeshmodule::logkey = 'BetaPlane' private
Definition at line 96 of file BetaPlane.f90.
integer(kint), parameter betaplanemeshmodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 97 of file BetaPlane.f90.
character(len=max_string_length) betaplanemeshmodule::logstring private
Definition at line 98 of file BetaPlane.f90.
type(polymesh2d) betaplanemeshmodule::betaplanemesh::mesh private
Definition at line 42 of file BetaPlane.f90.
type(mpisetup) betaplanemeshmodule::betaplanemesh::mpiparticles private
Definition at line 51 of file BetaPlane.f90.
type(field) betaplanemeshmodule::betaplanemesh::relstream private
Definition at line 45 of file BetaPlane.f90.
type(field) betaplanemeshmodule::betaplanemesh::relvort private
Definition at line 44 of file BetaPlane.f90.
type(field), dimension(:), allocatable betaplanemeshmodule::betaplanemesh::tracers private
Definition at line 48 of file BetaPlane.f90.
logical(klog) betaplanemeshmodule::betaplanemesh::useamr = .FALSE. private
Definition at line 52 of file BetaPlane.f90.
type(field) betaplanemeshmodule::betaplanemesh::velocity private
Definition at line 47 of file BetaPlane.f90.