LPM: Lagrangian Particle Methods: MPISetup
MPISetup
A class for handling parallelization via MPI for distributed memory architectures.
Detailed Description
A class for handling parallelization via MPI for distributed memory architectures.
The current implementation uses the 'replicated data algorithm' and simply divides the number of items by the number of processors and distributes indices accordingly. Every process knows the indices assigned to every other process, and the message size associated with every other process.
Note: In accordance with OpenMPI convention, these indices are assigned using a base-0 system, rather than the base-1 system typical of Fortran.
Data Types
interface mpisetupmodule::new
interface mpisetupmodule::copy
interface mpisetupmodule::delete
Functions/Subroutines
final mpisetupmodule::mpisetup::deleteprivate
subroutine mpisetupmodule::new::newprivate (self, nItems, nProcs)
Allocates memory and initializes a new MPISetup object.
subroutine mpisetupmodule::copy::copyprivate (self, other)
Copies an MPISetup object.
subroutine mpisetupmodule::delete::deleteprivate (self)
Deletes and frees memory associated with an MPISetup object.
subroutine mpisetupmodule::newprivate (self, nItems, nProcs)
Allocates memory and initializes a new MPISetup object.
subroutine mpisetupmodule::deleteprivate (self)
Deletes and frees memory associated with an MPISetup object.
subroutine mpisetupmodule::copyprivate (self, other)
Copies an MPISetup object.
subroutine, public mpisetupmodule::loadbalance (self, nItems, nProcs)
Distributes nItems across nProcs.
Variables
integer(kint), dimension(:),
allocatable mpisetupmodule::mpisetup::indexstart
integer(kint), dimension(:),
allocatable mpisetupmodule::mpisetup::indexend
integer(kint), dimension(:),
allocatable mpisetupmodule::mpisetup::messagelength
integer(kint) mpisetupmodule::mpisetup::n = 0
Function/Subroutine Documentation
subroutine mpisetupmodule::copyprivate (type(mpisetup), intent(inout) self, type(mpisetup), intent(in) other) private
Copies an MPISetup object.
Parameters
self Target MPISetup object
other Source MPISetup object
Definition at line 99 of file MPISetup.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate(), betaplanemeshmodule::new::newprivate(), and numberkindsmodule::numprocs.
subroutine mpisetupmodule::copy::copyprivate (type(mpisetup), intent(inout) self, type(mpisetup), intent(in) other) private
Copies an MPISetup object.
Parameters
self Target MPISetup object
other Source MPISetup object
Definition at line 99 of file MPISetup.f90.
subroutine mpisetupmodule::deleteprivate (type(mpisetup), intent(inout) self) private
Deletes and frees memory associated with an MPISetup object.
Parameters
self Target MPISetup object
Definition at line 87 of file MPISetup.f90.
subroutine mpisetupmodule::delete::deleteprivate (type(mpisetup), intent(inout) self) private
Deletes and frees memory associated with an MPISetup object.
Parameters
self Target MPISetup object
Definition at line 87 of file MPISetup.f90.
final mpisetupmodule::mpisetup::deleteprivate () final private
Definition at line 41 of file MPISetup.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine, public mpisetupmodule::loadbalance (type(mpisetup), intent(inout) self, integer(kint), intent(in) nItems, integer(kint), intent(in) nProcs)
Distributes nItems across nProcs.
Parameters
self Target MPISetup object
nItems The number of items to distribute across processes
nProcs The number of processes
Definition at line 110 of file MPISetup.f90.
subroutine mpisetupmodule::newprivate (type(mpisetup), intent(out) self, integer(kint), intent(in) nItems, integer(kint), intent(in) nProcs) private
Allocates memory and initializes a new MPISetup object.
Parameters
self Target MPISetup object
nItems The number of items to distribute across processes
nProcs The number of processes
Definition at line 73 of file MPISetup.f90.
References mpisetupmodule::loadbalance().
subroutine mpisetupmodule::new::newprivate (type(mpisetup), intent(out) self, integer(kint), intent(in) nItems, integer(kint), intent(in) nProcs) private
Allocates memory and initializes a new MPISetup object.
Parameters
self Target MPISetup object
nItems The number of items to distribute across processes
nProcs The number of processes
Definition at line 73 of file MPISetup.f90.
Variable Documentation
integer(kint), dimension(:), allocatable mpisetupmodule::mpisetup::indexend private
Definition at line 37 of file MPISetup.f90.
integer(kint), dimension(:), allocatable mpisetupmodule::mpisetup::indexstart private
Definition at line 36 of file MPISetup.f90.
integer(kint), dimension(:), allocatable mpisetupmodule::mpisetup::messagelength private
Definition at line 38 of file MPISetup.f90.
integer(kint) mpisetupmodule::mpisetup::n = 0 private
Definition at line 39 of file MPISetup.f90.