LPM: Lagrangian Particle Methods: Particles
Particles
Provides a vectorized data structure that defines the particles for LPM spatial discretization.
Detailed Description
Provides a vectorized data structure that defines the particles for LPM spatial discretization.
Particles are combined with the Field data structure to define scalar and vector fields over a spatial domain. Particles may be combined with a mesh object (e.g., PolyMesh2d) or an unstructured data object (e.g., a quadtree) to facilitate interpolation, differentiation, quadrature, etc.
The particles data structures is a "structure of arrays," so that all information about a particle i is located at index i in the relevant arrays. For example, the x-coordinate in physical space of particle i is aParticles%x(i). Its Lagrangian coordinates are given by aParticles%x0(i), aParticles%y0(i), etc.
Particles that contribute to a midpoint quadrature rule are called "active," and this status is recorded in the isActive array. Active particles have nonzero area (2d) or volume (3d). Particles that do not contribute to the midpoint rule (i.e., vertex particles) are considered "passive." Passive particles have zero area or volume.
Each particle has physical coordinates \((x(t),y(t),z(t)) \) and Lagrangian coordinates \((x_0, y_0, z_0) \); area (for 2d models) or volume (for 3d models).
Particle sets used with a mesh are initialized in the PolyMesh2d module.
Data Types
interface particlesmodule::new
Allocates memory and initializes to null/zero a Particles object.
interface particlesmodule::delete
Deletes a Particles object and frees its memory.
interface particlesmodule::copy
Copies (deep copy) one Particles object to another.
interface particlesmodule::logstats
Outputs statistics about a Particles object to the console via a loggermodule::logger object.
interface particlesmodule::printdebuginfo
Prints detailed information about a Particles object to the console.
Functions/Subroutines
subroutine particlesmodule::new::newprivate (self, nMax, geomKind)
Allocates memory for a new particles object. All values are zeroed and must be initialized separately.
subroutine particlesmodule::delete::deleteprivate (self)
Deletes and frees memory associated with a particles object.
subroutine particlesmodule::copy::copyprivate (self, other)
Performs a deep copy of one particles object into another.
subroutine particlesmodule::logstats::logstatsprivate (self, aLog)
Writes particles information to console using a loggermodule::logger object for formatting.
subroutine particlesmodule::printdebuginfo::printdebugprivate (self)
Prints a large amount of information to the console. Used for debugging.
subroutine particlesmodule::newprivate (self, nMax, geomKind)
Allocates memory for a new particles object. All values are zeroed and must be initialized separately.
subroutine particlesmodule::deleteprivate (self)
Deletes and frees memory associated with a particles object.
subroutine particlesmodule::copyprivate (self, other)
Performs a deep copy of one particles object into another.
subroutine particlesmodule::printdebugprivate (self)
Prints a large amount of information to the console. Used for debugging.
subroutine, public particlesmodule::writevtkpoints (self, fileunit, title)
Writes VTK point data to a .vtk file in vtk legacy version 2.0 PolyData format. Used for plotting with VTK C++ programs or ParaView.
subroutine, public particlesmodule::writevtklagcoords (self, fileunit)
Writes a particle set's Lagrangian coordinates to VTK PolyData Output.
subroutine, public particlesmodule::writevtkparticlearea (self, fileunit)
Writes particle area to VTK PolyData Output.
subroutine, public particlesmodule::writevtkparticlevolume (self, fileunit)
Writes particle volume to VTK PolyData Output.
subroutine, public particlesmodule::insertparticle (self, physX, lagX)
Inserts a single particle into a particles object.
subroutine, public particlesmodule::makeparticleactive (self, index)
Changes a passive particle to an active particle. Area/volume must be set separately.
subroutine, public particlesmodule::makeparticlepassive (self, index)
Changes an active particle to a passive particle. Area/volume may be set to zero separately.
subroutine, public particlesmodule::resetlagrangianparameter (self)
subroutine particlesmodule::logstatsprivate (self, aLog)
Writes particles information to console using a loggermodule::logger object for formatting.
subroutine, public particlesmodule::sortincidentedgesatparticle (self, index)
Sorts the incident edges at a particle into counter-clockwise order using a bubble-sort algorithm.
pure subroutine particlesmodule::orderedgepair (index1, angle1, index2, angle2)
pure real(kreal) function,
dimension(3), public particlesmodule::physcoord (self, index)
Returns a particle's physical coordinate vector.
pure real(kreal) function,
dimension(3), public particlesmodule::lagcoord (self, index)
Returns a particle's Lagrangian coordinate vector.
pure real(kreal) function, public particlesmodule::totalarea (self)
Returns the total area represented by all active ParticlesModule.
pure real(kreal) function, public particlesmodule::totalvolume (self)
Returns the total volume represented by all active ParticlesModule.
subroutine, public particlesmodule::writeparticlestomatlab (self, fileunit)
Writes particles to a script .m file readable by Matlab.
subroutine particlesmodule::initlogger (aLog, rank)
Initializes a logger for the Particles module.
Variables
real(kreal), dimension(:),
allocatable particlesmodule::particles::x
physical coordinate
real(kreal), dimension(:),
allocatable particlesmodule::particles::y
physical coordinate
real(kreal), dimension(:),
allocatable particlesmodule::particles::z
physical coordinate
real(kreal), dimension(:),
allocatable particlesmodule::particles::x0
Lagrangian coordinate.
real(kreal), dimension(:),
allocatable particlesmodule::particles::y0
Lagrangian coordinate.
real(kreal), dimension(:),
allocatable particlesmodule::particles::z0
Lagrangian coordinate.
real(kreal), dimension(:),
allocatable particlesmodule::particles::area
area represented by each particle
real(kreal), dimension(:),
allocatable particlesmodule::particles::volume
volume represented by each particle
integer(kint), dimension(:),
allocatable particlesmodule::particles::nedges
number of edges (if a mesh is used) incident to each particle
integer(kint), dimension(:,:),
allocatable particlesmodule::particles::incidentedges
indices to Edges incident on each particle (only if a mesh is used)
real(kreal), dimension(:,:),
allocatable particlesmodule::particles::incidentangles
angles of indcidence for edges at each particle (only if a mesh is used)
logical(klog), dimension(:),
allocatable particlesmodule::particles::isactive
logical(klog), dimension(:),
allocatable particlesmodule::particles::ispassive
integer(kint) particlesmodule::particles::n = 0
integer(kint) particlesmodule::particles::n_max = 0
integer(kint) particlesmodule::particles::geomkind = 0
logical(klog), save particlesmodule::loginit = .FALSE.
type(logger) particlesmodule::log
character(len=28), save particlesmodule::logkey = 'ParticlesLog'
integer(kint), parameter particlesmodule::loglevel = DEBUG_LOGGING_LEVEL
character(len=max_string_length) particlesmodule::logstring
Function/Subroutine Documentation
subroutine particlesmodule::copyprivate (type(particles), intent(inout) self, type(particles), intent(in) other) private
Performs a deep copy of one particles object into another.
Parameters
self Target Particles object
other Source Particles object
Definition at line 215 of file Particles.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine particlesmodule::copy::copyprivate (type(particles), intent(inout) self, type(particles), intent(in) other) private
Performs a deep copy of one particles object into another.
Parameters
self Target Particles object
other Source Particles object
Definition at line 215 of file Particles.f90.
subroutine particlesmodule::deleteprivate (type(particles), intent(inout) self) private
Deletes and frees memory associated with a particles object.
Parameters
self Target Particles object
Definition at line 192 of file Particles.f90.
subroutine particlesmodule::delete::deleteprivate (type(particles), intent(inout) self) private
Deletes and frees memory associated with a particles object.
Parameters
self Target Particles object
Definition at line 192 of file Particles.f90.
subroutine particlesmodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the Particles module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 723 of file Particles.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine, public particlesmodule::insertparticle (type(particles), intent(inout) self, real(kreal), dimension(:), intent(in) physX, real(kreal), dimension(:), intent(in) lagX)
Inserts a single particle into a particles object.
Parameters
[in,out] self a set of particles
[in] physX physical coordinate vector of particle to add
[in] lagX Lagrangian coordinate vector of particle to add
Definition at line 453 of file Particles.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, and numberkindsmodule::planar_geom.
pure real(kreal) function, dimension(3), public particlesmodule::lagcoord (type(particles), intent(in) self, integer(kint), intent(in) index)
Returns a particle's Lagrangian coordinate vector.
Parameters
self
index
Returns
LagCoord coordinate vector
Definition at line 618 of file Particles.f90.
subroutine particlesmodule::logstatsprivate (type(particles), intent(in) self, type(logger), intent(inout) aLog) private
Writes particles information to console using a loggermodule::logger object for formatting.
Parameters
self
aLog
Definition at line 517 of file Particles.f90.
References betaplanemeshmodule::logkey, planarincompressiblesolvermodule::planesolver::mask, and loggermodule::trace_logging_level.
subroutine particlesmodule::logstats::logstatsprivate (type(particles), intent(in) self, type(logger), intent(inout) aLog) private
Writes particles information to console using a loggermodule::logger object for formatting.
Parameters
self
aLog
Definition at line 517 of file Particles.f90.
subroutine, public particlesmodule::makeparticleactive (type(particles), intent(inout) self, integer(kint), intent(in) index)
Changes a passive particle to an active particle. Area/volume must be set separately.
Parameters
self
index index of particle to be changed.
Definition at line 479 of file Particles.f90.
References betaplanemeshmodule::log, betaplanemeshmodule::logkey, and loggermodule::warning_logging_level.
subroutine, public particlesmodule::makeparticlepassive (type(particles), intent(inout) self, integer(kint), intent(in) index)
Changes an active particle to a passive particle. Area/volume may be set to zero separately.
Parameters
self
index index of particle to be changed.
Definition at line 494 of file Particles.f90.
References betaplanemeshmodule::log, betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, and loggermodule::warning_logging_level.
subroutine particlesmodule::newprivate (type(particles), intent(out) self, integer(kint), intent(in) nMax, integer(kint), intent(in) geomKind) private
Allocates memory for a new particles object. All values are zeroed and must be initialized separately.
Parameters
self Target Particles object
nMax Number of maximum particles required
geomKind Geometry kind (e.g., spherical or planar) as defined in NumberKinds
Definition at line 134 of file Particles.f90.
References loggermodule::error_logging_level, numberkindsmodule::euclidean_3d, initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, numberkindsmodule::max_vertex_degree, numberkindsmodule::planar_geom, numberkindsmodule::procrank, and numberkindsmodule::sphere_geom.
subroutine particlesmodule::new::newprivate (type(particles), intent(out) self, integer(kint), intent(in) nMax, integer(kint), intent(in) geomKind) private
Allocates memory for a new particles object. All values are zeroed and must be initialized separately.
Parameters
self Target Particles object
nMax Number of maximum particles required
geomKind Geometry kind (e.g., spherical or planar) as defined in NumberKinds
Definition at line 134 of file Particles.f90.
pure subroutine particlesmodule::orderedgepair (integer(kint), intent(inout) index1, real(kreal), intent(inout) angle1, integer(kint), intent(inout) index2, real(kreal), intent(inout) angle2) private
Definition at line 582 of file Particles.f90.
pure real(kreal) function, dimension(3), public particlesmodule::physcoord (type(particles), intent(in) self, integer(kint), intent(in) index)
Returns a particle's physical coordinate vector.
Parameters
self
index
Returns
PhysCoord coordinate vector
Definition at line 604 of file Particles.f90.
subroutine particlesmodule::printdebugprivate (type(particles), intent(in) self) private
Prints a large amount of information to the console. Used for debugging.
Parameters
self Target Particles object
Definition at line 294 of file Particles.f90.
References stdintvectormodule::stdintvector::print().
subroutine particlesmodule::printdebuginfo::printdebugprivate (type(particles), intent(in) self) private
Prints a large amount of information to the console. Used for debugging.
Parameters
self Target Particles object
Definition at line 294 of file Particles.f90.
subroutine, public particlesmodule::resetlagrangianparameter (type(particles), intent(inout) self)
Definition at line 506 of file Particles.f90.
References numberkindsmodule::planar_geom.
subroutine, public particlesmodule::sortincidentedgesatparticle (type(particles), intent(inout) self, integer(kint), intent(in) index)
Sorts the incident edges at a particle into counter-clockwise order using a bubble-sort algorithm.
Parameters
self
index of particle whose edges need sorting.
Definition at line 544 of file Particles.f90.
References betaplanemeshmodule::log, betaplanemeshmodule::logstring, particlesmodule::orderedgepair(), and loggermodule::warning_logging_level.
pure real(kreal) function, public particlesmodule::totalarea (type(particles), intent(in) self)
Returns the total area represented by all active ParticlesModule.
Parameters
self
Returns
TotalArea
Definition at line 631 of file Particles.f90.
References planarincompressiblesolvermodule::planesolver::mask.
pure real(kreal) function, public particlesmodule::totalvolume (type(particles), intent(in) self)
Returns the total volume represented by all active ParticlesModule.
Parameters
self
Returns
Totalvolume
Definition at line 640 of file Particles.f90.
References planarincompressiblesolvermodule::planesolver::mask.
subroutine, public particlesmodule::writeparticlestomatlab (type(particles), intent(in) self, integer(kint), intent(in) fileunit)
Writes particles to a script .m file readable by Matlab.
Parameters
self
fileunit
Definition at line 650 of file Particles.f90.
References numberkindsmodule::planar_geom.
subroutine, public particlesmodule::writevtklagcoords (class(particles), intent(in) self, integer(kint), intent(in) fileunit)
Writes a particle set's Lagrangian coordinates to VTK PolyData Output.
Parameters
self
fileunit
Definition at line 394 of file Particles.f90.
References numberkindsmodule::planar_geom.
subroutine, public particlesmodule::writevtkparticlearea (class(particles), intent(in) self, integer(kint), intent(in) fileunit)
Writes particle area to VTK PolyData Output.
Parameters
self
fileunit
Definition at line 416 of file Particles.f90.
References betaplanemeshmodule::log, and loggermodule::warning_logging_level.
subroutine, public particlesmodule::writevtkparticlevolume (class(particles), intent(in) self, integer(kint), intent(in) fileunit)
Writes particle volume to VTK PolyData Output.
Parameters
self
fileunit
Definition at line 434 of file Particles.f90.
References betaplanemeshmodule::log, and loggermodule::warning_logging_level.
subroutine, public particlesmodule::writevtkpoints (class(particles), intent(in) self, integer(kint), intent(in) fileunit, character(len=*), intent(in), optional title)
Writes VTK point data to a .vtk file in vtk legacy version 2.0 PolyData format. Used for plotting with VTK C++ programs or ParaView.
Parameters
self particles to output
fileunit integer fileunit of output file.
title title associated with this particle set.
Definition at line 367 of file Particles.f90.
References numberkindsmodule::planar_geom, and outputwritermodule::writevtkfileheader().
Variable Documentation
real(kreal), dimension(:), allocatable particlesmodule::particles::area private
area represented by each particle
Definition at line 67 of file Particles.f90.
integer(kint) particlesmodule::particles::geomkind = 0 private
Definition at line 76 of file Particles.f90.
real(kreal), dimension(:,:), allocatable particlesmodule::particles::incidentangles private
angles of indcidence for edges at each particle (only if a mesh is used)
Definition at line 71 of file Particles.f90.
integer(kint), dimension(:,:), allocatable particlesmodule::particles::incidentedges private
indices to Edges incident on each particle (only if a mesh is used)
Definition at line 70 of file Particles.f90.
logical(klog), dimension(:), allocatable particlesmodule::particles::isactive private
Definition at line 72 of file Particles.f90.
logical(klog), dimension(:), allocatable particlesmodule::particles::ispassive private
Definition at line 73 of file Particles.f90.
type(logger) particlesmodule::log private
Definition at line 85 of file Particles.f90.
logical(klog), save particlesmodule::loginit = .FALSE. private
Definition at line 84 of file Particles.f90.
character(len=28), save particlesmodule::logkey = 'ParticlesLog' private
Definition at line 86 of file Particles.f90.
integer(kint), parameter particlesmodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 87 of file Particles.f90.
character(len=max_string_length) particlesmodule::logstring private
Definition at line 88 of file Particles.f90.
integer(kint) particlesmodule::particles::n = 0 private
Definition at line 74 of file Particles.f90.
integer(kint) particlesmodule::particles::n_max = 0 private
Definition at line 75 of file Particles.f90.
integer(kint), dimension(:), allocatable particlesmodule::particles::nedges private
number of edges (if a mesh is used) incident to each particle
Definition at line 69 of file Particles.f90.
real(kreal), dimension(:), allocatable particlesmodule::particles::volume private
volume represented by each particle
Definition at line 68 of file Particles.f90.
real(kreal), dimension(:), allocatable particlesmodule::particles::x private
physical coordinate
Definition at line 61 of file Particles.f90.
real(kreal), dimension(:), allocatable particlesmodule::particles::x0 private
Lagrangian coordinate.
Definition at line 64 of file Particles.f90.
real(kreal), dimension(:), allocatable particlesmodule::particles::y private
physical coordinate
Definition at line 62 of file Particles.f90.
real(kreal), dimension(:), allocatable particlesmodule::particles::y0 private
Lagrangian coordinate.
Definition at line 65 of file Particles.f90.
real(kreal), dimension(:), allocatable particlesmodule::particles::z private
physical coordinate
Definition at line 63 of file Particles.f90.
real(kreal), dimension(:), allocatable particlesmodule::particles::z0 private
Lagrangian coordinate.
Definition at line 66 of file Particles.f90.