LPM: Lagrangian Particle Methods: SWEPlaneSolver
SWEPlaneSolver
Data structure for solving the Shallow Water Equations (SWE) in the beta plane. Used with the PlanarSWE module.
Detailed Description
Data structure for solving the Shallow Water Equations (SWE) in the beta plane. Used with the PlanarSWE module.
The shallow water equations are presented in the detailed description of the PlanarSWE module.
Integrals are used to compute the velocity \(\vec{u}\), the double dot product \(\nabla\vec{u}:\nabla\vec{u} \), and a PSE integral (see PSEDirectSum) approximates the Laplacian of the fluid surface.
As with the other integrals in LPM, these integrals are computed as a parallel direct summation across all MPI ranks.
See sweplanesolvermodule::sweplanerhsintegrals.
All other terms are computed as ODEs along each particle trajectory; see sweplanesolvermodule::timestepprivate.
Data Types
interface sweplanesolvermodule::new
interface sweplanesolvermodule::delete
interface sweplanesolvermodule::timestep
Functions/Subroutines
final sweplanesolvermodule::swesolver::deleteprivate
subroutine sweplanesolvermodule::new::newprivate (self, plane, topoFn)
Allocates memory for a new SWE Solver. Initializes the solver to match the current mesh.
subroutine sweplanesolvermodule::delete::deleteprivate (self)
Deletes and frees memory associated with an SWESolver.
subroutine sweplanesolvermodule::timestep::timestepprivate (self, plane, dt, topoFn)
Advances a SWE mesh forward in time by one timestep using 4th order Runge-Kutta.
subroutine sweplanesolvermodule::newprivate (self, plane, topoFn)
Allocates memory for a new SWE Solver. Initializes the solver to match the current mesh.
subroutine sweplanesolvermodule::deleteprivate (self)
Deletes and frees memory associated with an SWESolver.
subroutine sweplanesolvermodule::timestepprivate (self, plane, dt, topoFn)
Advances a SWE mesh forward in time by one timestep using 4th order Runge-Kutta.
subroutine sweplanesolvermodule::sweplanerhsintegrals (u, v, doubleDot, lapSurf, x, y, vort, div, h, topoFn, area, mask, pseEps, mpiParticles)
Computes the integral expressions on the right-hand side of the set of ODEs from a Lagrangian method of lines discretization; see PlanarSWE.
subroutine sweplanesolvermodule::initlogger (aLog, rank)
Initializes a logger for the planar SWE solver module.
Variables
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::xstart
starting x-coordinate of each particle
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::ystart
starting y-coordinate of each particle
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::relvortstart
starting relative vorticity of each particle
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::areastart
starting area of each particle
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::divstart
starting divergence of each particle
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::hstart
starting depth at each particle
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::u
x-component of fluid velocity
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::v
y-component of fluid velocity
logical(klog), dimension(:),
allocatable sweplanesolvermodule::swesolver::mask
mask(i) is .TRUE. if particle i is active
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::potvort
potential vorticity of each particle
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::doubledot
double dot product of velocity at each particle
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::lapsurf
Laplacian of fluid surface at each particle.
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::xin
x-coordinate input to RK4
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::xstage1
x-coordinates of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::xstage2
x-coordinates of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::xstage3
x-coordinates of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::xstage4
x-coordinates of each particle at RK4 stage 4
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::yin
y-coordinate input to RK4
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::ystage1
y-coordinates of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::ystage2
y-coordinates of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::ystage3
y-coordinates of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::ystage4
y-coordinates of each particle at RK4 stage 4
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::areain
area input to RK4
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::areastage1
area of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::areastage2
area of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::areastage3
area of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::areastage4
area of each particle at RK4 stage 4
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::relvortin
relative vorticity input to RK4
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::relvortstage1
relative vorticity of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::relvortstage2
relative vorticity of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::relvortstage3
relative vorticity of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::relvortstage4
relative vorticity of each particle at RK4 stage 4
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::divin
divergence input to RK4
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::divstage1
divergence of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::divstage2
divergence of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::divstage3
divergence of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::divstage4
divergence of each particle at RK4 stage 4
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::hin
depth input to RK4
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::hstage1
depth of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::hstage2
depth of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::hstage3
depth of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable sweplanesolvermodule::swesolver::hstage4
depth of each particle at RK4 stage 4
logical(klog), save sweplanesolvermodule::loginit = .FALSE.
type(logger) sweplanesolvermodule::log
character(len=28), save sweplanesolvermodule::logkey = 'SWESolver'
integer(kint), parameter sweplanesolvermodule::loglevel = DEBUG_LOGGING_LEVEL
character(len=max_string_length) sweplanesolvermodule::logstring
Function/Subroutine Documentation
subroutine sweplanesolvermodule::deleteprivate (type(swesolver), intent(inout) self) private
Deletes and frees memory associated with an SWESolver.
Parameters
[in,out] self Solver
Definition at line 203 of file SWEPlaneSolver.f90.
final sweplanesolvermodule::swesolver::deleteprivate () final private
Definition at line 89 of file SWEPlaneSolver.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine sweplanesolvermodule::delete::deleteprivate (type(swesolver), intent(inout) self) private
Deletes and frees memory associated with an SWESolver.
Parameters
[in,out] self Solver
Definition at line 203 of file SWEPlaneSolver.f90.
subroutine sweplanesolvermodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the planar SWE solver module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 529 of file SWEPlaneSolver.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine sweplanesolvermodule::newprivate (type(swesolver), intent(out) self, type(swemesh), intent(in) plane, procedure(scalarfnof2dspace) topoFn) private
Allocates memory for a new SWE Solver. Initializes the solver to match the current mesh.
Parameters
[out] self Target SWE Solver
[in] plane PlanarSWE mesh
[in] topoFn bottom topography function, must conform to the numberkindsmodule::scalarFnOf2DSpace interface
Definition at line 131 of file SWEPlaneSolver.f90.
References initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, numberkindsmodule::procrank, and sweplanesolvermodule::sweplanerhsintegrals().
subroutine sweplanesolvermodule::new::newprivate (type(swesolver), intent(out) self, type(swemesh), intent(in) plane, procedure(scalarfnof2dspace) topoFn) private
Allocates memory for a new SWE Solver. Initializes the solver to match the current mesh.
Parameters
[out] self Target SWE Solver
[in] plane PlanarSWE mesh
[in] topoFn bottom topography function, must conform to the numberkindsmodule::scalarFnOf2DSpace interface
Definition at line 131 of file SWEPlaneSolver.f90.
subroutine sweplanesolvermodule::sweplanerhsintegrals (real(kreal), dimension(:), intent(out) u, real(kreal), dimension(:), intent(out) v, real(kreal), dimension(:), intent(out) doubleDot, real(kreal), dimension(:), intent(out) lapSurf, real(kreal), dimension(:), intent(in) x, real(kreal), dimension(:), intent(in) y, real(kreal), dimension(:), intent(in) vort, real(kreal), dimension(:), intent(in) div, real(kreal), dimension(:), intent(in) h, procedure(scalarfnof2dspace) topoFn, real(kreal), dimension(:), intent(in) area, logical(klog), dimension(:), intent(in) mask, real(kreal), intent(in) pseEps, type(mpisetup), intent(in) mpiParticles) private
Computes the integral expressions on the right-hand side of the set of ODEs from a Lagrangian method of lines discretization; see PlanarSWE.
Integrals are used to compute the double dot product \(\nabla\vec{u}:\nabla\vec{u} \) and a PSE integral (see PSEDirectSum) approximates the Laplacian of the fluid surface.
As with the other integrals in LPM, these integrals are computed as a parallel direct summation across all MPI ranks.
Parameters
[out] u x-component of velocity
[out] v y-component of velocity
[out] doubleDot double dot product
[out] lapSurf Laplacian of fluid surface
[in] x x-coordinates of particles
[in] y y-coordinates of particles
[in] vort vorticity carried by particles
[in] div divergence carried by particles
[in] h fluid depth at particles
[in] topoFn bottom topography height function, must conform to numberkindsmodule::scalarFnOf2DSpace interface
[in] area area represented by each particle
[in] mask mask(i) is true if particle i is active
[in] pseEps PSE particle influence radius
[in] mpiParticles MPISetup to distribute work of particle integration across all MPI ranks
Definition at line 416 of file SWEPlaneSolver.f90.
References psedirectsummodule::bivariatelaplaciankernel8(), numberkindsmodule::numprocs, numberkindsmodule::pi, and numberkindsmodule::procrank.
subroutine sweplanesolvermodule::timestepprivate (type(swesolver), intent(inout) self, type(swemesh), intent(inout) plane, real(kreal), intent(in) dt, procedure(scalarfnof2dspace) topoFn) private
Advances a SWE mesh forward in time by one timestep using 4th order Runge-Kutta.
Parameters
[in,out] self SWE solver
[in,out] plane PlanarSWE mesh
[in] dt timestep increment
[in] topoFn bottom topography function, must conform to the numberkindsmodule::scalarFnOf2DSpace interface
Definition at line 257 of file SWEPlaneSolver.f90.
References planarswemodule::setbottomheightonmesh(), and sweplanesolvermodule::sweplanerhsintegrals().
subroutine sweplanesolvermodule::timestep::timestepprivate (type(swesolver), intent(inout) self, type(swemesh), intent(inout) plane, real(kreal), intent(in) dt, procedure(scalarfnof2dspace) topoFn) private
Advances a SWE mesh forward in time by one timestep using 4th order Runge-Kutta.
Parameters
[in,out] self SWE solver
[in,out] plane PlanarSWE mesh
[in] dt timestep increment
[in] topoFn bottom topography function, must conform to the numberkindsmodule::scalarFnOf2DSpace interface
Definition at line 257 of file SWEPlaneSolver.f90.
Variable Documentation
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::areain private
area input to RK4
Definition at line 67 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::areastage1 private
area of each particle at RK4 stage 1
Definition at line 68 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::areastage2 private
area of each particle at RK4 stage 2
Definition at line 69 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::areastage3 private
area of each particle at RK4 stage 3
Definition at line 70 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::areastage4 private
area of each particle at RK4 stage 4
Definition at line 71 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::areastart private
starting area of each particle
Definition at line 47 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::divin private
divergence input to RK4
Definition at line 77 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::divstage1 private
divergence of each particle at RK4 stage 1
Definition at line 78 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::divstage2 private
divergence of each particle at RK4 stage 2
Definition at line 79 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::divstage3 private
divergence of each particle at RK4 stage 3
Definition at line 80 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::divstage4 private
divergence of each particle at RK4 stage 4
Definition at line 81 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::divstart private
starting divergence of each particle
Definition at line 48 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::doubledot private
double dot product of velocity at each particle
Definition at line 54 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::hin private
depth input to RK4
Definition at line 82 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::hstage1 private
depth of each particle at RK4 stage 1
Definition at line 83 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::hstage2 private
depth of each particle at RK4 stage 2
Definition at line 84 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::hstage3 private
depth of each particle at RK4 stage 3
Definition at line 85 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::hstage4 private
depth of each particle at RK4 stage 4
Definition at line 86 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::hstart private
starting depth at each particle
Definition at line 49 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::lapsurf private
Laplacian of fluid surface at each particle.
Definition at line 55 of file SWEPlaneSolver.f90.
type(logger) sweplanesolvermodule::log private
Definition at line 115 of file SWEPlaneSolver.f90.
logical(klog), save sweplanesolvermodule::loginit = .FALSE. private
Definition at line 114 of file SWEPlaneSolver.f90.
character(len=28), save sweplanesolvermodule::logkey = 'SWESolver' private
Definition at line 116 of file SWEPlaneSolver.f90.
integer(kint), parameter sweplanesolvermodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 117 of file SWEPlaneSolver.f90.
character(len=max_string_length) sweplanesolvermodule::logstring private
Definition at line 118 of file SWEPlaneSolver.f90.
logical(klog), dimension(:), allocatable sweplanesolvermodule::swesolver::mask private
mask(i) is .TRUE. if particle i is active
Definition at line 52 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::potvort private
potential vorticity of each particle
Definition at line 53 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::relvortin private
relative vorticity input to RK4
Definition at line 72 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::relvortstage1 private
relative vorticity of each particle at RK4 stage 1
Definition at line 73 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::relvortstage2 private
relative vorticity of each particle at RK4 stage 2
Definition at line 74 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::relvortstage3 private
relative vorticity of each particle at RK4 stage 3
Definition at line 75 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::relvortstage4 private
relative vorticity of each particle at RK4 stage 4
Definition at line 76 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::relvortstart private
starting relative vorticity of each particle
Definition at line 46 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::u private
x-component of fluid velocity
Definition at line 50 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::v private
y-component of fluid velocity
Definition at line 51 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::xin private
x-coordinate input to RK4
Definition at line 57 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::xstage1 private
x-coordinates of each particle at RK4 stage 1
Definition at line 58 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::xstage2 private
x-coordinates of each particle at RK4 stage 2
Definition at line 59 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::xstage3 private
x-coordinates of each particle at RK4 stage 3
Definition at line 60 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::xstage4 private
x-coordinates of each particle at RK4 stage 4
Definition at line 61 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::xstart private
starting x-coordinate of each particle
Definition at line 44 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::yin private
y-coordinate input to RK4
Definition at line 62 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::ystage1 private
y-coordinates of each particle at RK4 stage 1
Definition at line 63 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::ystage2 private
y-coordinates of each particle at RK4 stage 2
Definition at line 64 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::ystage3 private
y-coordinates of each particle at RK4 stage 3
Definition at line 65 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::ystage4 private
y-coordinates of each particle at RK4 stage 4
Definition at line 66 of file SWEPlaneSolver.f90.
real(kreal), dimension(:), allocatable sweplanesolvermodule::swesolver::ystart private
starting y-coordinate of each particle
Definition at line 45 of file SWEPlaneSolver.f90.