LPM: Lagrangian Particle Methods: SSRFPACKRemesh
SSRFPACKRemesh
Data structure and methods for remapping spherical LPM data using SSRFPACK.
.
Detailed Description
Data structure and methods for remapping spherical LPM data using SSRFPACK.
.
Uses the interfaces provided by ssrfpackInterface module. For references describing the SSRFPACK package and its counterpart STRIPACK, see the ssrfpackInterface module's detailed description.
Data Types
interface ssrfpackremeshmodule::new
interface ssrfpackremeshmodule::delete
Functions/Subroutines
final ssrfpackremeshmodule::bveremeshsource::deletebve
subroutine ssrfpackremeshmodule::new::newbve (self, oldSphere)
Allocates memory and initializes a remapping utility for a SphereBVE BVE mesh.
subroutine ssrfpackremeshmodule::delete::deletebve (self)
Deletes and frees memory associated with a BVE remeshing object.
subroutine ssrfpackremeshmodule::newbve (self, oldSphere)
Allocates memory and initializes a remapping utility for a SphereBVE BVE mesh.
subroutine ssrfpackremeshmodule::deletebve (self)
Deletes and frees memory associated with a BVE remeshing object.
subroutine, public ssrfpackremeshmodule::directremeshbve (self, oldSphere, newSphere, AMR, vortFlagFn1, tol1, desc1, flagFn2, tol2, desc2, field2)
Performs a remesh/remap of an LPM simulation of the barotropic vorticity equation on the sphere using direct interpolation of each variable.
subroutine, public ssrfpackremeshmodule::lagrangianremeshbvewithvorticityfunction (self, oldSphere, newSphere, AMR, relVortFn, flagFn1, tol1, desc1, flagFn2, tol2, desc2, RefineFlowMapYN, flowMapVarTol, nLagTracers, tracerFn1, tracerFn2)
Performs a remesh/remap of an LPM BVE simulation using indirect interpolation for the variables in a SphereBVE mesh. Remaps to reference time t = 0.
subroutine, public ssrfpackremeshmodule::lagrangianremeshbvetoreferencemesh (newSphere, oldSphere, refSphere, refRemesh, AMR, flagFn1, tol1, desc1, flagFn2, tol2, desc2, RefineFlowMapYN, flowMapVarTol)
Performs a remesh/remap of an LPM SphereBVE simulation using indirect interpolation for all variables in a BVE mesh. Remaps to reference time t = t_{rm}, where t_{rm} is time of definition for a reference mesh (numerical solution). Note that the reference mesh's Lagrangian parameter has been reset, so that x = x0, y = y0, z = z0 at t = t_{rm}.
subroutine ssrfpackremeshmodule::initlogger (aLog, rank)
Initializes a logger for the SsrfpackRemesh module.
Variables
type(delaunaytriangulation) ssrfpackremeshmodule::bveremeshsource::deltri
Delaunay triangulation from STRIPACK.
type(ssrfpackinterface) ssrfpackremeshmodule::bveremeshsource::relvortsource
Source data for relative vorticity interpolation.
type(ssrfpackinterface) ssrfpackremeshmodule::bveremeshsource::absvortsource
Source data for absolute vorticity interpolation.
type(ssrfpackinterface) ssrfpackremeshmodule::bveremeshsource::lagparamsource
Source data for Lagrangian parameter interpolation.
type(ssrfpackinterface),
dimension(:), allocatable ssrfpackremeshmodule::bveremeshsource::tracersource
Source data for passive tracers.
integer(kint), save ssrfpackremeshmodule::remeshcounter = 0
logical(klog), save ssrfpackremeshmodule::loginit = .FALSE.
type(logger) ssrfpackremeshmodule::log
character(len=28), save ssrfpackremeshmodule::logkey = 'SSRFRemesh'
character(len=max_string_length) ssrfpackremeshmodule::logstring
integer(kint), parameter ssrfpackremeshmodule::loglevel = DEBUG_LOGGING_LEVEL
Function/Subroutine Documentation
subroutine ssrfpackremeshmodule::deletebve (type(bveremeshsource), intent(inout) self) private
Deletes and frees memory associated with a BVE remeshing object.
Parameters
[in,out] self Target remeshing object
Definition at line 133 of file SsrfpackRemesh.f90.
final ssrfpackremeshmodule::bveremeshsource::deletebve () final private
Definition at line 50 of file SsrfpackRemesh.f90.
subroutine ssrfpackremeshmodule::delete::deletebve (type(bveremeshsource), intent(inout) self) private
Deletes and frees memory associated with a BVE remeshing object.
Parameters
[in,out] self Target remeshing object
Definition at line 133 of file SsrfpackRemesh.f90.
subroutine, public ssrfpackremeshmodule::directremeshbve (type(bveremeshsource), intent(in) self, type(bvemesh), intent(in) oldSphere, type(bvemesh), intent(inout) newSphere, logical(klog), intent(in) AMR, procedure(flagfunction), optional vortFlagFn1, real(kreal), intent(in), optional tol1, character(len=*), intent(in), optional desc1, procedure(flagfunction), optional flagFn2, real(kreal), intent(in), optional tol2, character(len=*), intent(in), optional desc2, type(field), intent(inout), optional field2)
Performs a remesh/remap of an LPM simulation of the barotropic vorticity equation on the sphere using direct interpolation of each variable.
Parameters
[in] self Remeshing data structure
[in] oldSphere source SphereBVE mesh
[in,out] newSphere target SphereBVE mesh (note that this must have been allocated prior to calling this subroutine)
[in] AMR .TRUE. if adaptive refinement will be used
[in] vortFlagFn1 FlagFunction for vorticity refinement, must have same interface as refinementmodule::FlagFunction
[in] tol1 tolerance for vortFlagFn1
[in] desc1 description of AMR criterion used for vortFlagFn1
[in] flagFn2 Flag function for refinement of field2
[in] tol2 tolerance for flagFn2
[in] desc2 description of AMR criterion used for flagFn2
[in,out] field2 second field to use for adaptive refinement
Definition at line 164 of file SsrfpackRemesh.f90.
References bivarinterfacemodule::interpolatelagparam(), bivarinterfacemodule::interpolatescalar(), bivarinterfacemodule::interpolatevector(), refinementmodule::iteratemeshrefinementonevariable(), refinementmodule::iteratemeshrefinementtwovariables(), mpisetupmodule::loadbalance(), numberkindsmodule::numprocs, ssrfpackremeshmodule::remeshcounter, and betaplanemeshmodule::setstreamfunctionsonmesh().
subroutine ssrfpackremeshmodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the SsrfpackRemesh module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 706 of file SsrfpackRemesh.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine, public ssrfpackremeshmodule::lagrangianremeshbvetoreferencemesh (type(bvemesh), intent(inout) newSphere, type(bvemesh), intent(inout) oldSphere, type(bvemesh), intent(in) refSphere, type(bveremeshsource), intent(in) refRemesh, logical(klog), intent(in) AMR, procedure(flagfunction) flagFn1, real(kreal), intent(in) tol1, character(len=*), intent(in) desc1, procedure(flagfunction), optional flagFn2, real(kreal), intent(in), optional tol2, character(len=*), intent(in), optional desc2, logical(klog), intent(in), optional RefineFlowMapYN, real(kreal), intent(in), optional flowMapVarTol)
Performs a remesh/remap of an LPM SphereBVE simulation using indirect interpolation for all variables in a BVE mesh. Remaps to reference time t = t_{rm}, where t_{rm} is time of definition for a reference mesh (numerical solution). Note that the reference mesh's Lagrangian parameter has been reset, so that x = x0, y = y0, z = z0 at t = t_{rm}.
Parameters
[in,out] newSphere target SphereBVE mesh (note that this must have been allocated prior to calling this subroutine)
[in] oldSphere source SphereBVE mesh
[in] refSphere SphereBVE reference mesh
[in] refRemesh remesh data structure associated with refSphere
[in] AMR .TRUE. if adaptive refinement will be used
[in] flagFn1 FlagFunction for vorticity refinement, must have same interface as refinementmodule::FlagFunction
[in] tol1 tolerance for flagFn1
[in] desc1 description of AMR criterion used for flagFn1
[in] flagFn2 FlagFunction for vorticity refinement, must have same interface as refinementmodule::FlagFunction
[in] tol2 tolerance for flagFn2
[in] desc2 description of AMR criterion used for flagFn2
[in] RefineFLowMapYN True if refinement of the flow map will be used
[in] flowMapVarTol tolerance value for Lagrangian coordinate variation per face
Definition at line 510 of file SsrfpackRemesh.f90.
References bivarinterfacemodule::interpolatelagparam(), bivarinterfacemodule::interpolatescalar(), bivarinterfacemodule::interpolatevector(), refinementmodule::iteratemeshrefinementonevariable(), refinementmodule::iteratemeshrefinementonevariableandflowmap(), refinementmodule::iteratemeshrefinementtwovariables(), refinementmodule::iteratemeshrefinementtwovariablesandflowmap(), mpisetupmodule::loadbalance(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, ssrfpackremeshmodule::new::newbve(), numberkindsmodule::numprocs, and betaplanemeshmodule::setstreamfunctionsonmesh().
subroutine, public ssrfpackremeshmodule::lagrangianremeshbvewithvorticityfunction (type(bveremeshsource), intent(in) self, type(bvemesh), intent(in) oldSphere, type(bvemesh), intent(inout) newSphere, logical(klog), intent(in) AMR, procedure(scalarfnof3dspace) relVortFn, procedure(flagfunction) flagFn1, real(kreal), intent(in) tol1, character(len=*), intent(in) desc1, procedure(flagfunction), optional flagFn2, real(kreal), intent(in), optional tol2, character(len=*), intent(in), optional desc2, logical(klog), intent(in), optional RefineFlowMapYN, real(kreal), intent(in), optional flowMapVarTol, integer(kint), intent(in), optional nLagTracers, procedure(scalarfnof3dspace), optional tracerFn1, procedure(scalarfnof3dspace), optional tracerFn2)
Performs a remesh/remap of an LPM BVE simulation using indirect interpolation for the variables in a SphereBVE mesh. Remaps to reference time t = 0.
Parameters
[in] self Remeshing data structure
[in] oldSphere source SphereBVE mesh
[in,out] newSphere target SphereBVE mesh (note that this must have been allocated prior to calling this subroutine)
[in] AMR true if adaptive refinement will be used
[in] relVortFn Vorticity distribution function, must have same interface as numberkindsmodule::scalarFnOf3DSpace
[in] flagFn1 FlagFunction for vorticity refinement, must have same interface as refinementmodule::FlagFunction
[in] tol1 tolerance for flagFn1
[in] desc1 description of AMR criterion used for flagFn1
[in] flagFn2 FlagFunction for vorticity refinement, must have same interface as refinementmodule::FlagFunction
[in] tol2 tolerance for flagFn2
[in] desc2 description of AMR criterion used for flagFn2
[in] RefineFLowMapYN True if refinement of the flow map will be used
[in] flowMapVarTol tolerance value for Lagrangian coordinate variation per face
[in] nLagTracers number of Lagrangian passive tracers (currently 0, 1, or 2 are only values allowed)
[in] tracerFn1 tracer distribution function, must have same interface as numberkindsmodule::scalarFnOf3DSpace
[in] tracerFn2 tracer distribution function, must have same interface as numberkindsmodule::scalarFnOf3DSpace
Definition at line 320 of file SsrfpackRemesh.f90.
References bivarinterfacemodule::interpolatelagparam(), bivarinterfacemodule::interpolatescalar(), bivarinterfacemodule::interpolatevector(), refinementmodule::iteratemeshrefinementonevariable(), refinementmodule::iteratemeshrefinementonevariableandflowmap(), refinementmodule::iteratemeshrefinementtwovariables(), refinementmodule::iteratemeshrefinementtwovariablesandflowmap(), mpisetupmodule::loadbalance(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, numberkindsmodule::numprocs, betaplanemeshmodule::outputtovtk(), ssrfpackremeshmodule::remeshcounter, and betaplanemeshmodule::setstreamfunctionsonmesh().
subroutine ssrfpackremeshmodule::newbve (type(bveremeshsource), intent(out) self, type(bvemesh), intent(inout) oldSphere) private
Allocates memory and initializes a remapping utility for a SphereBVE BVE mesh.
Parameters
[out] self target Remeshing data structure
[in] oldSphere source SphereBVE
Definition at line 90 of file SsrfpackRemesh.f90.
References initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, numberkindsmodule::procrank, ssrfpackinterfacemodule::setscalarsourcedata(), ssrfpackinterfacemodule::setsourcelagrangianparameter(), and ssrfpackinterfacemodule::setvectorsourcedata().
subroutine ssrfpackremeshmodule::new::newbve (type(bveremeshsource), intent(out) self, type(bvemesh), intent(inout) oldSphere) private
Allocates memory and initializes a remapping utility for a SphereBVE BVE mesh.
Parameters
[out] self target Remeshing data structure
[in] oldSphere source SphereBVE
Definition at line 90 of file SsrfpackRemesh.f90.
Variable Documentation
type(ssrfpackinterface) ssrfpackremeshmodule::bveremeshsource::absvortsource private
Source data for absolute vorticity interpolation.
Definition at line 45 of file SsrfpackRemesh.f90.
type(delaunaytriangulation) ssrfpackremeshmodule::bveremeshsource::deltri private
Delaunay triangulation from STRIPACK.
Definition at line 43 of file SsrfpackRemesh.f90.
type(ssrfpackinterface) ssrfpackremeshmodule::bveremeshsource::lagparamsource private
Source data for Lagrangian parameter interpolation.
Definition at line 46 of file SsrfpackRemesh.f90.
type(logger) ssrfpackremeshmodule::log private
Definition at line 74 of file SsrfpackRemesh.f90.
logical(klog), save ssrfpackremeshmodule::loginit = .FALSE. private
Definition at line 73 of file SsrfpackRemesh.f90.
character(len=28), save ssrfpackremeshmodule::logkey = 'SSRFRemesh' private
Definition at line 75 of file SsrfpackRemesh.f90.
integer(kint), parameter ssrfpackremeshmodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 77 of file SsrfpackRemesh.f90.
character(len=max_string_length) ssrfpackremeshmodule::logstring private
Definition at line 76 of file SsrfpackRemesh.f90.
type(ssrfpackinterface) ssrfpackremeshmodule::bveremeshsource::relvortsource private
Source data for relative vorticity interpolation.
Definition at line 44 of file SsrfpackRemesh.f90.
integer(kint), save ssrfpackremeshmodule::remeshcounter = 0 private
Definition at line 53 of file SsrfpackRemesh.f90.
type(ssrfpackinterface), dimension(:), allocatable ssrfpackremeshmodule::bveremeshsource::tracersource private
Source data for passive tracers.
Definition at line 47 of file SsrfpackRemesh.f90.