LPM: Lagrangian Particle Methods: PlanarIncompressibleSolver
PlanarIncompressibleSolver
Data structure for integrating a planar incompressible flow forward in time using a fourth-order Runge-Kutta method.
Detailed Description
Data structure for integrating a planar incompressible flow forward in time using a fourth-order Runge-Kutta method.
Data Types
interface planarincompressiblesolvermodule::new
interface planarincompressiblesolvermodule::delete
interface planarincompressiblesolvermodule::timestep
Functions/Subroutines
final planarincompressiblesolvermodule::planesolver::deleteprivate
subroutine planarincompressiblesolvermodule::new::newprivate (self, plane)
Allocates memory for a new solver. Unlike a mesh, which maintains extra space in memory for possible adaptive refinement, solvers only allocate memory based on the current number of particles. Hence, a new solver needs to be created every time a mesh is refined.
subroutine planarincompressiblesolvermodule::delete::deleteprivate (self)
Deletes and frees memory associated with a PlanarIncompressible solver.
subroutine planarincompressiblesolvermodule::timestep::timestepprivate (self, plane, dt)
Advances a PlanarIncompressible mesh forward in time by one timestep using 4th order Runge-Kutta.
subroutine planarincompressiblesolvermodule::newprivate (self, plane)
Allocates memory for a new solver. Unlike a mesh, which maintains extra space in memory for possible adaptive refinement, solvers only allocate memory based on the current number of particles. Hence, a new solver needs to be created every time a mesh is refined.
subroutine planarincompressiblesolvermodule::deleteprivate (self)
Deletes and frees memory associated with a PlanarIncompressible solver.
subroutine planarincompressiblesolvermodule::timestepprivate (self, plane, dt)
Advances a PlanarIncompressible mesh forward in time by one timestep using 4th order Runge-Kutta.
subroutine planarincompressiblesolvermodule::planarincompressiblevelocity (u, v, x, y, vortIn, areaIn, activeMask, mpiParticles)
Computes velocity based on the given vorticity of all point vortices (particles) using the Biot-Savart integral. Integral is computed in parallel as a direct summation.
subroutine planarincompressiblesolvermodule::initlogger (aLog, rank)
Initializes a logger for the PlanarIncompressible solver module.
Variables
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::xstart
starting x-coordinate of each particle
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::ystart
starting y-coordinate of each particle
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::u
x-component of velocity for each particle
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::v
y-component of velocity for each particle
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::vort
vorticity carried by each particle
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::area
area represented by each particle (passive particles represent zero area)
logical(klog), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::mask
mask(i) is .TRUE. if particle i is active
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::xin
x-coordinate input to RK4
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::xstage1
x-coordinates of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::xstage2
x-coordinates of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::xstage3
x-coordinates of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::xstage4
x-coordinates of each particle at RK4 stage 4
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::yin
y-coordinate input to RK4
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::ystage1
y-coordinates of each particle at RK4 stage 1
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::ystage2
y-coordinates of each particle at RK4 stage 2
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::ystage3
y-coordinates of each particle at RK4 stage 3
real(kreal), dimension(:),
allocatable planarincompressiblesolvermodule::planesolver::ystage4
y-coordinates of each particle at RK4 stage 4
logical(klog), save planarincompressiblesolvermodule::loginit = .FALSE.
type(logger) planarincompressiblesolvermodule::log
character(len=28), save planarincompressiblesolvermodule::logkey = 'PlaneIncSolver'
integer(kint), parameter planarincompressiblesolvermodule::loglevel = DEBUG_LOGGING_LEVEL
character(len=max_string_length) planarincompressiblesolvermodule::logstring
Function/Subroutine Documentation
subroutine planarincompressiblesolvermodule::deleteprivate (type(planesolver), intent(inout) self) private
Deletes and frees memory associated with a PlanarIncompressible solver.
Parameters
[in,out] self solver
Definition at line 143 of file PlaneIncompressibleSolver.f90.
final planarincompressiblesolvermodule::planesolver::deleteprivate () final private
Definition at line 58 of file PlaneIncompressibleSolver.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine planarincompressiblesolvermodule::delete::deleteprivate (type(planesolver), intent(inout) self) private
Deletes and frees memory associated with a PlanarIncompressible solver.
Parameters
[in,out] self solver
Definition at line 143 of file PlaneIncompressibleSolver.f90.
subroutine planarincompressiblesolvermodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the PlanarIncompressible solver module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 326 of file PlaneIncompressibleSolver.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine planarincompressiblesolvermodule::newprivate (type(planesolver), intent(out) self, type(planemeshincompressible), intent(in) plane) private
Allocates memory for a new solver. Unlike a mesh, which maintains extra space in memory for possible adaptive refinement, solvers only allocate memory based on the current number of particles. Hence, a new solver needs to be created every time a mesh is refined.
Parameters
[out] self Target solver
[in] plane PlanarIncompressible mesh
Definition at line 103 of file PlaneIncompressibleSolver.f90.
References initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, and numberkindsmodule::procrank.
subroutine planarincompressiblesolvermodule::new::newprivate (type(planesolver), intent(out) self, type(planemeshincompressible), intent(in) plane) private
Allocates memory for a new solver. Unlike a mesh, which maintains extra space in memory for possible adaptive refinement, solvers only allocate memory based on the current number of particles. Hence, a new solver needs to be created every time a mesh is refined.
Parameters
[out] self Target solver
[in] plane PlanarIncompressible mesh
Definition at line 103 of file PlaneIncompressibleSolver.f90.
subroutine planarincompressiblesolvermodule::planarincompressiblevelocity (real(kreal), dimension(:), intent(out) u, real(kreal), dimension(:), intent(out) v, real(kreal), dimension(:), intent(in) x, real(kreal), dimension(:), intent(in) y, real(kreal), dimension(:), intent(in) vortIn, real(kreal), dimension(:), intent(in) areaIn, logical(klog), dimension(:), intent(in) activeMask, type(mpisetup), intent(in) mpiParticles) private
Computes velocity based on the given vorticity of all point vortices (particles) using the Biot-Savart integral. Integral is computed in parallel as a direct summation.
Parameters
[out] u x-component of velocity at each particle
[out] v y-component of velocity at each particle
[in] x x-coordinate of each particle
[in] y y-coordinate of each particle
[in] vortIn vorticity carried by each particle
[in] areaIn area carried by each particle
[in] activeMask .TRUE. for active particles, .FALSE. for passive particles
[in] mpiParticles MPISetup object to distribute integral over MPI processes
Definition at line 281 of file PlaneIncompressibleSolver.f90.
References numberkindsmodule::numprocs, numberkindsmodule::pi, and numberkindsmodule::procrank.
subroutine planarincompressiblesolvermodule::timestepprivate (type(planesolver), intent(inout) self, type(planemeshincompressible), intent(inout) plane, real(kreal), intent(in) dt) private
Advances a PlanarIncompressible mesh forward in time by one timestep using 4th order Runge-Kutta.
Parameters
[in,out] self PlanarIncompressible solver
[in,out] plane PlanarIncompressible mesh
[in] dt timestep increment
Definition at line 171 of file PlaneIncompressibleSolver.f90.
References planarincompressiblesolvermodule::planarincompressiblevelocity(), and planarincompressiblemodule::setstreamfunctiononmesh().
subroutine planarincompressiblesolvermodule::timestep::timestepprivate (type(planesolver), intent(inout) self, type(planemeshincompressible), intent(inout) plane, real(kreal), intent(in) dt) private
Advances a PlanarIncompressible mesh forward in time by one timestep using 4th order Runge-Kutta.
Parameters
[in,out] self PlanarIncompressible solver
[in,out] plane PlanarIncompressible mesh
[in] dt timestep increment
Definition at line 171 of file PlaneIncompressibleSolver.f90.
Variable Documentation
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::area private
area represented by each particle (passive particles represent zero area)
Definition at line 43 of file PlaneIncompressibleSolver.f90.
type(logger) planarincompressiblesolvermodule::log private
Definition at line 84 of file PlaneIncompressibleSolver.f90.
logical(klog), save planarincompressiblesolvermodule::loginit = .FALSE. private
Definition at line 83 of file PlaneIncompressibleSolver.f90.
character(len=28), save planarincompressiblesolvermodule::logkey = 'PlaneIncSolver' private
Definition at line 85 of file PlaneIncompressibleSolver.f90.
integer(kint), parameter planarincompressiblesolvermodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 86 of file PlaneIncompressibleSolver.f90.
character(len=max_string_length) planarincompressiblesolvermodule::logstring private
Definition at line 87 of file PlaneIncompressibleSolver.f90.
logical(klog), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::mask private
mask(i) is .TRUE. if particle i is active
Definition at line 44 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::u private
x-component of velocity for each particle
Definition at line 40 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::v private
y-component of velocity for each particle
Definition at line 41 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::vort private
vorticity carried by each particle
Definition at line 42 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::xin private
x-coordinate input to RK4
Definition at line 46 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::xstage1 private
x-coordinates of each particle at RK4 stage 1
Definition at line 47 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::xstage2 private
x-coordinates of each particle at RK4 stage 2
Definition at line 48 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::xstage3 private
x-coordinates of each particle at RK4 stage 3
Definition at line 49 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::xstage4 private
x-coordinates of each particle at RK4 stage 4
Definition at line 50 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::xstart private
starting x-coordinate of each particle
Definition at line 38 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::yin private
y-coordinate input to RK4
Definition at line 51 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::ystage1 private
y-coordinates of each particle at RK4 stage 1
Definition at line 52 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::ystage2 private
y-coordinates of each particle at RK4 stage 2
Definition at line 53 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::ystage3 private
y-coordinates of each particle at RK4 stage 3
Definition at line 54 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::ystage4 private
y-coordinates of each particle at RK4 stage 4
Definition at line 55 of file PlaneIncompressibleSolver.f90.
real(kreal), dimension(:), allocatable planarincompressiblesolvermodule::planesolver::ystart private
starting y-coordinate of each particle
Definition at line 39 of file PlaneIncompressibleSolver.f90.