LPM: Lagrangian Particle Methods: OutputWriter
OutputWriter
Provides an interface for writing output to the console.
Detailed Description
Provides an interface for writing output to the console.
Data Types
interface outputwritermodule::new
Initializes and OutputWriter object.
interface outputwritermodule::delete
Deletes and frees memory associated with an OutputWriter object.
interface outputwritermodule::startsection
Starts an indented section.
interface outputwritermodule::endsection
Ends an indented section.
interface outputwritermodule::write
Writes various output to console.
interface outputwritermodule::writetomatlab
Writes various output to a .m file for later loading in Matlab.
Functions/Subroutines
subroutine outputwritermodule::new::newprivate (self, fileUnit, fileName)
Initializes a new OutputWriter object.
subroutine outputwritermodule::delete::deleteprivate (self)
Deletes and frees memory associated with an OutputWriter object.
subroutine outputwritermodule::startsection::startsectionwriter (self, sectionName, description)
Starts an indented section with a title and optional description.
subroutine outputwritermodule::startsection::startblanksectionwriter (self)
Starts an indented section with no title.
subroutine outputwritermodule::endsection::endsectionwriter (self)
Ends an indented sectionName.
subroutine outputwritermodule::write::writestring (self, key, str)
Writes a key/value pair with appropriate indentation.
subroutine outputwritermodule::write::writeinteger (self, key, val)
Writes a key/value pair with appropriate indentation.
subroutine outputwritermodule::write::writereal (self, key, val)
Writes a key/value pair with appropriate indentation.
subroutine outputwritermodule::write::writeintvector (self, key, val)
Writes a key/value pair with appropriate indentation.
subroutine outputwritermodule::writetomatlab::writearraytomatlab (array, fileunit, name)
Writes a vector (1-d array) of real numbers to a .m file for later reading by Matlab.
subroutine outputwritermodule::writetomatlab::writematrixtomatlab (matrix, fileunit, name)
Writes a matrix (2-d array) of real numbers to a .m file for later reading by Matlab.
subroutine outputwritermodule::writetomatlab::writeintegermatrixtomatlab (matrix, fileunit, name)
Writes a matrix (2-d array) of integers to a .m file for later reading by Matlab.
subroutine outputwritermodule::newprivate (self, fileUnit, fileName)
Initializes a new OutputWriter object.
subroutine outputwritermodule::deleteprivate (self)
Deletes and frees memory associated with an OutputWriter object.
subroutine outputwritermodule::writestring (self, key, str)
Writes a key/value pair with appropriate indentation.
subroutine outputwritermodule::writeinteger (self, key, val)
Writes a key/value pair with appropriate indentation.
subroutine outputwritermodule::writereal (self, key, val)
Writes a key/value pair with appropriate indentation.
subroutine outputwritermodule::writeintvector (self, key, val)
Writes a key/value pair with appropriate indentation.
subroutine outputwritermodule::startblanksectionwriter (self)
Starts an indented section with no title.
subroutine outputwritermodule::startsectionwriter (self, sectionName, description)
Starts an indented section with a title and optional description.
subroutine outputwritermodule::endsectionwriter (self)
Ends an indented sectionName.
subroutine, public outputwritermodule::writevtkfileheader (fileunit, title)
Writes the header of a Legacy formatted .vtk ASCII file.
subroutine, public outputwritermodule::writevtkpointdatasectionheader (fileunit, nPoints)
Writes the section header for VTK Point Data in a legacy formatted .vtk file.
subroutine outputwritermodule::writearraytomatlab (array, fileunit, name)
Writes a vector (1-d array) of real numbers to a .m file for later reading by Matlab.
subroutine outputwritermodule::writematrixtomatlab (matrix, fileunit, name)
Writes a matrix (2-d array) of real numbers to a .m file for later reading by Matlab.
subroutine outputwritermodule::writeintegermatrixtomatlab (matrix, fileunit, name)
Writes a matrix (2-d array) of integers to a .m file for later reading by Matlab.
character(len=len(formatstring)+10)
function outputwritermodule::formatwithindent (self, formatString)
This function returns a string with white space prepended to the intput formatString to provide appropriate indentation.
Variables
integer(kint) outputwritermodule::outputwriter::fileunit
integer(kint) outputwritermodule::outputwriter::indentlevel
character(len=max_string_length) outputwritermodule::outputwriter::filename
integer(kint), parameter outputwritermodule::tab_space = 4
Function/Subroutine Documentation
subroutine outputwritermodule::deleteprivate (type(outputwriter), intent(inout) self) private
Deletes and frees memory associated with an OutputWriter object.
Parameters
self Target OutputWriter object
Definition at line 133 of file OutputWriter.f90.
References numberkindsmodule::std_err, and numberkindsmodule::std_out.
subroutine outputwritermodule::delete::deleteprivate (type(outputwriter), intent(inout) self) private
Deletes and frees memory associated with an OutputWriter object.
Parameters
self Target OutputWriter object
Definition at line 133 of file OutputWriter.f90.
subroutine outputwritermodule::endsectionwriter (type(outputwriter), intent(inout) self) private
Ends an indented sectionName.
Parameters
self Target OutputWriter object
Definition at line 237 of file OutputWriter.f90.
References stdintvectormodule::stdintvector::print().
subroutine outputwritermodule::endsection::endsectionwriter (type(outputwriter), intent(inout) self) private
Ends an indented sectionName.
Parameters
self Target OutputWriter object
Definition at line 237 of file OutputWriter.f90.
character(len=len(formatstring)+10) function outputwritermodule::formatwithindent (type(outputwriter), intent(in) self, character(len=*), intent(in) formatString) private
This function returns a string with white space prepended to the intput formatString to provide appropriate indentation.
Parameters
self Target OutputWriter object
formatString Format intsructions for console output
Definition at line 352 of file OutputWriter.f90.
References outputwritermodule::tab_space.
subroutine outputwritermodule::newprivate (type(outputwriter), intent(out) self, integer(kint), intent(in), optional fileUnit, character(len=*), intent(in), optional fileName) private
Initializes a new OutputWriter object.
Todo:
In later versions, fileunit and filename will allow an OutputWriter's output to be redirected to a file
Parameters
self Target writer to be initialized
fileunit placeholder
filename placeholder
Definition at line 100 of file OutputWriter.f90.
References stdintvectormodule::stdintvector::print(), numberkindsmodule::std_err, and numberkindsmodule::std_out.
subroutine outputwritermodule::new::newprivate (type(outputwriter), intent(out) self, integer(kint), intent(in), optional fileUnit, character(len=*), intent(in), optional fileName) private
Initializes a new OutputWriter object.
Todo:
In later versions, fileunit and filename will allow an OutputWriter's output to be redirected to a file
Parameters
self Target writer to be initialized
fileunit placeholder
filename placeholder
Definition at line 100 of file OutputWriter.f90.
subroutine outputwritermodule::startblanksectionwriter (type(outputwriter), intent(inout) self) private
Starts an indented section with no title.
Parameters
self Target OutputWriter object
Definition at line 212 of file OutputWriter.f90.
subroutine outputwritermodule::startsection::startblanksectionwriter (type(outputwriter), intent(inout) self) private
Starts an indented section with no title.
Parameters
self Target OutputWriter object
Definition at line 212 of file OutputWriter.f90.
subroutine outputwritermodule::startsectionwriter (type(outputwriter), intent(inout) self, character(len=*), intent(in) sectionName, character(len=*), intent(in), optional description) private
Starts an indented section with a title and optional description.
Parameters
self Target OutputWriter object
sectionName Title or subtitle of indented section
description Description of indented section
Definition at line 221 of file OutputWriter.f90.
References outputwritermodule::formatwithindent(), and numberkindsmodule::procrank.
subroutine outputwritermodule::startsection::startsectionwriter (type(outputwriter), intent(inout) self, character(len=*), intent(in) sectionName, character(len=*), intent(in), optional description) private
Starts an indented section with a title and optional description.
Parameters
self Target OutputWriter object
sectionName Title or subtitle of indented section
description Description of indented section
Definition at line 221 of file OutputWriter.f90.
subroutine outputwritermodule::writearraytomatlab (real(kreal), dimension(:), intent(in) array, integer(kint), intent(in) fileunit, character(len=*), intent(in) name) private
Writes a vector (1-d array) of real numbers to a .m file for later reading by Matlab.
Parameters
array Array to be written to a file
fileunit Integer unit of output .m file
name Name of array
Definition at line 275 of file OutputWriter.f90.
subroutine outputwritermodule::writetomatlab::writearraytomatlab (real(kreal), dimension(:), intent(in) array, integer(kint), intent(in) fileunit, character(len=*), intent(in) name) private
Writes a vector (1-d array) of real numbers to a .m file for later reading by Matlab.
Parameters
array Array to be written to a file
fileunit Integer unit of output .m file
name Name of array
Definition at line 275 of file OutputWriter.f90.
subroutine outputwritermodule::writeinteger (type(outputwriter), intent(in) self, character(len=*), intent(in) key, integer(kint), intent(in) val) private
Writes a key/value pair with appropriate indentation.
Parameters
self Target OutputWriter object
key identification key
val value associated with key
Definition at line 168 of file OutputWriter.f90.
References outputwritermodule::formatwithindent().
subroutine outputwritermodule::write::writeinteger (type(outputwriter), intent(in) self, character(len=*), intent(in) key, integer(kint), intent(in) val) private
Writes a key/value pair with appropriate indentation.
Parameters
self Target OutputWriter object
key identification key
val value associated with key
Definition at line 168 of file OutputWriter.f90.
subroutine outputwritermodule::writeintegermatrixtomatlab (integer(kint), dimension(:,:), intent(in) matrix, integer(kint), intent(in) fileunit, character(len=*), intent(in) name) private
Writes a matrix (2-d array) of integers to a .m file for later reading by Matlab.
Parameters
matrix Matrix to be written to a file
fileunit Integer unit of output .m file
name Name of array
Definition at line 320 of file OutputWriter.f90.
subroutine outputwritermodule::writetomatlab::writeintegermatrixtomatlab (integer(kint), dimension(:,:), intent(in) matrix, integer(kint), intent(in) fileunit, character(len=*), intent(in) name) private
Writes a matrix (2-d array) of integers to a .m file for later reading by Matlab.
Parameters
matrix Matrix to be written to a file
fileunit Integer unit of output .m file
name Name of array
Definition at line 320 of file OutputWriter.f90.
subroutine outputwritermodule::writeintvector (type(outputwriter), intent(in) self, character(len=*), intent(in) key, type(stdintvector), intent(in) val) private
Writes a key/value pair with appropriate indentation.
Parameters
self Target OutputWriter object
key identification key
val value associated with key
Definition at line 198 of file OutputWriter.f90.
References outputwritermodule::formatwithindent().
subroutine outputwritermodule::write::writeintvector (type(outputwriter), intent(in) self, character(len=*), intent(in) key, type(stdintvector), intent(in) val) private
Writes a key/value pair with appropriate indentation.
Parameters
self Target OutputWriter object
key identification key
val value associated with key
Definition at line 198 of file OutputWriter.f90.
subroutine outputwritermodule::writematrixtomatlab (real(kreal), dimension(:,:), intent(in) matrix, integer(kint), intent(in) fileunit, character(len=*), intent(in) name) private
Writes a matrix (2-d array) of real numbers to a .m file for later reading by Matlab.
Parameters
matrix Matrix to be written to a file
fileunit Integer unit of output .m file
name Name of array
Definition at line 294 of file OutputWriter.f90.
subroutine outputwritermodule::writetomatlab::writematrixtomatlab (real(kreal), dimension(:,:), intent(in) matrix, integer(kint), intent(in) fileunit, character(len=*), intent(in) name) private
Writes a matrix (2-d array) of real numbers to a .m file for later reading by Matlab.
Parameters
matrix Matrix to be written to a file
fileunit Integer unit of output .m file
name Name of array
Definition at line 294 of file OutputWriter.f90.
subroutine outputwritermodule::writereal (type(outputwriter), intent(in) self, character(len=*), intent(in) key, real(kreal), intent(in) val) private
Writes a key/value pair with appropriate indentation.
Parameters
self Target OutputWriter object
key identification key
val value associated with key
Definition at line 181 of file OutputWriter.f90.
References outputwritermodule::formatwithindent().
subroutine outputwritermodule::write::writereal (type(outputwriter), intent(in) self, character(len=*), intent(in) key, real(kreal), intent(in) val) private
Writes a key/value pair with appropriate indentation.
Parameters
self Target OutputWriter object
key identification key
val value associated with key
Definition at line 181 of file OutputWriter.f90.
subroutine outputwritermodule::writestring (type(outputwriter), intent(in) self, character(len=*), intent(in) key, character(len=*), intent(in), optional str) private
Writes a key/value pair with appropriate indentation.
Parameters
self Target OutputWriter object
key identification key
str value associated with key
Definition at line 150 of file OutputWriter.f90.
References outputwritermodule::formatwithindent().
subroutine outputwritermodule::write::writestring (type(outputwriter), intent(in) self, character(len=*), intent(in) key, character(len=*), intent(in), optional str) private
Writes a key/value pair with appropriate indentation.
Parameters
self Target OutputWriter object
key identification key
str value associated with key
Definition at line 150 of file OutputWriter.f90.
subroutine, public outputwritermodule::writevtkfileheader (integer(kint), intent(in) fileunit, character(len=*), intent(in), optional title)
Writes the header of a Legacy formatted .vtk ASCII file.
Parameters
fileunit Integer unit of output .vtk file
title for .vtk file
Definition at line 249 of file OutputWriter.f90.
subroutine, public outputwritermodule::writevtkpointdatasectionheader (integer(kint), intent(in) fileunit, integer(kint), intent(in) nPoints)
Writes the section header for VTK Point Data in a legacy formatted .vtk file.
Parameters
[in] fileunit Integer unit of output .vtk file
[in] nPoints Integer number of points
Definition at line 265 of file OutputWriter.f90.
Variable Documentation
character(len=max_string_length) outputwritermodule::outputwriter::filename private
Definition at line 40 of file OutputWriter.f90.
integer(kint) outputwritermodule::outputwriter::fileunit private
Definition at line 38 of file OutputWriter.f90.
integer(kint) outputwritermodule::outputwriter::indentlevel private
Definition at line 39 of file OutputWriter.f90.
integer(kint), parameter outputwritermodule::tab_space = 4 private
Definition at line 43 of file OutputWriter.f90.