LPM: Lagrangian Particle Methods: Edges
Edges
Edges of polyhedral meshes connect to vertices and faces.
Detailed Description
Edges of polyhedral meshes connect to vertices and faces.
Edges know the indices of their origin and destination particles (in a Particles object), and the indices of their left face and right face (in a Faces object).
The edges data structures is a "structure of arrays," so that all information about edge i is located at index i in the relevant array. For example, the index to the particle at the origin of edge i is anEdges%orig(i) , and its destination particle is anEdges%dest(i). An edge's left and right faces are accessed similarly, anEdges%leftFace(i) gives the index of the face (in a Faces object) to the left of edge i.
In addition the edges are organized into a binary tree, defined by the hasChildren, children, and parent arrays, to facilitate faster searching through the data structure.
Data Types
interface edgesmodule::new
interface edgesmodule::delete
interface edgesmodule::copy
interface edgesmodule::logstats
interface edgesmodule::printdebuginfo
interface edgesmodule::countparents
Functions/Subroutines
final edgesmodule::edges::deleteprivate
subroutine edgesmodule::new::newprivate (self, nMax)
Allocates memory for a new edges object. All values are zeroed and must be initialized separately.
subroutine edgesmodule::delete::deleteprivate (self)
Deletes and frees memory associated with an edges object.
subroutine edgesmodule::copy::copyprivate (self, other)
Performs a deep copy of one edges object into another. They must have been allocated the same to avoid memory errors.
subroutine edgesmodule::logstats::logstatsprivate (self, aLog)
Log summarizing statistics about an edges object.
subroutine edgesmodule::printdebuginfo::printdebugprivate (self)
Writes edges object values to the console. For debugging.
integer(kint) function edgesmodule::countparents::countparentedges (self, index)
Counts the number of levels in the edges binary tree above the edge at index.
subroutine edgesmodule::newprivate (self, nMax)
Allocates memory for a new edges object. All values are zeroed and must be initialized separately.
subroutine edgesmodule::deleteprivate (self)
Deletes and frees memory associated with an edges object.
subroutine edgesmodule::copyprivate (self, other)
Performs a deep copy of one edges object into another. They must have been allocated the same to avoid memory errors.
subroutine edgesmodule::logstatsprivate (self, aLog)
Log summarizing statistics about an edges object.
subroutine, public edgesmodule::insertedge (self, aParticles, origIndex, destIndex, leftFace, rightFace)
Inserts an edge to the end of an edges object. Increase edges.N by one.
integer(kint) function edgesmodule::countparentedges (self, index)
Counts the number of levels in the edges binary tree above the edge at index.
real(kreal) function, public edgesmodule::maxedgelength (self, aParticles)
Computes the maximum edge length amongst all leaf edges.
real(kreal) function, public edgesmodule::edgelength (self, edgeIndex, aParticles)
Computes the length of the edge at edgeIndex.
real(kreal) function, public edgesmodule::minedgelength (self, aParticles)
Computes the minimum edge length amongst all leaf edges.
real(kreal) function, public edgesmodule::avgedgelength (self, aParticles)
Computes the average edge length amongst all leaf edges.
subroutine, public edgesmodule::writeedgestomatlab (self, fileunit)
Writes the edges data structure to a .m file for later reading by Matlab. For debugging.
subroutine edgesmodule::printdebugprivate (self)
Writes edges object values to the console. For debugging.
subroutine, public edgesmodule::recordincidentedgeatparticles (self, edgeIndex, aParticles)
Records the index of an incident edge at its origin and destination particles. Enables dual mesh functionality.
real(kreal) function edgesmodule::edgeangleatorig (self, edgeIndex, aParticles)
Determines the angle relative to the positive x-direction (for planar geometry) or the angle relative to the first edge listed at the origin particle (for spherical geometry). Used for dual-mesh functionality.
real(kreal) function edgesmodule::edgeangleatdest (self, edgeIndex, aParticles)
Determines the angle of edge at edgeIndex relative to the positive x-direction (for planar geometry) or the angle relative to the first edge listed at the destination particle (for spherical geometry). Used for dual-mesh functionality.
real(kreal) function, dimension(3) edgesmodule::edgevector (self, edgeIndex, aParticles)
Returns a vector pointing from an edge's origin particle to its destination particle.
subroutine, public edgesmodule::divideedge (self, edgeIndex, aParticles)
Divides a parent edge, creating two child edges with the same orientation.
subroutine, public edgesmodule::replaceincidentedgewithchild (self, parentIndex, aParticles)
Replaces an edge recorded at its incident particles with the appropriate child edge index.
logical(klog) function, public edgesmodule::positiveedge (anEdges, faceIndex, edgeIndex)
Returns .TRUE. if an edge has positive orientation relative to the selected face.
logical(klog) function, public edgesmodule::onboundary (anEdges, edgeIndex)
Returns .TRUE. if an edge is on the boundary of a mesh (does not apply to spherical meshes, which have no boundaries)
subroutine, public edgesmodule::getleafedgesfromparent (anEdges, parentIndex, leafEdges)
Builds a STDIntVector containing the indices of all of an edge's children.
real(kreal) function, public edgesmodule::areafromleafedges (self, aParticles, centerParticle, leafEdges, nLeaves)
Computes the area represented by the triangles connecting the vertices of an edge's child particles and the center particle of their common face. Used for adaptively refined meshes.
subroutine edgesmodule::initlogger (aLog, rank)
Initializes a logger for the Edges module.
Variables
integer(kint), dimension(:),
allocatable edgesmodule::edges::orig
Integer array containing indices of particlesmodule::particles.
integer(kint), dimension(:),
allocatable edgesmodule::edges::dest
Integer array containing indices of particlesmodule::particles.
integer(kint), dimension(:),
allocatable edgesmodule::edges::rightface
Integer array containing indices of facesmodule::faces.
integer(kint), dimension(:),
allocatable edgesmodule::edges::leftface
Integer array containing indices of facesmodule::faces.
integer(kint), dimension(:),
allocatable edgesmodule::edges::child1
Integer array containing indices to child edges with same origin vertex as parent.
integer(kint), dimension(:),
allocatable edgesmodule::edges::child2
Integer array containing indices to child edges with same destination vertex as parent.
logical(klog), dimension(:),
allocatable edgesmodule::edges::haschildren
hasChildren(i) is .TRUE. if edge i has been divided
integer(kint), dimension(:),
allocatable edgesmodule::edges::parent
Null for root edges. Integer pointers into edges for divided edges.
integer(kint) edgesmodule::edges::n = 0
Number of edges currently in use.
integer(kint) edgesmodule::edges::n_max = 0
Max number of edges allowed in memory.
logical(klog), save edgesmodule::loginit = .FALSE.
type(logger) edgesmodule::log
character(len=28), save edgesmodule::logkey = 'Edges'
integer(kint), parameter edgesmodule::loglevel = DEBUG_LOGGING_LEVEL
Function/Subroutine Documentation
real(kreal) function, public edgesmodule::areafromleafedges (type(edges), intent(in) self, type(particles), intent(in) aParticles, integer(kint), intent(in) centerParticle, integer(kint), dimension(:), intent(in) leafEdges, integer(kint), intent(in) nLeaves)
Computes the area represented by the triangles connecting the vertices of an edge's child particles and the center particle of their common face. Used for adaptively refined meshes.
Parameters
self Target edge object
aParticles particles object associated with this set of edges
centerParticle index to the particle at the center of the edge's face
leafEdges indices of the child edges associated with a face whose neighbors may be more refined than itself
nLeaves number of leafEdges
Returns
Area represented by one side of a polyhedral face
Definition at line 730 of file Edges.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, particlesmodule::physcoord(), numberkindsmodule::planar_geom, numberkindsmodule::sphere_geom, and planegeommodule::triarea().
real(kreal) function, public edgesmodule::avgedgelength (type(edges), intent(in) self, type(particles), intent(in) aParticles)
Computes the average edge length amongst all leaf edges.
Parameters
self Target edge object
aParticles particles object associated with this set of edges
Returns
average edge length
Definition at line 317 of file Edges.f90.
References edgesmodule::edgelength().
subroutine edgesmodule::copyprivate (type(edges), intent(inout) self, type(edges), intent(in) other) private
Performs a deep copy of one edges object into another. They must have been allocated the same to avoid memory errors.
Parameters
self Target edge object
other Source edge object
Definition at line 158 of file Edges.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine edgesmodule::copy::copyprivate (type(edges), intent(inout) self, type(edges), intent(in) other) private
Performs a deep copy of one edges object into another. They must have been allocated the same to avoid memory errors.
Parameters
self Target edge object
other Source edge object
Definition at line 158 of file Edges.f90.
integer(kint) function edgesmodule::countparentedges (type(edges), intent(in) self, integer(kint), intent(in) index) private
Counts the number of levels in the edges binary tree above the edge at index.
Parameters
self Target edge object
index index of target edge
Definition at line 231 of file Edges.f90.
integer(kint) function edgesmodule::countparents::countparentedges (type(edges), intent(in) self, integer(kint), intent(in) index) private
Counts the number of levels in the edges binary tree above the edge at index.
Parameters
self Target edge object
index index of target edge
Definition at line 231 of file Edges.f90.
subroutine edgesmodule::deleteprivate (type(edges), intent(inout) self) private
Deletes and frees memory associated with an edges object.
Parameters
self Target edge object
Definition at line 143 of file Edges.f90.
final edgesmodule::edges::deleteprivate () final private
Definition at line 63 of file Edges.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine edgesmodule::delete::deleteprivate (type(edges), intent(inout) self) private
Deletes and frees memory associated with an edges object.
Parameters
self Target edge object
Definition at line 143 of file Edges.f90.
subroutine, public edgesmodule::divideedge (type(edges), intent(inout) self, integer(kint), intent(in) edgeIndex, type(particles), intent(inout) aParticles)
Divides a parent edge, creating two child edges with the same orientation.
Parameters
self Target edge object
edgeIndex target edge
aParticles particles object associated with this set of edges
Definition at line 560 of file Edges.f90.
References loggermodule::error_logging_level, particlesmodule::insertparticle(), particlesmodule::lagcoord(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, particlesmodule::physcoord(), edgesmodule::recordincidentedgeatparticles(), edgesmodule::replaceincidentedgewithchild(), numberkindsmodule::sphere_geom, and spheregeommodule::spheremidpoint().
real(kreal) function edgesmodule::edgeangleatdest (type(edges), intent(in) self, integer(kint), intent(in) edgeIndex, type(particles), intent(in) aParticles) private
Determines the angle of edge at edgeIndex relative to the positive x-direction (for planar geometry) or the angle relative to the first edge listed at the destination particle (for spherical geometry). Used for dual-mesh functionality.
Todo:
This doesn't work.
Parameters
self Target edge object
edgeIndex target edge
aParticles particles object associated with this set of edges
Definition at line 497 of file Edges.f90.
References spheregeommodule::crossproduct(), edgesmodule::edgevector(), loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, numberkindsmodule::planar_geom, numberkindsmodule::sphere_geom, and loggermodule::warning_logging_level.
real(kreal) function edgesmodule::edgeangleatorig (type(edges), intent(in) self, integer(kint), intent(in) edgeIndex, type(particles), intent(in) aParticles) private
Determines the angle relative to the positive x-direction (for planar geometry) or the angle relative to the first edge listed at the origin particle (for spherical geometry). Used for dual-mesh functionality.
Todo:
This doesn't work.
Parameters
self Target edge object
edgeIndex target edge
aParticles particles object associated with this set of edges
Definition at line 449 of file Edges.f90.
References spheregeommodule::crossproduct(), edgesmodule::edgevector(), loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, numberkindsmodule::planar_geom, numberkindsmodule::sphere_geom, and loggermodule::warning_logging_level.
real(kreal) function, public edgesmodule::edgelength (type(edges), intent(in) self, integer(kint), intent(in) edgeIndex, type(particles), intent(in) aParticles)
Computes the length of the edge at edgeIndex.
Parameters
self Target edge object
edgeIndex location of edge whose length is needed
aParticles particles object associated with this set of edges
Returns
Length of edge
Definition at line 275 of file Edges.f90.
References spheregeommodule::chorddistance(), particlesmodule::physcoord(), and numberkindsmodule::sphere_geom.
real(kreal) function, dimension(3) edgesmodule::edgevector (type(edges), intent(in) self, integer(kint), intent(in) edgeIndex, type(particles), intent(in) aParticles) private
Returns a vector pointing from an edge's origin particle to its destination particle.
Parameters
self Target edge object
edgeIndex target edge
aParticles particles object associated with this set of edges
Definition at line 542 of file Edges.f90.
subroutine, public edgesmodule::getleafedgesfromparent (type(edges), intent(in) anEdges, integer(kint), intent(in) parentIndex, type(stdintvector), intent(out) leafEdges)
Builds a STDIntVector containing the indices of all of an edge's children.
Parameters
anEdges Target edge object
parentIndex edge whose children are needed
leafEdges On output, the indices of parentEdge's children
Definition at line 691 of file Edges.f90.
subroutine edgesmodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the Edges module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 773 of file Edges.f90.
References betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine, public edgesmodule::insertedge (type(edges), intent(inout) self, type(particles), intent(inout) aParticles, integer(kint), intent(in) origIndex, integer(kint), intent(in) destIndex, integer(kint), intent(in) leftFace, integer(kint), intent(in) rightFace)
Inserts an edge to the end of an edges object. Increase edges.N by one.
Parameters
self Target edge object
aParticles particlesmdoule::particles object associated with this set of edges
origIndex index to origin particle
destIndex index to destination particle
leftFace index to left face of new edge in faces object
rightFace index to right face of new edge in faces object
Definition at line 204 of file Edges.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, and edgesmodule::recordincidentedgeatparticles().
subroutine edgesmodule::logstatsprivate (type(edges), intent(in) self, type(logger), intent(inout) aLog) private
Log summarizing statistics about an edges object.
Parameters
self Target edge object
aLog Target loggermodule::logger object for output
Definition at line 185 of file Edges.f90.
References betaplanemeshmodule::logkey, and loggermodule::trace_logging_level.
subroutine edgesmodule::logstats::logstatsprivate (type(edges), intent(in) self, type(logger), intent(inout) aLog) private
Log summarizing statistics about an edges object.
Parameters
self Target edge object
aLog Target loggermodule::logger object for output
Definition at line 185 of file Edges.f90.
real(kreal) function, public edgesmodule::maxedgelength (type(edges), intent(in) self, type(particles), intent(in) aParticles)
Computes the maximum edge length amongst all leaf edges.
Parameters
self Target edge object
aParticles particles object associated with this set of edges
Returns
Maximum edge length
Definition at line 253 of file Edges.f90.
References edgesmodule::edgelength().
real(kreal) function, public edgesmodule::minedgelength (type(edges), intent(in) self, type(particles), intent(in) aParticles)
Computes the minimum edge length amongst all leaf edges.
Parameters
self Target edge object
aParticles particles object associated with this set of edges
Returns
Minimum edge length
Definition at line 296 of file Edges.f90.
References edgesmodule::edgelength().
subroutine edgesmodule::newprivate (type(edges), intent(out) self, integer(kint), intent(in) nMax) private
Allocates memory for a new edges object. All values are zeroed and must be initialized separately.
Parameters
self Target edge object
nMax max number of edges allowed in memory
Definition at line 109 of file Edges.f90.
References loggermodule::error_logging_level, initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and numberkindsmodule::procrank.
subroutine edgesmodule::new::newprivate (type(edges), intent(out) self, integer(kint), intent(in) nMax) private
Allocates memory for a new edges object. All values are zeroed and must be initialized separately.
Parameters
self Target edge object
nMax max number of edges allowed in memory
Definition at line 109 of file Edges.f90.
logical(klog) function, public edgesmodule::onboundary (type(edges), intent(in) anEdges, integer(kint), intent(in) edgeIndex)
Returns .TRUE. if an edge is on the boundary of a mesh (does not apply to spherical meshes, which have no boundaries)
Parameters
anEdges Target edge object
edgeIndex target edge
Definition at line 679 of file Edges.f90.
logical(klog) function, public edgesmodule::positiveedge (type(edges), intent(in) anEdges, integer(kint), intent(in) faceIndex, integer(kint), intent(in) edgeIndex)
Returns .TRUE. if an edge has positive orientation relative to the selected face.
Todo:
This function should output an error if edgeIndex is not a member of faces.edges(:)
Parameters
anEdges Target edge object
faceIndex Integer index to a face in a facesmodule::faces object
edgeIndex Integer index to an edge
Returns
.TRUE. if edge has positive orientation relative to the chosen face
Definition at line 667 of file Edges.f90.
subroutine edgesmodule::printdebugprivate (type(edges), intent(in) self) private
Writes edges object values to the console. For debugging.
Parameters
self Target edge object
Definition at line 366 of file Edges.f90.
References stdintvectormodule::stdintvector::print().
subroutine edgesmodule::printdebuginfo::printdebugprivate (type(edges), intent(in) self) private
Writes edges object values to the console. For debugging.
Parameters
self Target edge object
Definition at line 366 of file Edges.f90.
subroutine, public edgesmodule::recordincidentedgeatparticles (type(edges), intent(in) self, integer(kint), intent(in) edgeIndex, type(particles), intent(inout) aParticles)
Records the index of an incident edge at its origin and destination particles. Enables dual mesh functionality.
Todo:
This doesn't work.
Parameters
self Target edge object
edgeIndex target edge
aParticles particles object associated with this set of edges
Definition at line 389 of file Edges.f90.
References edgesmodule::edgeangleatdest(), edgesmodule::edgeangleatorig(), loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, and numberkindsmodule::max_vertex_degree.
subroutine, public edgesmodule::replaceincidentedgewithchild (type(edges), intent(in) self, integer(kint), intent(in) parentIndex, type(particles), intent(inout) aParticles)
Replaces an edge recorded at its incident particles with the appropriate child edge index.
Parameters
self Target edge object
parentIndex index of edge that was divided
aParticles particles object associated with this set of edges
Definition at line 616 of file Edges.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine, public edgesmodule::writeedgestomatlab (type(edges), intent(in) self, integer(kint), intent(in) fileunit)
Writes the edges data structure to a .m file for later reading by Matlab. For debugging.
Parameters
self Target edge object
fileunit integer unit of .m file
Definition at line 338 of file Edges.f90.
Variable Documentation
integer(kint), dimension(:), allocatable edgesmodule::edges::child1 private
Integer array containing indices to child edges with same origin vertex as parent.
Definition at line 55 of file Edges.f90.
integer(kint), dimension(:), allocatable edgesmodule::edges::child2 private
Integer array containing indices to child edges with same destination vertex as parent.
Definition at line 56 of file Edges.f90.
integer(kint), dimension(:), allocatable edgesmodule::edges::dest private
Integer array containing indices of particlesmodule::particles.
Definition at line 52 of file Edges.f90.
logical(klog), dimension(:), allocatable edgesmodule::edges::haschildren private
hasChildren(i) is .TRUE. if edge i has been divided
Definition at line 57 of file Edges.f90.
integer(kint), dimension(:), allocatable edgesmodule::edges::leftface private
Integer array containing indices of facesmodule::faces.
Definition at line 54 of file Edges.f90.
type(logger) edgesmodule::log private
Definition at line 96 of file Edges.f90.
logical(klog), save edgesmodule::loginit = .FALSE. private
Definition at line 95 of file Edges.f90.
character(len=28), save edgesmodule::logkey = 'Edges' private
Definition at line 97 of file Edges.f90.
integer(kint), parameter edgesmodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 98 of file Edges.f90.
integer(kint) edgesmodule::edges::n = 0 private
Number of edges currently in use.
Definition at line 59 of file Edges.f90.
integer(kint) edgesmodule::edges::n_max = 0 private
Max number of edges allowed in memory.
Definition at line 60 of file Edges.f90.
integer(kint), dimension(:), allocatable edgesmodule::edges::orig private
Integer array containing indices of particlesmodule::particles.
Definition at line 51 of file Edges.f90.
integer(kint), dimension(:), allocatable edgesmodule::edges::parent private
Null for root edges. Integer pointers into edges for divided edges.
Definition at line 58 of file Edges.f90.
integer(kint), dimension(:), allocatable edgesmodule::edges::rightface private
Integer array containing indices of facesmodule::faces.
Definition at line 53 of file Edges.f90.