LPM: Lagrangian Particle Methods: PSEDirectSum
PSEDirectSum
Data structure and methods for approximations of scattered data and derivatives using Particle Strength Exchange (PSE).
Detailed Description
Data structure and methods for approximations of scattered data and derivatives using Particle Strength Exchange (PSE).
PSE provides a method for approximating derivatives on scattered data by replacing a differential operator with an integral convolution that approximates the action of the differential operator in the sense of distributions.
PSE approximations converge as a small parameter \(\epsilon \) approaches zero in a limit that also depends on the distance between particles, \(\Delta x \),
\[ \epsilon = \Delta x^{1/p},\quad p>1. \]
A differential operator \(D^\beta \), where \(\beta \) is a multi-index, is approximated by a linear integral operator \(L^\beta \),
\[ D^\beta f(\vec{x}) \approx L^\beta f(\vec{x}) = \frac{1}{\epsilon^{|\beta|}}\int_{\mathbb{R}^d} \left(f(\vec{y}) \mp f(\vec{x})\right)\eta_\epsilon^\beta(\vec{x}-\vec{y})\,dV(\vec{y}), \]
where d the dimension of the space, \(\eta_{\epsilon}^\beta = \eta^\beta(|\vec{x}|/\epsilon) \), where \(\eta^\beta \) is defined to satisfy a set of moment conditions related to \(D^\beta\) that define its order of accuracy as \(\epsilon\to 0\).
Using PSE for derivatives transforms spatial derivatives on moving sets of LPM particles into integrals of the same form we already use to compute the velocity.
Like stream functions and the Biot-Savart integral, PSE integrals are currently computed using a parallel direct summation algorithm.
For a detailed description of how to construct PSE kernels for Euclidean spaces with free boundaries, see
J. Eldredge, A. Leonard, and T. Colonius, A general deterministic treatment of derivatives in particle methods, J. Comput. Phys., 180 (2002).
Data Types
interface psedirectsummodule::new
interface psedirectsummodule::delete
Functions/Subroutines
final psedirectsummodule::pse::deleteprivate
subroutine psedirectsummodule::new::newprivate (self, aMesh, radiusMultiplier)
Initializes a new PSE object and computes the PSE parameter epsilon.
subroutine psedirectsummodule::delete::deleteprivate (self)
Deletes and frees memory associated with a PSE object.
subroutine psedirectsummodule::newprivate (self, aMesh, radiusMultiplier)
Initializes a new PSE object and computes the PSE parameter epsilon.
subroutine psedirectsummodule::deleteprivate (self)
Deletes and frees memory associated with a PSE object.
pure real(kreal) function, public psedirectsummodule::pseplaneinterpolatescalar (self, aMesh, scalarField, interpLoc)
Interpolates a scalar field in the plane using convolution with a kernel that approximates a delta function.
subroutine, public psedirectsummodule::pseplanegradientatparticles (self, aMesh, scalarField, scalarGrad, particlesMPI)
Constructs a Field that approximates that gradient of a scalar in the plane using PSE.
subroutine, public psedirectsummodule::psespheregradientatparticles (self, amesh, scalarField, scalarGrad, particlesMPI)
subroutine, public psedirectsummodule::pseplanesecondpartialsatparticles (self, aMesh, scalarGrad, secondPartials, particlesMPI)
subroutine, public psedirectsummodule::pseplanedoubledotproductatparticles (self, aMesh, vectorField, doubleDot, particlesMPI)
subroutine psedirectsummodule::psespheredoubledotproductatparticles (self, aMesh, vectorField, doubleDot, particlesMPI)
subroutine psedirectsummodule::psedoubledotproductarrays (self, doubleDot, xIn, yIn, uIn, vIn, areaIn, activeMask, mpiParticles)
subroutine, public psedirectsummodule::pseplanelaplacianatparticles (self, aMesh, scalarField, scalarLap, particlesMPI)
Constructs a Field that approximates that Laplacian of a scalar in the plane using PSE.
subroutine, public psedirectsummodule::psespherelaplacianatparticles (self, aMesh, scalarField, scalarLap, particlesMPI)
pure real(kreal) function, public psedirectsummodule::psesphereinterpolatescalar (self, aMesh, scalarField, interpLoc)
subroutine, public psedirectsummodule::psespheredivergenceatparticles (self, aMesh, vectorField, divergence, particlesMPI)
pure real(kreal) function psedirectsummodule::integralkernelinput (xi, xj, eps, geomKind)
Computes the scaled input to a PSE kernel.
pure real(kreal) function psedirectsummodule::bivariatedeltakernel8 (radialDist)
Computes the value of a kernel that approximates a delta function on \(\mathbb{R}^2 \) to 8th order accuracy.
pure real(kreal) function, public psedirectsummodule::bivariatelaplaciankernel8 (radialDist)
Computes the value of a kernel that approximates the Laplacian on \(\mathbb{R}^2 \) to 8th order accuracy.
pure real(kreal) function, public psedirectsummodule::bivariatefirstderivativekernel8 (radialDist)
pure real(kreal) function psedirectsummodule::bivariatesecondderivativekernel8 (radialDist)
pure real(kreal) function psedirectsummodule::bivariatemixedsecondderivativekernel8 (radialDist, x, y)
pure real(kreal) function psedirectsummodule::trivariatedeltakernel8 (radialDist)
pure real(kreal) function psedirectsummodule::trivariatefirstderivativekernel8 (radialDist, eps)
subroutine psedirectsummodule::initlogger (aLog, rank)
Initializes a logger for the PSEDirectSum module.
Variables
real(kreal) psedirectsummodule::pse::eps
PSE radius of influence, depends on mesh size.
logical(klog), save psedirectsummodule::loginit = .FALSE.
type(logger) psedirectsummodule::log
character(len=28), save psedirectsummodule::logkey = 'PSE'
integer(kint), parameter psedirectsummodule::loglevel = DEBUG_LOGGING_LEVEL
Function/Subroutine Documentation
pure real(kreal) function psedirectsummodule::bivariatedeltakernel8 (real(kreal), intent(in) radialDist) private
Computes the value of a kernel that approximates a delta function on \(\mathbb{R}^2 \) to 8th order accuracy.
Parameters
[in] radialDist Kernel input, typically from psedirectsummodule::integralkernelinput
Returns
kernel value
Definition at line 608 of file PSEDirectSum.f90.
References numberkindsmodule::pi.
pure real(kreal) function, public psedirectsummodule::bivariatefirstderivativekernel8 (real(kreal), intent(in) radialDist)
Definition at line 626 of file PSEDirectSum.f90.
References numberkindsmodule::pi.
pure real(kreal) function, public psedirectsummodule::bivariatelaplaciankernel8 (real(kreal), intent(in) radialDist)
Computes the value of a kernel that approximates the Laplacian on \(\mathbb{R}^2 \) to 8th order accuracy.
Parameters
[in] radialDist Kernel input, typically from psedirectsummodule::integralkernelinput
Returns
kernel value
Definition at line 619 of file PSEDirectSum.f90.
References numberkindsmodule::pi.
pure real(kreal) function psedirectsummodule::bivariatemixedsecondderivativekernel8 (real(kreal), intent(in) radialDist, real(kreal), intent(in) x, real(kreal), intent(in) y) private
Definition at line 640 of file PSEDirectSum.f90.
References numberkindsmodule::pi.
pure real(kreal) function psedirectsummodule::bivariatesecondderivativekernel8 (real(kreal), intent(in) radialDist) private
Definition at line 633 of file PSEDirectSum.f90.
References numberkindsmodule::pi.
subroutine psedirectsummodule::deleteprivate (type(pse), intent(inout) self) private
Deletes and frees memory associated with a PSE object.
Parameters
[in,out] self PSE object
Definition at line 115 of file PSEDirectSum.f90.
final psedirectsummodule::pse::deleteprivate () final private
Definition at line 58 of file PSEDirectSum.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine psedirectsummodule::delete::deleteprivate (type(pse), intent(inout) self) private
Deletes and frees memory associated with a PSE object.
Parameters
[in,out] self PSE object
Definition at line 115 of file PSEDirectSum.f90.
subroutine psedirectsummodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the PSEDirectSum module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 668 of file PSEDirectSum.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
pure real(kreal) function psedirectsummodule::integralkernelinput (real(kreal), dimension(3), intent(in) xi, real(kreal), dimension(3), intent(in) xj, real(kreal), intent(in) eps, integer(kint), intent(in) geomKind) private
Computes the scaled input to a PSE kernel.
Parameters
[in] xi position vector of particle i
[in] xj position vector of particle j
[in] eps PSE parameter
[in] geomKind geometry kind (e.g., planar or spherical) as defined in NumberKinds
Returns
Scaled kernel input \(\frac{|\vec{x}_i - \vec{x}_j|}{\epsilon} \)
Definition at line 591 of file PSEDirectSum.f90.
References spheregeommodule::chorddistance(), numberkindsmodule::planar_geom, and numberkindsmodule::sphere_geom.
subroutine psedirectsummodule::newprivate (type(pse), intent(out) self, type(polymesh2d), intent(in) aMesh, real(kreal), intent(in), optional radiusMultiplier) private
Initializes a new PSE object and computes the PSE parameter epsilon.
Epsilon is defined to be a fractional power of the mesh size,
\[ \epsilon = \Delta x^{1/p},\quad p > 1 \]
Definition at line 92 of file PSEDirectSum.f90.
References initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, edgesmodule::maxedgelength(), and numberkindsmodule::procrank.
subroutine psedirectsummodule::new::newprivate (type(pse), intent(out) self, type(polymesh2d), intent(in) aMesh, real(kreal), intent(in), optional radiusMultiplier) private
Initializes a new PSE object and computes the PSE parameter epsilon.
Epsilon is defined to be a fractional power of the mesh size,
\[ \epsilon = \Delta x^{1/p},\quad p > 1 \]
Definition at line 92 of file PSEDirectSum.f90.
subroutine psedirectsummodule::psedoubledotproductarrays (type(pse), intent(in) self, real(kreal), dimension(:), intent(out) doubleDot, real(kreal), dimension(:), intent(in) xIn, real(kreal), dimension(:), intent(in) yIn, real(kreal), dimension(:), intent(in) uIn, real(kreal), dimension(:), intent(in) vIn, real(kreal), dimension(:), intent(in) areaIn, logical(klog), dimension(:), intent(in) activeMask, type(mpisetup), intent(in) mpiParticles) private
Definition at line 396 of file PSEDirectSum.f90.
References psedirectsummodule::bivariatefirstderivativekernel8(), numberkindsmodule::numprocs, and numberkindsmodule::procrank.
subroutine, public psedirectsummodule::pseplanedoubledotproductatparticles (type(pse), intent(in) self, type(polymesh2d), intent(in) aMesh, type(field), intent(in) vectorField, type(field), intent(inout) doubleDot, type(mpisetup), intent(in) particlesMPI)
Definition at line 298 of file PSEDirectSum.f90.
References psedirectsummodule::bivariatefirstderivativekernel8(), spheregeommodule::chorddistance(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, numberkindsmodule::numprocs, particlesmodule::physcoord(), numberkindsmodule::procrank, and fieldmodule::setfieldtozero().
subroutine, public psedirectsummodule::pseplanegradientatparticles (type(pse), intent(in) self, type(polymesh2d), intent(in) aMesh, type(field), intent(in) scalarField, type(field), intent(inout) scalarGrad, type(mpisetup), intent(in) particlesMPI)
Constructs a Field that approximates that gradient of a scalar in the plane using PSE.
Integration is carried out in parallel using direct summation.
Parameters
[in] self PSE object
[in] aMesh PolyMesh2d
[in] scalarField scalar Field containing source data
[in,out] scalarGrad vector Field (preallocated) that, on output, stores the approximate scalar gradient at each particles
[in] particlesMPI MPISetup object to distribute particles across processes
Definition at line 156 of file PSEDirectSum.f90.
References psedirectsummodule::bivariatefirstderivativekernel8(), spheregeommodule::chorddistance(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, fieldmodule::multiplyfieldbyscalar(), numberkindsmodule::numprocs, particlesmodule::physcoord(), numberkindsmodule::procrank, and fieldmodule::setfieldtozero().
pure real(kreal) function, public psedirectsummodule::pseplaneinterpolatescalar (type(pse), intent(in) self, type(polymesh2d), intent(in) aMesh, type(field), intent(in) scalarField, real(kreal), dimension(3), intent(in) interpLoc)
Interpolates a scalar field in the plane using convolution with a kernel that approximates a delta function.
Parameters
[in] self PSE object
[in] aMesh PolyMesh2d
[in] scalarField scalar Field
[in] interpLoc position vector of desired interpolation location
Returns
Interpolated scalar value
Definition at line 126 of file PSEDirectSum.f90.
References psedirectsummodule::bivariatedeltakernel8(), spheregeommodule::chorddistance(), and particlesmodule::physcoord().
subroutine, public psedirectsummodule::pseplanelaplacianatparticles (type(pse), intent(in) self, type(polymesh2d), intent(in) aMesh, type(field), intent(in) scalarField, type(field), intent(inout) scalarLap, type(mpisetup), intent(in) particlesMPI)
Constructs a Field that approximates that Laplacian of a scalar in the plane using PSE.
Integration is carried out in parallel using direct summation.
Parameters
[in] self PSE object
[in] aMesh PolyMesh2d
[in] scalarField scalar Field containing source data
[in,out] scalarLap scalar Field (preallocated) that, on output, stores the approximate Laplacian at each particle
[in] particlesMPI MPISetup object to distribute particles across processes
Definition at line 443 of file PSEDirectSum.f90.
References psedirectsummodule::bivariatelaplaciankernel8(), spheregeommodule::chorddistance(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, fieldmodule::multiplyfieldbyscalar(), numberkindsmodule::numprocs, particlesmodule::physcoord(), numberkindsmodule::procrank, and fieldmodule::setfieldtozero().
subroutine, public psedirectsummodule::pseplanesecondpartialsatparticles (type(pse), intent(in) self, class(polymesh2d), intent(in) aMesh, type(field), intent(in) scalarGrad, type(field), intent(inout) secondPartials, type(mpisetup), intent(in) particlesMPI)
Definition at line 245 of file PSEDirectSum.f90.
References psedirectsummodule::bivariatefirstderivativekernel8(), spheregeommodule::chorddistance(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, fieldmodule::multiplyfieldbyscalar(), numberkindsmodule::numprocs, particlesmodule::physcoord(), numberkindsmodule::procrank, and fieldmodule::setfieldtozero().
subroutine, public psedirectsummodule::psespheredivergenceatparticles (type(pse), intent(in) self, type(polymesh2d), intent(in) aMesh, type(field), intent(in) vectorField, type(field), intent(inout) divergence, type(mpisetup), intent(in) particlesMPI)
Definition at line 534 of file PSEDirectSum.f90.
References psedirectsummodule::bivariatefirstderivativekernel8(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, fieldmodule::multiplyfieldbyscalar(), numberkindsmodule::numprocs, particlesmodule::physcoord(), numberkindsmodule::procrank, fieldmodule::setfieldtozero(), and spheregeommodule::sphereprojection().
subroutine psedirectsummodule::psespheredoubledotproductatparticles (type(pse), intent(in) self, type(polymesh2d), intent(in) aMesh, type(field), intent(in) vectorField, type(field), intent(inout) doubleDot, type(mpisetup), intent(in) particlesMPI) private
Definition at line 343 of file PSEDirectSum.f90.
References psedirectsummodule::bivariatefirstderivativekernel8(), particlesmodule::physcoord(), numberkindsmodule::procrank, and fieldmodule::setfieldtozero().
subroutine, public psedirectsummodule::psespheregradientatparticles (type(pse), intent(in) self, type(polymesh2d), intent(in) amesh, type(field), intent(in) scalarField, type(field), intent(inout) scalarGrad, type(mpisetup), intent(in) particlesMPI)
Definition at line 196 of file PSEDirectSum.f90.
References psedirectsummodule::bivariatefirstderivativekernel8(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, fieldmodule::multiplyfieldbyscalar(), numberkindsmodule::numprocs, particlesmodule::physcoord(), numberkindsmodule::procrank, fieldmodule::setfieldtozero(), and spheregeommodule::sphereprojection().
pure real(kreal) function, public psedirectsummodule::psesphereinterpolatescalar (type(pse), intent(in) self, type(polymesh2d), intent(in) aMesh, type(field), intent(in) scalarField, real(kreal), dimension(3), intent(in) interpLoc)
Definition at line 513 of file PSEDirectSum.f90.
References psedirectsummodule::bivariatedeltakernel8(), and particlesmodule::physcoord().
subroutine, public psedirectsummodule::psespherelaplacianatparticles (type(pse), intent(in) self, type(polymesh2d), intent(in) aMesh, type(field), intent(in) scalarField, type(field), intent(inout) scalarLap, type(mpisetup), intent(in) particlesMPI)
Definition at line 478 of file PSEDirectSum.f90.
References psedirectsummodule::bivariatelaplaciankernel8(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, fieldmodule::multiplyfieldbyscalar(), numberkindsmodule::numprocs, particlesmodule::physcoord(), numberkindsmodule::procrank, and fieldmodule::setfieldtozero().
pure real(kreal) function psedirectsummodule::trivariatedeltakernel8 (real(kreal), intent(in) radialDist) private
Definition at line 647 of file PSEDirectSum.f90.
pure real(kreal) function psedirectsummodule::trivariatefirstderivativekernel8 (real(kreal), intent(in) radialDist, real(kreal), intent(in) eps) private
Definition at line 654 of file PSEDirectSum.f90.
Variable Documentation
real(kreal) psedirectsummodule::pse::eps private
PSE radius of influence, depends on mesh size.
Definition at line 56 of file PSEDirectSum.f90.
type(logger) psedirectsummodule::log private
Definition at line 75 of file PSEDirectSum.f90.
logical(klog), save psedirectsummodule::loginit = .FALSE. private
Definition at line 74 of file PSEDirectSum.f90.
character(len=28), save psedirectsummodule::logkey = 'PSE' private
Definition at line 76 of file PSEDirectSum.f90.
integer(kint), parameter psedirectsummodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 77 of file PSEDirectSum.f90.