LPM: Lagrangian Particle Methods: Faces
Faces
Faces of polyhedral meshes have centers and vertices via the Particles and edges via the Edges.
Detailed Description
Faces of polyhedral meshes have centers and vertices via the Particles and edges via the Edges.
The faces data structures is a "structure of arrays," so that all information about face i is located at index i in the relevant array. For example, the index to the particle at the center of face i aFaces%centerParticle(i) and the vertices of face i can be accessed by aFaces%vertices(:,i).
The faces data structure maintains arrays of pointers (integer indices) into Particles and Edges objects to avoid reproducing the data contained by those structures.
In addition the faces are organized into a quadtree, defined by the hasChildren, children, and parent arrays, to facilitate faster searching through the data structure.
Data Types
interface facesmodule::new
interface facesmodule::delete
interface facesmodule::copy
interface facesmodule::logstats
interface facesmodule::printdebuginfo
interface facesmodule::countparents
Functions/Subroutines
final facesmodule::faces::deleteprivate
subroutine facesmodule::new::newprivate (self, faceKind, nMax)
Allocates memory for a new faces object. New arrays are set to zero, and must be initialized separately.
subroutine facesmodule::delete::deleteprivate (self)
Deletes and frees memory associated with a faces object.
subroutine facesmodule::copy::copyprivate (dest, source)
Performs a deep copy of one faces object into another. Both objects must have been allocated correctly before calling this subroutine.
subroutine facesmodule::logstats::logstatsprivate (self, aLog)
Writes basic info about a faces object to a specified loggermodule::Logger.
subroutine facesmodule::printdebuginfo::printdebugprivate (self)
Prints detailed information about the contents of a faces object to the console. Used for debugging.
integer(kint) function facesmodule::countparents::countparentfaces (self, index)
Counts the number of levels in the faces quadtree above a particular face.
subroutine facesmodule::newprivate (self, faceKind, nMax)
Allocates memory for a new faces object. New arrays are set to zero, and must be initialized separately.
subroutine facesmodule::deleteprivate (self)
Deletes and frees memory associated with a faces object.
subroutine facesmodule::copyprivate (dest, source)
Performs a deep copy of one faces object into another. Both objects must have been allocated correctly before calling this subroutine.
subroutine facesmodule::printdebugprivate (self)
Prints detailed information about the contents of a faces object to the console. Used for debugging.
subroutine facesmodule::logstatsprivate (self, aLog)
Writes basic info about a faces object to a specified loggermodule::Logger.
real(kreal) function,
dimension(3), public facesmodule::facecenterphyscoord (self, faceIndex, aparticles)
Returns the physical coordinates of a face's center particle.
real(kreal) function,
dimension(3), public facesmodule::facecenterlagcoord (self, faceIndex, aparticles)
Returns the Lagrangian coordinates of a face's center particle.
integer(kint) function facesmodule::countparentfaces (self, index)
Counts the number of levels in the faces quadtree above a particular face.
integer(kint) function, public facesmodule::sharededge (self, face1, face2)
Counts the number of shared edges between two faces Outputs an error of this number is > 1.
integer(kint) function, public facesmodule::particleoppositetriedge (self, faceIndex, edgeIndex)
Returns the index to a vertex particle opposite to an edge in a triangular face.
subroutine, public facesmodule::writefacestovtkpolygons (self, fileunit)
Outputs connectivity data to a legacy format .vtk ASCII file. Note: This subroutine must be called in the correct order, after outputwritermodule::writevtkfileheader and particlesmodule::writevtkpoints.
subroutine, public facesmodule::writefaceareatovtkcelldata (self, aParticles, fileunit)
Outputs face areas data to a legacy format .vtk ASCII file. Note: This subroutine must be called in the correct order, after all vtk point data has been written by calls to fieldmodule::writefieldtovtkpointdata and before any other calls to fieldmodule::writefieldtovtkcelldata.
subroutine, public facesmodule::writefacestomatlab (self, fileunit)
Outputs data associated with a faces object, including all connectivity information, to a Matlab-readable .m file.
subroutine, public facesmodule::dividequadface (self, faceIndex, aParticles, anEdges)
This is a primary subroutine used by any quadrilateral mesh (spherical or planar). It divides a quadrilateral face into 4 children, adding a 4 leaves to the faces quadtree. It creates new particles and new edges. It replaces divided edges with their appropriate children.
subroutine, public facesmodule::dividetriface (self, faceIndex, aParticles, anEdges)
This is a primary subroutine used by any triangular mesh (spherical or planar). It divides a triangular face into 4 children, adding a 4 leaves to the faces quadtree. It creates new particles and new edges. It replaces divided edges with their appropriate children.
real(kreal) function, public facesmodule::facearea (self, index, aParticles, anEdges)
Computes the area of a polyhedral face.
subroutine, public facesmodule::insertface (self, centerParticle, vertIndices, edgeIndices)
Inserts a new face into the faces data structure. Increases faces.N by 1.
real(kreal) function, public facesmodule::quadfacearea (self, index, aParticles)
Determines the area of a quadrilateral face. Assumes the face has exactly 4 edges (Does not account for adjacent face's having different levels of refinement).
real(kreal) function, public facesmodule::trifacearea (self, index, aParticles)
Determines the area of a triangular face. Assumes the face has exactly 3 edges (Does not account for adjacent face's having different levels of refinement).
real(kreal) function,
dimension(3), public facesmodule::facecentroid (self, index, aParticles)
Computes the centroid (in physical space) of a face based on its vertices.
subroutine facesmodule::initlogger (aLog, rank)
Initializes a logger for the Faces module.
Variables
integer(kint), dimension(:),
allocatable facesmodule::faces::centerparticle
indices to faces' center particles in a particlesmodule::particles object
integer(kint), dimension(:,:),
allocatable facesmodule::faces::vertices
indices to faces' vertex particles in a particlesmodule::particles object
integer(kint), dimension(:,:),
allocatable facesmodule::faces::edges
indices to faces' edges in an edgesmodule::edges object
logical(klog), dimension(:),
allocatable facesmodule::faces::haschildren
hasChildren(i) is .TRUE. if face i has been divided
integer(kint), dimension(:,:),
allocatable facesmodule::faces::children
indices to child faces in a faces object
integer(kint), dimension(:),
allocatable facesmodule::faces::parent
indices to parent faces in a faces object
integer(kint) facesmodule::faces::facekind
identifies type of face (e.g., triangular, quadrilateral, etc.)
integer(kint) facesmodule::faces::n
Number of faces currently in use.
integer(kint) facesmodule::faces::n_active
Number of undivided faces; these define the spatial discretization.
integer(kint) facesmodule::faces::n_max
Maximum number of faces allowed in memory.
logical(klog), save facesmodule::loginit = .FALSE.
type(logger) facesmodule::log
character(len=28), save facesmodule::logkey = 'Faces'
integer(kint), parameter facesmodule::loglevel = DEBUG_LOGGING_LEVEL
character(len=max_string_length) facesmodule::logstring
Function/Subroutine Documentation
subroutine facesmodule::copyprivate (type(faces), intent(inout) dest, type(faces), intent(in) source) private
Performs a deep copy of one faces object into another. Both objects must have been allocated correctly before calling this subroutine.
Parameters
dest Target faces object
source Source faces object
Definition at line 166 of file Faces.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine facesmodule::copy::copyprivate (type(faces), intent(inout) dest, type(faces), intent(in) source) private
Performs a deep copy of one faces object into another. Both objects must have been allocated correctly before calling this subroutine.
Parameters
dest Target faces object
source Source faces object
Definition at line 166 of file Faces.f90.
integer(kint) function facesmodule::countparentfaces (type(faces), intent(in) self, integer(kint), intent(in) index) private
Counts the number of levels in the faces quadtree above a particular face.
Parameters
self Target Faces object
index Target face
Returns
Number of levels in quadtree above face(i)(
Definition at line 304 of file Faces.f90.
integer(kint) function facesmodule::countparents::countparentfaces (type(faces), intent(in) self, integer(kint), intent(in) index) private
Counts the number of levels in the faces quadtree above a particular face.
Parameters
self Target Faces object
index Target face
Returns
Number of levels in quadtree above face(i)(
Definition at line 304 of file Faces.f90.
subroutine facesmodule::deleteprivate (type(faces), intent(inout) self) private
Deletes and frees memory associated with a faces object.
Parameters
self Target faces object
Definition at line 152 of file Faces.f90.
final facesmodule::faces::deleteprivate () final private
Definition at line 63 of file Faces.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine facesmodule::delete::deleteprivate (type(faces), intent(inout) self) private
Deletes and frees memory associated with a faces object.
Parameters
self Target faces object
Definition at line 152 of file Faces.f90.
subroutine, public facesmodule::dividequadface (type(faces), intent(inout) self, integer(kint), intent(in) faceIndex, type(particles), intent(inout) aParticles, type(edges), intent(inout) anEdges)
This is a primary subroutine used by any quadrilateral mesh (spherical or planar). It divides a quadrilateral face into 4 children, adding a 4 leaves to the faces quadtree. It creates new particles and new edges. It replaces divided edges with their appropriate children.
Parameters
[in,out] self Target faces object
[in] faceIndex index of face to be divided
[in,out] aParticles Particles object associated with this set of faces.
[in,out] anEdges Edges object associated with this set of faces
Definition at line 529 of file Faces.f90.
References edgesmodule::divideedge(), loggermodule::error_logging_level, edgesmodule::insertedge(), particlesmodule::insertparticle(), particlesmodule::lagcoord(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, particlesmodule::makeparticleactive(), particlesmodule::makeparticlepassive(), particlesmodule::physcoord(), numberkindsmodule::planar_geom, edgesmodule::positiveedge(), numberkindsmodule::quad_panel, planegeommodule::quadcentroid(), facesmodule::quadfacearea(), numberkindsmodule::sphere_geom, and spheregeommodule::spherequadcenter().
subroutine, public facesmodule::dividetriface (type(faces), intent(inout) self, integer(kint), intent(in) faceIndex, type(particles), intent(inout) aParticles, type(edges), intent(inout) anEdges)
This is a primary subroutine used by any triangular mesh (spherical or planar). It divides a triangular face into 4 children, adding a 4 leaves to the faces quadtree. It creates new particles and new edges. It replaces divided edges with their appropriate children.
Parameters
[in,out] self Target faces object
[in] faceIndex index of face to be divided
[in,out] aParticles Particles object associated with this set of faces.
[in,out] anEdges Edges object associated with this set of faces
Definition at line 701 of file Faces.f90.
References edgesmodule::divideedge(), loggermodule::error_logging_level, edgesmodule::insertedge(), particlesmodule::insertparticle(), particlesmodule::lagcoord(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, particlesmodule::makeparticleactive(), particlesmodule::physcoord(), numberkindsmodule::planar_geom, edgesmodule::positiveedge(), numberkindsmodule::sphere_geom, spheregeommodule::spheretricenter(), numberkindsmodule::tri_panel, planegeommodule::tricentroid(), and facesmodule::trifacearea().
real(kreal) function, public facesmodule::facearea (type(faces), intent(in) self, integer(kint), intent(in) index, type(particles), intent(in) aParticles, type(edges), intent(in) anEdges)
Computes the area of a polyhedral face.
Parameters
self Target faces object
index Index of face whose area is needed
aParticles Particles object associated with this set of faces
anEdges Edges object associated with this set of faces
Definition at line 866 of file Faces.f90.
References edgesmodule::areafromleafedges(), and edgesmodule::getleafedgesfromparent().
real(kreal) function, dimension(3), public facesmodule::facecenterlagcoord (type(faces), intent(in) self, integer(kint) faceIndex, type(particles), intent(in) aparticles)
Returns the Lagrangian coordinates of a face's center particle.
Parameters
self Target faces object
faceIndex Index to target face
aParticles particlesmodule::particles object associated with this set of faces
Returns
Coordinate vector of face's center particle's Lagrangian coordinate
Definition at line 285 of file Faces.f90.
real(kreal) function, dimension(3), public facesmodule::facecenterphyscoord (type(faces), intent(in) self, integer(kint) faceIndex, type(particles), intent(in) aparticles)
Returns the physical coordinates of a face's center particle.
Parameters
self Target faces object
faceIndex Index to target face
aParticles particlesmodule::particles object associated with this set of faces
Returns
Coordinate vector of face's center particle's position
Definition at line 265 of file Faces.f90.
real(kreal) function, dimension(3), public facesmodule::facecentroid (type(faces), intent(in) self, integer(kint), intent(in) index, type(particles), intent(in) aParticles)
Computes the centroid (in physical space) of a face based on its vertices.
Parameters
[in] self Target faces object
[in] index Index of face whose centroid is needed
[in] aParticles Particles object associated with this set of faces
Returns
Position vector of face centroid
Definition at line 982 of file Faces.f90.
References numberkindsmodule::planar_geom, numberkindsmodule::quad_panel, numberkindsmodule::sphere_geom, numberkindsmodule::sphereradius, and numberkindsmodule::tri_panel.
subroutine facesmodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the Faces module.
Output is controlled both by message priority and by MPI Rank
Parameters
[out] aLog Target Logger object
[in] rank Rank of this processor
Definition at line 1024 of file Faces.f90.
References betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine, public facesmodule::insertface (type(faces), intent(inout) self, integer(kint), intent(in) centerParticle, integer(kint), dimension(:), intent(in) vertIndices, integer(kint), dimension(:), intent(in) edgeIndices)
Inserts a new face into the faces data structure. Increases faces.N by 1.
Parameters
self Target faces object
centerParticle index to a the new face's center particle in a particlesmodule::particles object
vertIndices indices to the new face's vertices in a particlesmodule::particles object
edgeIndices indices to the new face's edges in an edgesmodule::edges object.
Definition at line 891 of file Faces.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine facesmodule::logstatsprivate (type(faces), intent(in) self, type(logger), intent(inout) aLog) private
Writes basic info about a faces object to a specified loggermodule::Logger.
Parameters
self Target faces object
aLog Logger object to handle output
Definition at line 241 of file Faces.f90.
References betaplanemeshmodule::logkey, numberkindsmodule::quad_panel, loggermodule::trace_logging_level, and numberkindsmodule::tri_panel.
subroutine facesmodule::logstats::logstatsprivate (type(faces), intent(in) self, type(logger), intent(inout) aLog) private
Writes basic info about a faces object to a specified loggermodule::Logger.
Parameters
self Target faces object
aLog Logger object to handle output
Definition at line 241 of file Faces.f90.
subroutine facesmodule::newprivate (type(faces), intent(out) self, integer(kint), intent(in) faceKind, integer(kint), intent(in) nMax) private
Allocates memory for a new faces object. New arrays are set to zero, and must be initialized separately.
Todo:
Move faceKind constants from numberkindsmodule to facesmodule?
Parameters
self Target faces object
faceKind Face kind identifier (e.g., triangular, quadrilateral, etc.), as definded in NumberKindsModule
nMax Max amount of memory to allocate
Definition at line 109 of file Faces.f90.
References loggermodule::error_logging_level, initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, numberkindsmodule::procrank, numberkindsmodule::quad_panel, and numberkindsmodule::tri_panel.
subroutine facesmodule::new::newprivate (type(faces), intent(out) self, integer(kint), intent(in) faceKind, integer(kint), intent(in) nMax) private
Allocates memory for a new faces object. New arrays are set to zero, and must be initialized separately.
Todo:
Move faceKind constants from numberkindsmodule to facesmodule?
Parameters
self Target faces object
faceKind Face kind identifier (e.g., triangular, quadrilateral, etc.), as definded in NumberKindsModule
nMax Max amount of memory to allocate
Definition at line 109 of file Faces.f90.
integer(kint) function, public facesmodule::particleoppositetriedge (type(faces), intent(in) self, integer(kint), intent(in) faceIndex, integer(kint), intent(in) edgeIndex)
Returns the index to a vertex particle opposite to an edge in a triangular face.
Parameters
self Target faces object
faceIndex target face
edgeIndex index to an edge from an edgesmodule::edges object
Definition at line 356 of file Faces.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine facesmodule::printdebugprivate (type(faces), intent(in) self) private
Prints detailed information about the contents of a faces object to the console. Used for debugging.
Parameters
self Target faces object
Definition at line 195 of file Faces.f90.
References stdintvectormodule::stdintvector::print().
subroutine facesmodule::printdebuginfo::printdebugprivate (type(faces), intent(in) self) private
Prints detailed information about the contents of a faces object to the console. Used for debugging.
Parameters
self Target faces object
Definition at line 195 of file Faces.f90.
real(kreal) function, public facesmodule::quadfacearea (type(faces), intent(in) self, integer(kint), intent(in) index, type(particles), intent(in) aParticles)
Determines the area of a quadrilateral face. Assumes the face has exactly 4 edges (Does not account for adjacent face's having different levels of refinement).
Parameters
self Target faces object
index Index to face whose area is needed
aParticles Particles object associated with this set of faces
Definition at line 917 of file Faces.f90.
References particlesmodule::physcoord(), numberkindsmodule::planar_geom, numberkindsmodule::sphere_geom, and planegeommodule::triarea().
integer(kint) function, public facesmodule::sharededge (type(faces), intent(in) self, integer(kint), intent(in) face1, integer(kint), intent(in) face2)
Counts the number of shared edges between two faces Outputs an error of this number is > 1.
Parameters
self Target faces object
face1 index to a face
face2 index to another face
Returns
SharedEdge = 0 if faces do not have a common edge, SharedEdge = 1 if faces have a common edge, SharedEdges > 1 is an error, probably with the mesh seed file.
Definition at line 329 of file Faces.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
real(kreal) function, public facesmodule::trifacearea (type(faces), intent(in) self, integer(kint), intent(in) index, type(particles), intent(in) aParticles)
Determines the area of a triangular face. Assumes the face has exactly 3 edges (Does not account for adjacent face's having different levels of refinement).
Parameters
self Target faces object
index Index to face whose area is needed
aParticles Particles object associated with this set of faces
Definition at line 950 of file Faces.f90.
References particlesmodule::physcoord(), numberkindsmodule::planar_geom, numberkindsmodule::sphere_geom, and planegeommodule::triarea().
subroutine, public facesmodule::writefaceareatovtkcelldata (type(faces), intent(in) self, type(particles), intent(in) aParticles, integer(kint), intent(in) fileunit)
Outputs face areas data to a legacy format .vtk ASCII file. Note: This subroutine must be called in the correct order, after all vtk point data has been written by calls to fieldmodule::writefieldtovtkpointdata and before any other calls to fieldmodule::writefieldtovtkcelldata.
Parameters
self Target faces object
aParticles Particles object associated with this set of faces
fileunit Integer unit associated with .vtk file
Definition at line 418 of file Faces.f90.
References numberkindsmodule::quad_panel, and numberkindsmodule::tri_panel.
subroutine, public facesmodule::writefacestomatlab (type(faces), intent(in) self, integer(kint), intent(in) fileunit)
Outputs data associated with a faces object, including all connectivity information, to a Matlab-readable .m file.
Parameters
self Target faces object
fileunit Integer unit associated with a .m file
Definition at line 447 of file Faces.f90.
References numberkindsmodule::quad_panel, and numberkindsmodule::tri_panel.
subroutine, public facesmodule::writefacestovtkpolygons (type(faces), intent(in) self, integer(kint), intent(in) fileunit)
Outputs connectivity data to a legacy format .vtk ASCII file. Note: This subroutine must be called in the correct order, after outputwritermodule::writevtkfileheader and particlesmodule::writevtkpoints.
Parameters
self Target faces object
fileunit Integer unit associated with .vtk file
Definition at line 388 of file Faces.f90.
References numberkindsmodule::quad_panel, and numberkindsmodule::tri_panel.
Variable Documentation
integer(kint), dimension(:), allocatable facesmodule::faces::centerparticle private
indices to faces' center particles in a particlesmodule::particles object
Definition at line 51 of file Faces.f90.
integer(kint), dimension(:,:), allocatable facesmodule::faces::children private
indices to child faces in a faces object
Definition at line 55 of file Faces.f90.
integer(kint), dimension(:,:), allocatable facesmodule::faces::edges private
indices to faces' edges in an edgesmodule::edges object
Definition at line 53 of file Faces.f90.
integer(kint) facesmodule::faces::facekind private
identifies type of face (e.g., triangular, quadrilateral, etc.)
Definition at line 57 of file Faces.f90.
logical(klog), dimension(:), allocatable facesmodule::faces::haschildren private
hasChildren(i) is .TRUE. if face i has been divided
Definition at line 54 of file Faces.f90.
type(logger) facesmodule::log private
Definition at line 96 of file Faces.f90.
logical(klog), save facesmodule::loginit = .FALSE. private
Definition at line 95 of file Faces.f90.
character(len=28), save facesmodule::logkey = 'Faces' private
Definition at line 97 of file Faces.f90.
integer(kint), parameter facesmodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 98 of file Faces.f90.
character(len=max_string_length) facesmodule::logstring private
Definition at line 99 of file Faces.f90.
integer(kint) facesmodule::faces::n private
Number of faces currently in use.
Definition at line 58 of file Faces.f90.
integer(kint) facesmodule::faces::n_active private
Number of undivided faces; these define the spatial discretization.
Definition at line 59 of file Faces.f90.
integer(kint) facesmodule::faces::n_max private
Maximum number of faces allowed in memory.
Definition at line 60 of file Faces.f90.
integer(kint), dimension(:), allocatable facesmodule::faces::parent private
indices to parent faces in a faces object
Definition at line 56 of file Faces.f90.
integer(kint), dimension(:,:), allocatable facesmodule::faces::vertices private
indices to faces' vertex particles in a particlesmodule::particles object
Definition at line 52 of file Faces.f90.