LPM: Lagrangian Particle Methods: Field
Field
Provides a vectorized data structure for scalar and vector fields defined on Particles objects.
Detailed Description
Provides a vectorized data structure for scalar and vector fields defined on Particles objects.
Allows users to set a name and units, if applicable, for each field. Provides a data type for holding variables associated with an LPM spatial discretization by instances of Particles .
May be scalar or vector data. Field objects have a 1-to-1 correspondence with a Particles object, so that the data associated with the particle whose index is i are in the field object also at index i.
The field data structures is a "structure of arrays," so that all information about a scalar of vector field at particle i is located at index i in the field arrays. For example, the value of a scalar carried by particle i is aField%scalar(i). Vector field components must be accessed individually using aField%xComp(i), aField%yComp(i), etc.
Data Types
interface fieldmodule::new
Allocates memory and initializes to null/zero a Field object.
interface fieldmodule::delete
Deletes a Field object and frees its memory.
interface fieldmodule::copy
interface fieldmodule::logstats
Outputs statistics about a Field object to the console via a Logger module object.
Functions/Subroutines
final fieldmodule::field::deleteprivate
subroutine fieldmodule::new::newprivate (self, nDim, nMax, name, units)
Allocates memory and initializes to zero a Field object.
subroutine fieldmodule::delete::deleteprivate (self)
Deallocates memory assigned by newprivate.
subroutine fieldmodule::copy::copyprivate (self, other)
Performs a deep copy of one field object into another.
subroutine fieldmodule::logstats::logstatsprivate (self, aLog)
Writes Field information to console using a loggermodule::logger object for formatting.
subroutine fieldmodule::newprivate (self, nDim, nMax, name, units)
Allocates memory and initializes to zero a Field object.
subroutine fieldmodule::deleteprivate (self)
Deallocates memory assigned by newprivate.
subroutine fieldmodule::copyprivate (self, other)
Performs a deep copy of one field object into another.
subroutine, public fieldmodule::insertscalartofield (self, val)
Inserts a scalar value to a preallocated Field object.
subroutine, public fieldmodule::insertvectortofield (self, vecVal)
Inserts a vector value to a preallocated Field object.
real(kreal) function, public fieldmodule::scalaraverage (self, aParticles)
Finds the area-average of a scalar.
subroutine, public fieldmodule::setfieldtozero (self)
Zeroes all values in a field object.
subroutine, public fieldmodule::multiplyfieldbyscalar (self, multiplier)
Multiplies all values in a field by a scalar.
subroutine, public fieldmodule::writefieldtovtkpointdata (self, fileunit)
Outputs Field object data to a .vtk PolyData file for use with VTK or ParaView.
subroutine, public fieldmodule::writefieldtovtkcelldata (self, fileunit, aFaces)
Outputs Field object data to a .vtk PolyData file for use with VTK or ParaView, if this field is also associated with a faces object.
subroutine fieldmodule::logstatsprivate (self, aLog)
Writes Field information to console using a loggermodule::logger object for formatting.
pure real(kreal) function, public fieldmodule::maxmagnitude (self)
Returns the maximum magnitude of a vector field.
pure real(kreal) function, public fieldmodule::minmagnitude (self)
Returns the minimum magnitude of a vector field.
subroutine, public fieldmodule::writefieldtomatlab (self, fileunit)
Writes Field data to a script .m file readable by Matlab.
subroutine fieldmodule::initlogger (aLog, rank)
Initializes a logger for the Field module.
Variables
real(kreal), dimension(:),
allocatable fieldmodule::field::scalar
Array to hold scalar field data.
real(kreal), dimension(:),
allocatable fieldmodule::field::xcomp
Array to hold the x-component of vector field data.
real(kreal), dimension(:),
allocatable fieldmodule::field::ycomp
Array to hold the y-component of vector field data.
real(kreal), dimension(:),
allocatable fieldmodule::field::zcomp
Array to hold the z-component of vector field data.
character(max_string_length) fieldmodule::field::name = "null"
name of field variable
character(max_string_length) fieldmodule::field::units = "null"
physical units of field variable
integer(kint) fieldmodule::field::n = 0
Number of field values stored (should be equal to the number of particles)
integer(kint) fieldmodule::field::n_max = 0
maximum number of field values allowed in memory
integer(kint) fieldmodule::field::ndim = 0
dimension of field, 1 = scalar, >= 2 for vector fields
logical(klog), save fieldmodule::loginit = .FALSE.
type(logger) fieldmodule::log
character(len=28), save fieldmodule::logkey = 'FieldLog'
integer(kint), parameter fieldmodule::loglevel = DEBUG_LOGGING_LEVEL
Function/Subroutine Documentation
subroutine fieldmodule::copyprivate (type(field), intent(inout) self, type(field), intent(in) other) private
Performs a deep copy of one field object into another.
Parameters
self Target field object
other Source field object
Definition at line 160 of file Field.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine fieldmodule::copy::copyprivate (type(field), intent(inout) self, type(field), intent(in) other) private
Performs a deep copy of one field object into another.
Parameters
self Target field object
other Source field object
Definition at line 160 of file Field.f90.
subroutine fieldmodule::deleteprivate (type(field), intent(inout) self) private
Deallocates memory assigned by newprivate.
Parameters
self Target field object.
Definition at line 149 of file Field.f90.
final fieldmodule::field::deleteprivate () final private
Definition at line 65 of file Field.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine fieldmodule::delete::deleteprivate (type(field), intent(inout) self) private
Deallocates memory assigned by newprivate.
Parameters
self Target field object.
Definition at line 149 of file Field.f90.
subroutine fieldmodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the Field module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 473 of file Field.f90.
References betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine, public fieldmodule::insertscalartofield (type(field), intent(inout) self, real(kreal), intent(in) val)
Inserts a scalar value to a preallocated Field object.
Parameters
self Target field object
val
Definition at line 194 of file Field.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine, public fieldmodule::insertvectortofield (type(field), intent(inout) self, real(kreal), dimension(:), intent(in) vecVal)
Inserts a vector value to a preallocated Field object.
Parameters
self Target field object
vecval
Definition at line 212 of file Field.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine fieldmodule::logstatsprivate (type(field), intent(in) self, type(logger), intent(inout) aLog) private
Writes Field information to console using a loggermodule::logger object for formatting.
Parameters
self
aLog
Definition at line 366 of file Field.f90.
References betaplanemeshmodule::logkey, fieldmodule::maxmagnitude(), fieldmodule::minmagnitude(), and loggermodule::trace_logging_level.
subroutine fieldmodule::logstats::logstatsprivate (type(field), intent(in) self, type(logger), intent(inout) aLog) private
Writes Field information to console using a loggermodule::logger object for formatting.
Parameters
self
aLog
Definition at line 366 of file Field.f90.
pure real(kreal) function, public fieldmodule::maxmagnitude (type(field), intent(in) self)
Returns the maximum magnitude of a vector field.
Parameters
self
Definition at line 387 of file Field.f90.
pure real(kreal) function, public fieldmodule::minmagnitude (type(field), intent(in) self)
Returns the minimum magnitude of a vector field.
Parameters
self
Definition at line 409 of file Field.f90.
subroutine, public fieldmodule::multiplyfieldbyscalar (type(field), intent(inout) self, real(kreal), intent(in) multiplier)
Multiplies all values in a field by a scalar.
Parameters
self Target field object
multiplier
Definition at line 267 of file Field.f90.
subroutine fieldmodule::newprivate (type(field), intent(out) self, integer(kint), intent(in) nDim, integer(kint), intent(in) nMax, character(len=*), intent(in), optional name, character(len=*), intent(in), optional units) private
Allocates memory and initializes to zero a Field object.
Parameters
[out] self Target field object
[in] nDim number of components in this Field object (not the spatial domain of its accompanying particle set)
[in] nMax max number of particles that can be associated with this field
[in] name e.g., vorticity or potential
[in] units physical units, if applicable
Definition at line 104 of file Field.f90.
References loggermodule::error_logging_level, initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and numberkindsmodule::procrank.
subroutine fieldmodule::new::newprivate (type(field), intent(out) self, integer(kint), intent(in) nDim, integer(kint), intent(in) nMax, character(len=*), intent(in), optional name, character(len=*), intent(in), optional units) private
Allocates memory and initializes to zero a Field object.
Parameters
[out] self Target field object
[in] nDim number of components in this Field object (not the spatial domain of its accompanying particle set)
[in] nMax max number of particles that can be associated with this field
[in] name e.g., vorticity or potential
[in] units physical units, if applicable
Definition at line 104 of file Field.f90.
real(kreal) function, public fieldmodule::scalaraverage (type(field), intent(in) self, type(particles), intent(in) aParticles)
Finds the area-average of a scalar.
Parameters
self Target field object
aParticles particlesmodule::particles object associated with this field
Returns
\(\frac{1}{A} \int f(x)\, dA \)
Definition at line 239 of file Field.f90.
References planarincompressiblesolvermodule::planesolver::mask, and particlesmodule::totalarea().
subroutine, public fieldmodule::setfieldtozero (type(field), intent(inout) self)
Zeroes all values in a field object.
Parameters
self Target field object
Definition at line 249 of file Field.f90.
subroutine, public fieldmodule::writefieldtomatlab (type(field), intent(in) self, integer(kint), intent(in) fileunit)
Writes Field data to a script .m file readable by Matlab.
Parameters
self
fileunit
Definition at line 432 of file Field.f90.
subroutine, public fieldmodule::writefieldtovtkcelldata (type(field), intent(in) self, integer(kint), intent(in) fileunit, type(faces), intent(in) aFaces)
Outputs Field object data to a .vtk PolyData file for use with VTK or ParaView, if this field is also associated with a faces object.
Parameters
self
fileunit
aFaces
Definition at line 320 of file Field.f90.
subroutine, public fieldmodule::writefieldtovtkpointdata (type(field), intent(in) self, integer(kint), intent(in) fileunit)
Outputs Field object data to a .vtk PolyData file for use with VTK or ParaView.
Parameters
self
fileunit
Definition at line 285 of file Field.f90.
References numberkindsmodule::zero_tol.
Variable Documentation
type(logger) fieldmodule::log private
Definition at line 92 of file Field.f90.
logical(klog), save fieldmodule::loginit = .FALSE. private
Definition at line 91 of file Field.f90.
character(len=28), save fieldmodule::logkey = 'FieldLog' private
Definition at line 93 of file Field.f90.
integer(kint), parameter fieldmodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 94 of file Field.f90.
integer(kint) fieldmodule::field::n = 0 private
Number of field values stored (should be equal to the number of particles)
Definition at line 60 of file Field.f90.
integer(kint) fieldmodule::field::n_max = 0 private
maximum number of field values allowed in memory
Definition at line 61 of file Field.f90.
character(max_string_length) fieldmodule::field::name = "null" private
name of field variable
Definition at line 58 of file Field.f90.
integer(kint) fieldmodule::field::ndim = 0 private
dimension of field, 1 = scalar, >= 2 for vector fields
Definition at line 62 of file Field.f90.
real(kreal), dimension(:), allocatable fieldmodule::field::scalar private
Array to hold scalar field data.
Definition at line 54 of file Field.f90.
character(max_string_length) fieldmodule::field::units = "null" private
physical units of field variable
Definition at line 59 of file Field.f90.
real(kreal), dimension(:), allocatable fieldmodule::field::xcomp private
Array to hold the x-component of vector field data.
Definition at line 55 of file Field.f90.
real(kreal), dimension(:), allocatable fieldmodule::field::ycomp private
Array to hold the y-component of vector field data.
Definition at line 56 of file Field.f90.
real(kreal), dimension(:), allocatable fieldmodule::field::zcomp private
Array to hold the z-component of vector field data.
Definition at line 57 of file Field.f90.