LPM: Lagrangian Particle Methods: PolyMesh2d
PolyMesh2d
Each polygonal mesh is made up of Particles, Edges, and Faces.
Detailed Description
Each polygonal mesh is made up of Particles, Edges, and Faces.
Point-location queries are provided that use a tree search to accelerate a walk search.
Current implementation for planar meshes includes a mesh of quadrilateral faces from a square or a mesh of triangular faces from a hexagon, with free boundaries. Users choose the initial mesh from one of the predefined "seeds," defined to approximately cover the domain \(D = \{ (x,y) : x,y\in [-1,1] \} \), depending on the chosen seed. The seed is then multiplied by a user-supplied scalar maxR to cover larger subsets of the plane.
Implementations for spherical meshes include a mesh of quadrilaterals from the cubed sphere or a mesh of triangles from an icosahedral triangulation of the sphere. Users choose one of the spherical seeds (which discretize a unit sphere) and may choose a different radius.
The mesh seed is recursively refined until a user-supplied initial depth is achieved in the Faces quadtree. This refinement increases spatial resolution.
Adaptive refinement depends on the context of each problem and is handled by subclasses that include relevant Field objects for storing and handling physical data. These methods are provided in the Refinement module.
Some currently implemented mesh seeds are illustrated below.
Particles are drawn as circles and annotated by \(p_i\) where the subscript i indicates the index of that particle in the Particles structure.
Edges are illustrated as arrows \(e_i \) and Faces by \(F_i \).
Seeds are recursively refined by either facesmodule::dividetriface or facesmodule::dividequadface until a desired spatial resolution is achieved.
Seed for an initially square mesh of quadrilateral faces.
Seed for an initially hexagonal mesh of triangular faces.
Seed for a cubed sphere mesh of quadrilateral faces.
Seed for an icosahedral mesh of triangular faces on the sphere.
Data Types
interface polymesh2dmodule::new
interface polymesh2dmodule::delete
interface polymesh2dmodule::copy
interface polymesh2dmodule::logstats
interface polymesh2dmodule::printdebuginfo
Functions/Subroutines
final polymesh2dmodule::polymesh2d::deleteprivate
subroutine polymesh2dmodule::new::newprivate (self, meshSeed, initNest, maxNest, amrLimit, ampFactor)
Allocates memory for a new mesh (Particles, Edges, and Faces). Initializes a new mesh using a "mesh seed," which is recursively refined until a desired spatial resolution is achieved. The recursive refinement defines the Faces quadtree and the Edges binary tree.
subroutine polymesh2dmodule::delete::deleteprivate (self)
Deletes and frees memory associated with a PolyMesh2d object.
subroutine polymesh2dmodule::copy::copyprivate (self, other)
Peforms a deep copy of one mesh to another (all mesh components are deep copied). Both meshes must be allocated appropriately prior to calling this subroutine.
subroutine polymesh2dmodule::logstats::logstatsprivate (self, aLog)
Outputs basic mesh info to a Logger module object.
subroutine polymesh2dmodule::printdebuginfo::printdebugprivate (self)
Prints detailed mesh information to console. Used for debugging.
subroutine polymesh2dmodule::newprivate (self, meshSeed, initNest, maxNest, amrLimit, ampFactor)
Allocates memory for a new mesh (Particles, Edges, and Faces). Initializes a new mesh using a "mesh seed," which is recursively refined until a desired spatial resolution is achieved. The recursive refinement defines the Faces quadtree and the Edges binary tree.
subroutine polymesh2dmodule::deleteprivate (self)
Deletes and frees memory associated with a PolyMesh2d object.
subroutine polymesh2dmodule::copyprivate (self, other)
Peforms a deep copy of one mesh to another (all mesh components are deep copied). Both meshes must be allocated appropriately prior to calling this subroutine.
real(kreal) function, public polymesh2dmodule::maxlagrangianvariationperface (self)
Computes the maximum variation of the Lagrangian parameter over all faces in a mesh.
integer(kint) function, public polymesh2dmodule::locatefacecontainingpoint (self, queryPt)
Locates the face containing an arbitrary query point. This function assumes faces are convex polygons.
integer(kint) function, public polymesh2dmodule::nearestparticle (self, queryPt)
Finds the particle closest to an arbitrary query point.
subroutine, public polymesh2dmodule::ccwedgesaroundface (self, leafEdges, faceIndex)
Returns an STDIntVector containing indices of Edges around a face, listed in counter-clockwise order.
subroutine, public polymesh2dmodule::ccwverticesaroundface (self, verts, faceIndex)
Returns an STDIntVector containing indices of vertex Particles around a face, listed in counter-clockwise order.
subroutine, public polymesh2dmodule::projectparticlestosphere (self, radius)
Projects all particles in a mesh to the surface of a sphere with a user-specified radius.
logical(klog) function, public polymesh2dmodule::pointisoutsidemesh (self, xVec)
Returns .TRUE. if a query point is outside the boundaries of a planar mesh.
subroutine, public polymesh2dmodule::ccwadjacentfaces (self, adjFaces, faceIndex)
Returns an STDIntVector containing indices of Faces adjacent to a face, listed in counter-clockwise order.
subroutine, public polymesh2dmodule::ccwfacesaroundvertex (self, adjFaces, vertexIndex)
Returns an STDIntVector containing indices of Faces incident to a vertex, listed in counter-clockwise order.
integer(kint) function polymesh2dmodule::nearestrootface (self, queryPt)
Finds the nearest root face (faces included in the mesh seed, with no parents) to an arbitrary query point. Used to initialize a tree search of a Faces data structure.
integer(kint) function polymesh2dmodule::facekindfromseed (seed)
Determines the appropriate value of faceKind (as defined by NumberKinds) based on a specified mesh seed.
integer(kint) function polymesh2dmodule::geomkindfromseed (seed)
Determines the geometry (as defined by NumberKinds) based on a specified mesh seed.
recursive integer(kint) function polymesh2dmodule::locatepointtreesearch (self, queryPt, index)
Performs a tree search of a Faces object to locate the face containing a query point. Used to initialize a walk search.
recursive integer(kint) function polymesh2dmodule::locatepointwalksearch (self, queryPt, index)
Performs a walk search of a Faces object to locate the face containing a query point. Accelerated by using the output of a tree search for its first guess.
integer(kint) function polymesh2dmodule::nverticesinmesh (self, initNest)
Computes the number of vertices in a uniformly refined mesh. Used to compute memory allocation requirements.
integer(kint) function polymesh2dmodule::nfacesinmesh (self, initNest)
Computes the number of faces in a uniformly refined mesh. Used to compute memory allocation requirements.
integer(kint) function polymesh2dmodule::nedgesinmesh (self, nVertices, nFaces)
Uses the number of vertices and the number of faces (via Euler's formulas) to determine the the number of edges in a uniformly refined mesh. Used to compute memory allocation requirements.
subroutine polymesh2dmodule::initializemeshfromseed (self, ampFactor)
Initializes a mesh using a mesh seed .dat file to define the root set of Particles, Edges, and Faces. Mesh seeds are defined in both NumberKinds and via the corresponding .dat file. Multiplies particle postions by a specified amount to change the spatial domain (all mesh seeds approximately cover the unit sphere of their embedded space).
subroutine polymesh2dmodule::readseedfile (self, seedFilename, nParticles, nEdges, nFaces, seedXYZ, seedEdgeOrigs, seedEdgeDests, seedEdgeLefts, seedEdgeRights, seedFaceVerts, seedFaceEdges, seedVertexDegree)
Reads data from a mesh seed .dat file.
subroutine, public polymesh2dmodule::writemeshtomatlab (self, fileunit)
Writes a mesh to a Matlab-readable .m file.
subroutine polymesh2dmodule::logstatsprivate (self, aLog)
Outputs basic mesh info to a Logger module object.
subroutine, public polymesh2dmodule::writemeshtovtkpolydata (self, fileunit, title)
Outputs a mesh to a legacy formatted .vtk ASCII file. Does not output any Field data.
subroutine polymesh2dmodule::printdebugprivate (self)
Prints detailed mesh information to console. Used for debugging.
subroutine, public polymesh2dmodule::meshseedstring (seedString, msInt)
Converts the integer definitions of mesh seeds (from NumberKinds) to their corresponding strings.
subroutine polymesh2dmodule::initlogger (aLog, rank)
Initializes a logger for the Faces module.
Variables
type(particles) polymesh2dmodule::polymesh2d::particles
Particles defining the centers and vertices of each mesh face
type(edges) polymesh2dmodule::polymesh2d::edges
Edges connecting origin and destination particles for each edge, and each edge's left and right face
type(faces) polymesh2dmodule::polymesh2d::faces
Faces
integer(kint) polymesh2dmodule::polymesh2d::facekind = 0
face kind (e.g., triangular or quadrilateral) as defined in NumberKinds
integer(kint) polymesh2dmodule::polymesh2d::geomkind = 0
geometry kind (e.g., planar or spherical) as defined in NumberKinds
integer(kint) polymesh2dmodule::polymesh2d::meshseed = 0
mesh seed as defined in NumberKinds
integer(kint) polymesh2dmodule::polymesh2d::initnest = -1
initial refinement level (in terms of the Faces quadtree) for a mesh
integer(kint) polymesh2dmodule::polymesh2d::amrlimit = 0
Number of times a face may be divided beyond the initial refinement level.
real(kreal) polymesh2dmodule::polymesh2d::t = 0.0_kreal
time value represented by the mesh
logical(klog), save polymesh2dmodule::loginit = .FALSE.
type(logger) polymesh2dmodule::log
character(len=28), save polymesh2dmodule::logkey = 'PolyMesh2d'
integer(kint), parameter polymesh2dmodule::loglevel = TRACE_LOGGING_LEVEL
character(len=max_string_length) polymesh2dmodule::logstring
Function/Subroutine Documentation
subroutine, public polymesh2dmodule::ccwadjacentfaces (type(polymesh2d), intent(in) self, type(stdintvector), intent(out) adjFaces, integer(kint), intent(in) faceIndex)
Returns an STDIntVector containing indices of Faces adjacent to a face, listed in counter-clockwise order.
Parameters
[in] self Target mesh
[out] adjFaces list of adjacent faces, in CCW order
[in] faceIndex index to a face in Faces
Definition at line 463 of file PolyMesh2d.f90.
References polymesh2dmodule::ccwedgesaroundface(), and edgesmodule::positiveedge().
subroutine, public polymesh2dmodule::ccwedgesaroundface (type(polymesh2d), intent(in) self, type(stdintvector), intent(out) leafEdges, integer(kint), intent(in) faceIndex)
Returns an STDIntVector containing indices of Edges around a face, listed in counter-clockwise order.
Parameters
[in] self Target mesh
[out] leafEdges list of CCW edges around face
[in] faceIndex index to a face in Faces
Definition at line 328 of file PolyMesh2d.f90.
References edgesmodule::getleafedgesfromparent(), numberkindsmodule::quad_panel, and numberkindsmodule::tri_panel.
subroutine, public polymesh2dmodule::ccwfacesaroundvertex (type(polymesh2d), intent(in) self, type(stdintvector), intent(out) adjFaces, integer(kint), intent(in) vertexIndex)
Returns an STDIntVector containing indices of Faces incident to a vertex, listed in counter-clockwise order.
Todo:
Verify this subroutine works correctly
Parameters
[in] self Target mesh
[out] adjFaces list of adjacent faces, in CCW order
[in] vertexIndex index to a particle in Particles object
Definition at line 492 of file PolyMesh2d.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, and betaplanemeshmodule::logstring.
subroutine, public polymesh2dmodule::ccwverticesaroundface (type(polymesh2d), intent(in) self, type(stdintvector), intent(out) verts, integer(kint), intent(in) faceIndex)
Returns an STDIntVector containing indices of vertex Particles around a face, listed in counter-clockwise order.
Parameters
[in] self Target mesh
[out] verts list of vertices around face, in CCW order
[in] faceIndex index to a face in Faces
Definition at line 361 of file PolyMesh2d.f90.
References polymesh2dmodule::ccwedgesaroundface(), and edgesmodule::positiveedge().
subroutine polymesh2dmodule::copyprivate (type(polymesh2d), intent(inout) self, type(polymesh2d), intent(in) other) private
Peforms a deep copy of one mesh to another (all mesh components are deep copied). Both meshes must be allocated appropriately prior to calling this subroutine.
Parameters
[in,out] self Target mesh
[in] other Source mesh
Definition at line 207 of file PolyMesh2d.f90.
subroutine polymesh2dmodule::copy::copyprivate (type(polymesh2d), intent(inout) self, type(polymesh2d), intent(in) other) private
Peforms a deep copy of one mesh to another (all mesh components are deep copied). Both meshes must be allocated appropriately prior to calling this subroutine.
Parameters
[in,out] self Target mesh
[in] other Source mesh
Definition at line 207 of file PolyMesh2d.f90.
subroutine polymesh2dmodule::deleteprivate (type(polymesh2d), intent(inout) self) private
Deletes and frees memory associated with a PolyMesh2d object.
Parameters
[in,out] self Target mesh
Definition at line 191 of file PolyMesh2d.f90.
final polymesh2dmodule::polymesh2d::deleteprivate () final private
Definition at line 88 of file PolyMesh2d.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine polymesh2dmodule::delete::deleteprivate (type(polymesh2d), intent(inout) self) private
Deletes and frees memory associated with a PolyMesh2d object.
Parameters
[in,out] self Target mesh
Definition at line 191 of file PolyMesh2d.f90.
integer(kint) function polymesh2dmodule::facekindfromseed (integer(kint), intent(in) seed) private
Determines the appropriate value of faceKind (as defined by NumberKinds) based on a specified mesh seed.
Parameters
[in] seed as defined in NumberKinds
Returns
faceKind as defined in NumberKinds
Definition at line 575 of file PolyMesh2d.f90.
References numberkindsmodule::beta_plane_seed, numberkindsmodule::cubed_sphere_seed, numberkindsmodule::icos_tri_sphere_seed, numberkindsmodule::polar_disc_seed, numberkindsmodule::quad_panel, numberkindsmodule::quad_rect_periodic_seed, numberkindsmodule::quad_rect_seed, numberkindsmodule::tri_hex_seed, and numberkindsmodule::tri_panel.
integer(kint) function polymesh2dmodule::geomkindfromseed (integer(kint), intent(in) seed) private
Determines the geometry (as defined by NumberKinds) based on a specified mesh seed.
Parameters
[in] seed as defined in NumberKinds
Returns
geomKind as defined in NumberKinds
Definition at line 590 of file PolyMesh2d.f90.
References numberkindsmodule::beta_plane_seed, numberkindsmodule::cubed_sphere_seed, numberkindsmodule::icos_tri_sphere_seed, numberkindsmodule::planar_geom, numberkindsmodule::polar_disc_seed, numberkindsmodule::quad_rect_periodic_seed, numberkindsmodule::quad_rect_seed, numberkindsmodule::sphere_geom, and numberkindsmodule::tri_hex_seed.
subroutine polymesh2dmodule::initializemeshfromseed (type(polymesh2d), intent(inout) self, real(kreal), intent(in) ampFactor) private
Initializes a mesh using a mesh seed .dat file to define the root set of Particles, Edges, and Faces. Mesh seeds are defined in both NumberKinds and via the corresponding .dat file. Multiplies particle postions by a specified amount to change the spatial domain (all mesh seeds approximately cover the unit sphere of their embedded space).
Parameters
[in,out] self Target mesh to be initialized
[in] ampFactor
Definition at line 787 of file PolyMesh2d.f90.
References numberkindsmodule::beta_plane_seed, numberkindsmodule::cubed_sphere_seed, loggermodule::error_logging_level, numberkindsmodule::icos_tri_sphere_seed, edgesmodule::insertedge(), facesmodule::insertface(), particlesmodule::insertparticle(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, particlesmodule::makeparticleactive(), numberkindsmodule::polar_disc_seed, numberkindsmodule::quad_panel, numberkindsmodule::quad_rect_periodic_seed, numberkindsmodule::quad_rect_seed, facesmodule::quadfacearea(), polymesh2dmodule::readseedfile(), particlesmodule::sortincidentedgesatparticle(), spheregeommodule::spheretricenter(), numberkindsmodule::tri_hex_seed, numberkindsmodule::tri_panel, facesmodule::trifacearea(), and loggermodule::warning_logging_level.
subroutine polymesh2dmodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the Faces module.
Output is controlled both by message priority and by MPI Rank
Parameters
[out] aLog Target Logger object
[in] rank Rank of this processor
Definition at line 1149 of file PolyMesh2d.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
integer(kint) function, public polymesh2dmodule::locatefacecontainingpoint (type(polymesh2d), intent(in) self, real(kreal), dimension(:), intent(in) queryPt)
Locates the face containing an arbitrary query point. This function assumes faces are convex polygons.
Todo:
This function should handle points outside the mesh appropriately.
Parameters
[in] self Target mesh
[in] queryPt point in the spatial domain
Returns
Integer index of face (in a Faces object) containing the query point.
Definition at line 265 of file PolyMesh2d.f90.
References loggermodule::error_logging_level, polymesh2dmodule::locatepointtreesearch(), polymesh2dmodule::locatepointwalksearch(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, and polymesh2dmodule::nearestrootface().
recursive integer(kint) function polymesh2dmodule::locatepointtreesearch (type(polymesh2d), intent(in) self, real(kreal), dimension(:), intent(in) queryPt, integer(kint), intent(in) index) private
Performs a tree search of a Faces object to locate the face containing a query point. Used to initialize a walk search.
Parameters
[in] self Target mesh
[in] queryPt position vector of query point
[in] index index (to Faces) to start search
Returns
faceIndex index of face containing query point, as determined by a tree search. Note that child particles may move outside the boundaries of their parent faces, so this result may sometimes be incorrect. A walk search provides the correct result always.
Definition at line 610 of file PolyMesh2d.f90.
References facesmodule::facecentroid(), and numberkindsmodule::sphere_geom.
recursive integer(kint) function polymesh2dmodule::locatepointwalksearch (type(polymesh2d), intent(in) self, real(kreal), dimension(:), intent(in) queryPt, integer(kint), intent(in) index) private
Performs a walk search of a Faces object to locate the face containing a query point. Accelerated by using the output of a tree search for its first guess.
Parameters
[in] self Target mesh
[in] queryPt position vector of query point
[in] index index (to Faces) to start search
Returns
faceIndex index of face containing query point
Definition at line 652 of file PolyMesh2d.f90.
References polymesh2dmodule::ccwadjacentfaces(), loggermodule::error_logging_level, facesmodule::facecentroid(), betaplanemeshmodule::log, betaplanemeshmodule::logkey, and numberkindsmodule::sphere_geom.
subroutine polymesh2dmodule::logstatsprivate (type(polymesh2d), intent(in) self, type(logger), intent(inout) aLog) private
Outputs basic mesh info to a Logger module object.
Parameters
[in] self Target mesh
[in,out] aLog logger
Definition at line 1053 of file PolyMesh2d.f90.
References edgesmodule::avgedgelength(), numberkindsmodule::euclidean_3d, betaplanemeshmodule::logkey, betaplanemeshmodule::logstring, edgesmodule::maxedgelength(), polymesh2dmodule::meshseedstring(), edgesmodule::minedgelength(), numberkindsmodule::planar_geom, numberkindsmodule::sphere_geom, and loggermodule::trace_logging_level.
subroutine polymesh2dmodule::logstats::logstatsprivate (type(polymesh2d), intent(in) self, type(logger), intent(inout) aLog) private
Outputs basic mesh info to a Logger module object.
Parameters
[in] self Target mesh
[in,out] aLog logger
Definition at line 1053 of file PolyMesh2d.f90.
real(kreal) function, public polymesh2dmodule::maxlagrangianvariationperface (type(polymesh2d), intent(in) self)
Computes the maximum variation of the Lagrangian parameter over all faces in a mesh.
Parameters
[in] self Target mesh
Returns
Maximum over all faces of the variation of the Lagrangian parameter per face
Definition at line 223 of file PolyMesh2d.f90.
References particlesmodule::lagcoord().
subroutine, public polymesh2dmodule::meshseedstring (character(len=*), intent(inout) seedString, integer(kint), intent(in) msInt)
Converts the integer definitions of mesh seeds (from NumberKinds) to their corresponding strings.
Parameters
[out] seedString
[in] msInt mesh seed integer
Definition at line 1121 of file PolyMesh2d.f90.
References numberkindsmodule::beta_plane_seed, numberkindsmodule::cubed_sphere_seed, numberkindsmodule::icos_tri_sphere_seed, numberkindsmodule::polar_disc_seed, numberkindsmodule::quad_rect_periodic_seed, numberkindsmodule::quad_rect_seed, and numberkindsmodule::tri_hex_seed.
integer(kint) function, public polymesh2dmodule::nearestparticle (type(polymesh2d), intent(in) self, real(kreal), dimension(:), intent(in) queryPt)
Finds the particle closest to an arbitrary query point.
Todo:
This function should handle points outside the mesh appropriately.
Parameters
[in] self Target mesh
[in] queryPt point in the spatial domain
Returns
Integer index of particle (in a Particles object) closest to the query point.
Definition at line 288 of file PolyMesh2d.f90.
References polymesh2dmodule::ccwverticesaroundface(), spheregeommodule::chorddistance(), polymesh2dmodule::locatefacecontainingpoint(), particlesmodule::physcoord(), and numberkindsmodule::sphere_geom.
integer(kint) function polymesh2dmodule::nearestrootface (type(polymesh2d), intent(in) self, real(kreal), dimension(:), intent(in) queryPt) private
Finds the nearest root face (faces included in the mesh seed, with no parents) to an arbitrary query point. Used to initialize a tree search of a Faces data structure.
Parameters
[in] self Target mesh
[in] queryPt position vector of query point
Returns
Index to Faces of nearest root face
Definition at line 527 of file PolyMesh2d.f90.
References numberkindsmodule::beta_plane_seed, numberkindsmodule::cubed_sphere_seed, facesmodule::facecentroid(), numberkindsmodule::icos_tri_sphere_seed, numberkindsmodule::polar_disc_seed, numberkindsmodule::quad_rect_periodic_seed, numberkindsmodule::quad_rect_seed, numberkindsmodule::sphere_geom, and numberkindsmodule::tri_hex_seed.
integer(kint) function polymesh2dmodule::nedgesinmesh (type(polymesh2d), intent(in) self, integer(kint), intent(in) nVertices, integer(kint), intent(in) nFaces) private
Uses the number of vertices and the number of faces (via Euler's formulas) to determine the the number of edges in a uniformly refined mesh. Used to compute memory allocation requirements.
Parameters
[in] self Target mesh
[in] nVertices number of vertices in a mesh
[in] nFaces number of faces in a mesh
Returns
Number of edges in a mesh
Definition at line 766 of file PolyMesh2d.f90.
References numberkindsmodule::planar_geom, and numberkindsmodule::sphere_geom.
subroutine polymesh2dmodule::newprivate (type(polymesh2d), intent(out) self, integer(kint), intent(in) meshSeed, integer(kint), intent(in) initNest, integer(kint), intent(in) maxNest, integer(kint), intent(in) amrLimit, real(kreal), intent(in) ampFactor) private
Allocates memory for a new mesh (Particles, Edges, and Faces). Initializes a new mesh using a "mesh seed," which is recursively refined until a desired spatial resolution is achieved. The recursive refinement defines the Faces quadtree and the Edges binary tree.
Definition at line 127 of file PolyMesh2d.f90.
References numberkindsmodule::beta_plane_seed, facesmodule::dividequadface(), facesmodule::dividetriface(), loggermodule::error_logging_level, polymesh2dmodule::facekindfromseed(), polymesh2dmodule::geomkindfromseed(), polymesh2dmodule::initializemeshfromseed(), initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, polymesh2dmodule::nedgesinmesh(), polymesh2dmodule::nfacesinmesh(), polymesh2dmodule::nverticesinmesh(), numberkindsmodule::procrank, numberkindsmodule::quad_panel, particlesmodule::sortincidentedgesatparticle(), numberkindsmodule::tri_hex_seed, and numberkindsmodule::tri_panel.
subroutine polymesh2dmodule::new::newprivate (type(polymesh2d), intent(out) self, integer(kint), intent(in) meshSeed, integer(kint), intent(in) initNest, integer(kint), intent(in) maxNest, integer(kint), intent(in) amrLimit, real(kreal), intent(in) ampFactor) private
Allocates memory for a new mesh (Particles, Edges, and Faces). Initializes a new mesh using a "mesh seed," which is recursively refined until a desired spatial resolution is achieved. The recursive refinement defines the Faces quadtree and the Edges binary tree.
Definition at line 127 of file PolyMesh2d.f90.
integer(kint) function polymesh2dmodule::nfacesinmesh (type(polymesh2d), intent(in) self, integer(kint), intent(in) initNest) private
Computes the number of faces in a uniformly refined mesh. Used to compute memory allocation requirements.
Parameters
[in] self Target mesh
[in] initNest initial refinement level
Returns
Number of faces in a mesh
Definition at line 742 of file PolyMesh2d.f90.
References numberkindsmodule::beta_plane_seed, numberkindsmodule::cubed_sphere_seed, numberkindsmodule::icos_tri_sphere_seed, numberkindsmodule::quad_rect_periodic_seed, numberkindsmodule::quad_rect_seed, and numberkindsmodule::tri_hex_seed.
integer(kint) function polymesh2dmodule::nverticesinmesh (type(polymesh2d), intent(in) self, integer(kint), intent(in) initNest) private
Computes the number of vertices in a uniformly refined mesh. Used to compute memory allocation requirements.
Parameters
[in] self Target mesh
[in] initNest initial refinement level
Returns
Number of vertices in a mesh
Definition at line 709 of file PolyMesh2d.f90.
References numberkindsmodule::beta_plane_seed, numberkindsmodule::cubed_sphere_seed, numberkindsmodule::icos_tri_sphere_seed, numberkindsmodule::quad_rect_periodic_seed, numberkindsmodule::quad_rect_seed, and numberkindsmodule::tri_hex_seed.
logical(klog) function, public polymesh2dmodule::pointisoutsidemesh (type(polymesh2d), intent(in) self, real(kreal), dimension(:), intent(in) xVec)
Returns .TRUE. if a query point is outside the boundaries of a planar mesh.
Parameters
[in] self Target mesh
[in] xVec position vector of query point
Returns
.TRUE. if query point is outside mesh boundaries
Definition at line 412 of file PolyMesh2d.f90.
References polymesh2dmodule::ccwedgesaroundface(), facesmodule::facecentroid(), polymesh2dmodule::locatefacecontainingpoint(), edgesmodule::onboundary(), and particlesmodule::physcoord().
subroutine polymesh2dmodule::printdebugprivate (type(polymesh2d), intent(in) self) private
Prints detailed mesh information to console. Used for debugging.
Parameters
[in] self Target mesh
Definition at line 1106 of file PolyMesh2d.f90.
References stdintvectormodule::stdintvector::print().
subroutine polymesh2dmodule::printdebuginfo::printdebugprivate (type(polymesh2d), intent(in) self) private
Prints detailed mesh information to console. Used for debugging.
Parameters
[in] self Target mesh
Definition at line 1106 of file PolyMesh2d.f90.
subroutine, public polymesh2dmodule::projectparticlestosphere (type(polymesh2d), intent(inout) self, real(kreal), intent(in) radius)
Projects all particles in a mesh to the surface of a sphere with a user-specified radius.
Parameters
[in,out] self Target mesh
[in] radius radius of sphere
Definition at line 387 of file PolyMesh2d.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, and numberkindsmodule::sphere_geom.
subroutine polymesh2dmodule::readseedfile (type(polymesh2d), intent(in) self, character(len=*), intent(in) seedFilename, integer(kint), intent(in) nParticles, integer(kint), intent(in) nEdges, integer(kint), intent(in) nFaces, real(kreal), dimension(3,nparticles), intent(out) seedXYZ, integer(kint), dimension(nedges), intent(out) seedEdgeOrigs, integer(kint), dimension(nedges), intent(out) seedEdgeDests, integer(kint), dimension(nedges), intent(out) seedEdgeLefts, integer(kint), dimension(nedges), intent(out) seedEdgeRights, integer(kint), dimension(:,:), intent(inout) seedFaceVerts, integer(kint), dimension(:,:), intent(inout) seedFaceEdges, integer(kint), dimension(nparticles - nfaces), intent(out) seedVertexDegree) private
Reads data from a mesh seed .dat file.
Parameters
[in] self Target mesh
[in] seedFilename filename of .dat file
[in] nParticles number of particles in mesh seed
[in] nEdges number of edges in mesh seed
[in] nFaces number of faces in mesh seed
[out] seedXYZ position vectors of mesh seed particles
[out] seedEdgeOrigs indices of origin particles for each edge
[out] seedEdgeDests indices of destination particles for each edge
[out] seedEdgeLefts indices of left faces for each edge
[out] seedEdgeRights indices of right faces for each edge
[out] seedFaceVerts indices of vertex particles for each face
[out] seedFaceEdges indices of edges for each face
[out] seedVertexDegree degree (number of incident edges) of each vertex in mesh seed
Definition at line 948 of file PolyMesh2d.f90.
References loggermodule::error_logging_level, numberkindsmodule::icos_tri_sphere_seed, betaplanemeshmodule::log, betaplanemeshmodule::logkey, numberkindsmodule::planar_geom, numberkindsmodule::quad_panel, numberkindsmodule::read_unit, and numberkindsmodule::tri_panel.
subroutine, public polymesh2dmodule::writemeshtomatlab (type(polymesh2d), intent(in) self, integer(kint), intent(in) fileunit)
Writes a mesh to a Matlab-readable .m file.
Parameters
[in] self Mesh to output
[in] fileunit Integer unit of .m file
Definition at line 1041 of file PolyMesh2d.f90.
References edgesmodule::writeedgestomatlab(), facesmodule::writefacestomatlab(), and particlesmodule::writeparticlestomatlab().
subroutine, public polymesh2dmodule::writemeshtovtkpolydata (type(polymesh2d), intent(in) self, integer(kint), intent(in) fileunit, character(len=*), intent(in), optional title)
Outputs a mesh to a legacy formatted .vtk ASCII file. Does not output any Field data.
Parameters
[in] self Target mesh
[in] fileunit Integer unit of .vtk file
[in] title Optional title for vtk output
Definition at line 1085 of file PolyMesh2d.f90.
References facesmodule::writefaceareatovtkcelldata(), facesmodule::writefacestovtkpolygons(), particlesmodule::writevtklagcoords(), outputwritermodule::writevtkpointdatasectionheader(), and particlesmodule::writevtkpoints().
Variable Documentation
integer(kint) polymesh2dmodule::polymesh2d::amrlimit = 0 private
Number of times a face may be divided beyond the initial refinement level.
Definition at line 84 of file PolyMesh2d.f90.
type(edges) polymesh2dmodule::polymesh2d::edges private
Edges connecting origin and destination particles for each edge, and each edge's left and right face
Definition at line 78 of file PolyMesh2d.f90.
integer(kint) polymesh2dmodule::polymesh2d::facekind = 0 private
face kind (e.g., triangular or quadrilateral) as defined in NumberKinds
Definition at line 80 of file PolyMesh2d.f90.
type(faces) polymesh2dmodule::polymesh2d::faces private
Faces
Definition at line 79 of file PolyMesh2d.f90.
integer(kint) polymesh2dmodule::polymesh2d::geomkind = 0 private
geometry kind (e.g., planar or spherical) as defined in NumberKinds
Definition at line 81 of file PolyMesh2d.f90.
integer(kint) polymesh2dmodule::polymesh2d::initnest = -1 private
initial refinement level (in terms of the Faces quadtree) for a mesh
Definition at line 83 of file PolyMesh2d.f90.
type(logger) polymesh2dmodule::log private
Definition at line 117 of file PolyMesh2d.f90.
logical(klog), save polymesh2dmodule::loginit = .FALSE. private
Definition at line 116 of file PolyMesh2d.f90.
character(len=28), save polymesh2dmodule::logkey = 'PolyMesh2d' private
Definition at line 118 of file PolyMesh2d.f90.
integer(kint), parameter polymesh2dmodule::loglevel = TRACE_LOGGING_LEVEL private
Definition at line 119 of file PolyMesh2d.f90.
character(len=max_string_length) polymesh2dmodule::logstring private
Definition at line 120 of file PolyMesh2d.f90.
integer(kint) polymesh2dmodule::polymesh2d::meshseed = 0 private
mesh seed as defined in NumberKinds
Definition at line 82 of file PolyMesh2d.f90.
type(particles) polymesh2dmodule::polymesh2d::particles private
Particles defining the centers and vertices of each mesh face
Definition at line 77 of file PolyMesh2d.f90.
real(kreal) polymesh2dmodule::polymesh2d::t = 0.0_kreal private
time value represented by the mesh
Definition at line 85 of file PolyMesh2d.f90.