LPM: Lagrangian Particle Methods: Spherical Geometry
Spherical Geometry
defines functions for performing geometric calculations on the surface of a sphere.
Detailed Description
defines functions for performing geometric calculations on the surface of a sphere.
Author
Peter Bosler, Department of Mathematics, University of Michigan
Functions/Subroutines
pure real(kreal) function spheregeommodule::chorddistance (xyzA, xyzB)
Euclidean distance between two points on the sphere.
pure real(kreal) function spheregeommodule::spheredistancevector (xyzA, xyzB)
Great-circle distance between two points on the sphere.
pure real(kreal) function spheregeommodule::spheredistancecomponents (xA, yA, zA, xB, yB, zB)
Great-circle distance between two points on the sphere.
pure real(kreal) function spheregeommodule::spherearclengthvector (xyzA, xyzB)
Central angle between two points on the sphere.
pure real(kreal) function spheregeommodule::spherearclengthcomponents (xA, yA, zA, xB, yB, zB)
central angle between two points on the sphere
pure real(kreal) function,
dimension(3) spheregeommodule::latunitvector (xyz)
Constructs the latitudinal unit vector at a point on the sphere.
pure real(kreal) function,
dimension(3) spheregeommodule::lonunitvector (xyz)
Constructs the Longitudinal unit vector at a point on the sphere.
pure real(kreal) function,
dimension(3) spheregeommodule::spheremidpoint (xyzA, xyzB)
midpoint of a great-circle segment connecting two points on the sphere
pure real(kreal) function,
dimension(3) spheregeommodule::spheretricenter (xyzA, xyzB, xyzC)
Finds the centroid of a spherical triangle defined by three vertices.
pure real(kreal) function,
dimension(3) spheregeommodule::spherequadcenter (xyzA, xyzB, xyzC, xyzD)
Finds the centroid of a spherical quadrilateral defined by four vertices.
pure real(kreal) function spheregeommodule::spheretriareavector (xyzA, xyzB, xyzC)
Finds the area of a spherical triangle defined by three vertices.
pure real(kreal) function spheregeommodule::spheretriareacomponents (xa, ya, za, xb, yb, zb, xc, yc, zc)
Finds the area of a spherical triangle defined by three vertices.
pure real(kreal) function spheregeommodule::planetriarea (xyzA, xyzB, xyzC)
Finds the area of a planar triangle defined by three vertices.
pure real(kreal) function spheregeommodule::longitudevector (xyz)
Finds the longitude of a point on the sphere.
pure real(kreal) function spheregeommodule::longitudecomponents (x, y, z)
Finds the longitude of a point on the sphere.
pure real(kreal) function spheregeommodule::longitudecomponents2 (x, y)
Finds the longitude of a point on the sphere.
pure real(kreal) function spheregeommodule::latitudevector (xyz)
Finds the latitude of a point on the sphere.
pure real(kreal) function spheregeommodule::latitudecomponents (x, y, z)
Finds the latitude of a point on the sphere.
pure real(kreal) function spheregeommodule::atan4 (y, x)
A 4-quadrant inverse tangent function with range 0 to 2*pi instead of -pi to pi.
pure real(kreal) function spheregeommodule::crossmagnitude (xyzA, xyzB)
Magnitude of the vector xyzA X xyzB.
pure real(kreal) function,
dimension(3) spheregeommodule::crossproduct (xyzA, xyzB)
Computes a vector cross product.
pure real(kreal) function spheregeommodule::determinant (xA, xB, xC)
Computes a vector triple product.
real(kreal) function, dimension(3) spheregeommodule::randomspherepoint ()
Generates a random point on the surface of a sphere.
Function/Subroutine Documentation
pure real(kreal) function spheregeommodule::atan4 (real(kreal), intent(in) y, real(kreal), intent(in) x)
A 4-quadrant inverse tangent function with range 0 to 2*pi instead of -pi to pi.
Author
Peter Bosler
Parameters
[in] y double precision real
[in] x double precision real
Returns
atan(y/x) in range 0 to 2*pi
Definition at line 491 of file SphereGeometry.f90.
References numberkindsmodule::pi.
pure real(kreal) function spheregeommodule::chorddistance (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Euclidean distance between two points on the sphere.
Author
Peter Bosler
Parameters
[in] xyzA double precision real size(3); vector on the sphere
[in] xyzB double precision real size(3); vector on the sphere
Returns
Distance double precision real, straight-line distance between xyzA and xyzB
Definition at line 66 of file SphereGeometry.f90.
pure real(kreal) function spheregeommodule::crossmagnitude (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Magnitude of the vector xyzA X xyzB.
Author
Peter Bosler
Parameters
[in] xyzA double precision real size(3)
[in] xyzB double precision real size(3)
Returns
|xyzA x xyzB|
Definition at line 555 of file SphereGeometry.f90.
pure real(kreal) function, dimension(3) spheregeommodule::crossproduct (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Computes a vector cross product.
Author
Peter Bosler
Parameters
[in] xyzA double precision real size(3)
[in] xyzB double precision real size(3)
Returns
xyzA x xyzB double precision real size(3)
Definition at line 574 of file SphereGeometry.f90.
pure real(kreal) function spheregeommodule::determinant (real(kreal), dimension(3), intent(in) xA, real(kreal), dimension(3), intent(in) xB, real(kreal), dimension(3), intent(in) xC)
Computes a vector triple product.
Author
Peter Bosler
Parameters
[in] xA double precision real size(3)
[in] xB double precision real size(3)
[in] xC double precision real size(3)
Returns
\(x_A \cdot (x_b \times x_c) \) double precision real size(3)
Definition at line 594 of file SphereGeometry.f90.
References spheregeommodule::crossproduct().
pure real(kreal) function spheregeommodule::latitudecomponents (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Finds the latitude of a point on the sphere.
Author
Peter Bosler
Parameters
[in] x
[in] y
[in] z
Returns
Latitude of xyz
Definition at line 476 of file SphereGeometry.f90.
pure real(kreal) function spheregeommodule::latitudevector (real(kreal), dimension(3), intent(in) xyz)
Finds the latitude of a point on the sphere.
Author
Peter Bosler
Parameters
[in] xyz double precision real size(3); vector on the sphere in Cartesian coordinates
Returns
Latitude of xyz
Definition at line 458 of file SphereGeometry.f90.
pure real(kreal) function, dimension(3) spheregeommodule::latunitvector (real(kreal), dimension(3), intent(in) xyz)
Constructs the latitudinal unit vector at a point on the sphere.
Author
Peter Bosler
Parameters
[in] xyz double precision real size(3); vector on the sphere
Returns
northward-pointing unit vector at position xyz
Definition at line 207 of file SphereGeometry.f90.
pure real(kreal) function spheregeommodule::longitudecomponents (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Finds the longitude of a point on the sphere.
Author
Peter Bosler
Parameters
[in] x
[in] y
[in] z
Returns
Longitude of xyz
Definition at line 427 of file SphereGeometry.f90.
References spheregeommodule::atan4().
pure real(kreal) function spheregeommodule::longitudecomponents2 (real(kreal), intent(in) x, real(kreal), intent(in) y)
Finds the longitude of a point on the sphere.
Author
Peter Bosler
Parameters
[in] x
[in] y
Returns
Longitude
Definition at line 443 of file SphereGeometry.f90.
References spheregeommodule::atan4().
pure real(kreal) function spheregeommodule::longitudevector (real(kreal), dimension(3), intent(in) xyz)
Finds the longitude of a point on the sphere.
Author
Peter Bosler
Parameters
[in] xyz double precision real size(3); vector on the sphere in Cartesian coordinates
Returns
Longitude of xyz
Definition at line 409 of file SphereGeometry.f90.
References spheregeommodule::atan4().
pure real(kreal) function, dimension(3) spheregeommodule::lonunitvector (real(kreal), dimension(3), intent(in) xyz)
Constructs the Longitudinal unit vector at a point on the sphere.
Author
Peter Bosler
Parameters
[in] xyz double precision real size(3); vector on the sphere
Returns
eastward-pointing unit vector at position xyz
Definition at line 232 of file SphereGeometry.f90.
pure real(kreal) function spheregeommodule::planetriarea (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB, real(kreal), dimension(3), intent(in) xyzC)
Finds the area of a planar triangle defined by three vertices.
Author
Peter Bosler
Parameters
[in] xyzA double precision real size(3); vector on the sphere
[in] xyzB double precision real size(3); vector on the sphere
[in] xyzC double precision real size(3); vector on the sphere
Returns
scalar area
Definition at line 393 of file SphereGeometry.f90.
References spheregeommodule::crossmagnitude().
real(kreal) function, dimension(3) spheregeommodule::randomspherepoint ()
Generates a random point on the surface of a sphere.
Author
Peter Bosler
Returns
random vector satisfying x^2 + y^2 + z^2 = R^2
Definition at line 613 of file SphereGeometry.f90.
References numberkindsmodule::sphereradius.
pure real(kreal) function spheregeommodule::spherearclengthcomponents (real(kreal), intent(in) xA, real(kreal), intent(in) yA, real(kreal), intent(in) zA, real(kreal), intent(in) xB, real(kreal), intent(in) yB, real(kreal), intent(in) zB)
central angle between two points on the sphere
Author
Peter Bosler
Parameters
[in] xA double precision real
[in] yA double precision real
[in] zA
[in] xB
[in] yB
[in] zB
Returns
Distance double precision real, angular separation between xyzA and xyzB
Definition at line 180 of file SphereGeometry.f90.
pure real(kreal) function spheregeommodule::spherearclengthvector (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Central angle between two points on the sphere.
Author
Peter Bosler
Parameters
[in] xyzA double precision real size(3); vector on the sphere
[in] xyzB double precision real size(3); vector on the sphere
Returns
Distance double precision real, angular separation between xyzA and xyzB
Definition at line 146 of file SphereGeometry.f90.
pure real(kreal) function spheregeommodule::spheredistancecomponents (real(kreal), intent(in) xA, real(kreal), intent(in) yA, real(kreal), intent(in) zA, real(kreal), intent(in) xB, real(kreal), intent(in) yB, real(kreal), intent(in) zB)
Great-circle distance between two points on the sphere.
Author
Peter Bosler
Parameters
xA
yA
zA
xB
yB
zB
Returns
Distance great-circle distance between (xA, yA, zA) and (xB, yB, zB)
Definition at line 119 of file SphereGeometry.f90.
References numberkindsmodule::sphereradius.
pure real(kreal) function spheregeommodule::spheredistancevector (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Great-circle distance between two points on the sphere.
Author
Peter Bosler
Parameters
[in] xyzA double precision real size(3); vector on the sphere
[in] xyzB double precision real size(3); vector on the sphere
Returns
Distance double precision real, great-circle distance between xyzA and xyzB
Definition at line 85 of file SphereGeometry.f90.
References numberkindsmodule::sphereradius.
pure real(kreal) function, dimension(3) spheregeommodule::spheremidpoint (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
midpoint of a great-circle segment connecting two points on the sphere
Author
Peter Bosler
Parameters
[in] xyzA double precision real size(3); vector on the sphere
[in] xyzB double precision real size(3); vector on the sphere
Returns
Midpoint vector
Definition at line 258 of file SphereGeometry.f90.
References numberkindsmodule::sphereradius.
pure real(kreal) function, dimension(3) spheregeommodule::spherequadcenter (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB, real(kreal), dimension(3), intent(in) xyzC, real(kreal), dimension(3), intent(in) xyzD)
Finds the centroid of a spherical quadrilateral defined by four vertices.
Author
Peter Bosler
Parameters
[in] xyzA double precision real size(3); vector on the sphere
[in] xyzB double precision real size(3); vector on the sphere
[in] xyzC double precision real size(3); vector on the sphere
[in] xyzD double precision real size(3); vector on the sphere
Returns
centroid vector
Definition at line 303 of file SphereGeometry.f90.
References numberkindsmodule::sphereradius.
pure real(kreal) function spheregeommodule::spheretriareacomponents (real(kreal), intent(in) xa, real(kreal), intent(in) ya, real(kreal), intent(in) za, real(kreal), intent(in) xb, real(kreal), intent(in) yb, real(kreal), intent(in) zb, real(kreal), intent(in) xc, real(kreal), intent(in) yc, real(kreal), intent(in) zc)
Finds the area of a spherical triangle defined by three vertices.
Author
Peter Bosler
Parameters
[in] xA double precision real
[in] yA double precision real
[in] zA
[in] xB
[in] yB
[in] zB
[in] xC
[in] yC
[in] zC
Returns
scalar area
Definition at line 363 of file SphereGeometry.f90.
References spheregeommodule::spherearclength::spherearclengthcomponents(), and numberkindsmodule::sphereradius.
pure real(kreal) function spheregeommodule::spheretriareavector (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB, real(kreal), dimension(3), intent(in) xyzC)
Finds the area of a spherical triangle defined by three vertices.
Author
Peter Bosler
Parameters
[in] xyzA double precision real size(3); vector on the sphere
[in] xyzB double precision real size(3); vector on the sphere
[in] xyzC double precision real size(3); vector on the sphere
Returns
scalar area
Definition at line 325 of file SphereGeometry.f90.
References numberkindsmodule::sphereradius.
pure real(kreal) function, dimension(3) spheregeommodule::spheretricenter (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB, real(kreal), dimension(3), intent(in) xyzC)
Finds the centroid of a spherical triangle defined by three vertices.
Author
Peter Bosler
Parameters
[in] xyzA double precision real size(3); vector on the sphere
[in] xyzB double precision real size(3); vector on the sphere
[in] xyzC double precision real size(3); vector on the sphere
Returns
centroid vector
Definition at line 280 of file SphereGeometry.f90.
References numberkindsmodule::sphereradius.