LPM: Lagrangian Particle Methods: BetaPlaneSolver
BetaPlaneSolver
Data structure for integrating a planar incompressible flow with rotation forward in time using a fourth-order Runge-Kutta method.
Detailed Description
Data structure for integrating a planar incompressible flow with rotation forward in time using a fourth-order Runge-Kutta method.
Data Types
interface betaplanesolvermodule::new
interface betaplanesolvermodule::delete
interface betaplanesolvermodule::timestep
Functions/Subroutines
final betaplanesolvermodule::betaplanesolver::deleteprivate
subroutine betaplanesolvermodule::new::newprivate (self, betaPlane)
subroutine betaplanesolvermodule::delete::deleteprivate (self)
subroutine betaplanesolvermodule::timestep::timestepprivate (self, betaPlane, dt)
subroutine betaplanesolvermodule::newprivate (self, betaPlane)
subroutine betaplanesolvermodule::deleteprivate (self)
subroutine betaplanesolvermodule::timestepprivate (self, betaPlane, dt)
subroutine betaplanesolvermodule::betaplanevelocity (u, v, x, y, relVortIn, areaIn, activemask, mpiParticles)
subroutine betaplanesolvermodule::initlogger (aLog, rank)
Variables
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::xin => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::xstage1 => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::xstage2 => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::xstage3 => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::xstage4 => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::yin => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::ystage1 => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::ystage2 => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::ystage3 => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::ystage4 => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::relvortin => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::relvortstage1 => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::relvortstage2 => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::relvortstage3 => null()
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::relvortstage4 => null()
logical(klog), save betaplanesolvermodule::loginit = .FALSE.
type(logger) betaplanesolvermodule::log
character(len=28), save betaplanesolvermodule::logkey = 'BVESolver'
integer(kint), parameter betaplanesolvermodule::loglevel = DEBUG_LOGGING_LEVEL
character(len=max_string_length) betaplanesolvermodule::logstring
Function/Subroutine Documentation
subroutine betaplanesolvermodule::betaplanevelocity (real(kreal), dimension(:), intent(out) u, real(kreal), dimension(:), intent(out) v, real(kreal), dimension(:), intent(in) x, real(kreal), dimension(:), intent(in) y, real(kreal), dimension(:), intent(in) relVortIn, real(kreal), dimension(:), intent(in) areaIn, logical(klog), dimension(:), intent(in) activemask, type(mpisetup), intent(in) mpiParticles) private
Definition at line 227 of file BetaPlaneSolver.f90.
References numberkindsmodule::numprocs, numberkindsmodule::pi, and numberkindsmodule::procrank.
subroutine betaplanesolvermodule::deleteprivate (type(betaplanesolver), intent(inout) self) private
Definition at line 120 of file BetaPlaneSolver.f90.
final betaplanesolvermodule::betaplanesolver::deleteprivate () final private
Definition at line 55 of file BetaPlaneSolver.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine betaplanesolvermodule::delete::deleteprivate (type(betaplanesolver), intent(inout) self) private
Definition at line 120 of file BetaPlaneSolver.f90.
subroutine betaplanesolvermodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Definition at line 269 of file BetaPlaneSolver.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine betaplanesolvermodule::newprivate (type(betaplanesolver), intent(out) self, type(betaplanemesh), intent(in) betaPlane) private
Definition at line 93 of file BetaPlaneSolver.f90.
References initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, and numberkindsmodule::procrank.
subroutine betaplanesolvermodule::new::newprivate (type(betaplanesolver), intent(out) self, type(betaplanemesh), intent(in) betaPlane) private
Definition at line 93 of file BetaPlaneSolver.f90.
subroutine betaplanesolvermodule::timestepprivate (type(betaplanesolver), intent(inout) self, type(betaplanemesh), intent(inout) betaPlane, real(kreal), intent(in) dt) private
Definition at line 142 of file BetaPlaneSolver.f90.
References betaplanesolvermodule::betaplanevelocity(), and betaplanemeshmodule::setstreamfunctionsonmesh().
subroutine betaplanesolvermodule::timestep::timestepprivate (type(betaplanesolver), intent(inout) self, type(betaplanemesh), intent(inout) betaPlane, real(kreal), intent(in) dt) private
Definition at line 142 of file BetaPlaneSolver.f90.
Variable Documentation
type(logger) betaplanesolvermodule::log private
Definition at line 81 of file BetaPlaneSolver.f90.
logical(klog), save betaplanesolvermodule::loginit = .FALSE. private
Definition at line 80 of file BetaPlaneSolver.f90.
character(len=28), save betaplanesolvermodule::logkey = 'BVESolver' private
Definition at line 82 of file BetaPlaneSolver.f90.
integer(kint), parameter betaplanesolvermodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 83 of file BetaPlaneSolver.f90.
character(len=max_string_length) betaplanesolvermodule::logstring private
Definition at line 84 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::relvortin => null() private
Definition at line 48 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::relvortstage1 => null() private
Definition at line 49 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::relvortstage2 => null() private
Definition at line 50 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::relvortstage3 => null() private
Definition at line 51 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::relvortstage4 => null() private
Definition at line 52 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::xin => null() private
Definition at line 38 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::xstage1 => null() private
Definition at line 39 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::xstage2 => null() private
Definition at line 40 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::xstage3 => null() private
Definition at line 41 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::xstage4 => null() private
Definition at line 42 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::yin => null() private
Definition at line 43 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::ystage1 => null() private
Definition at line 44 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::ystage2 => null() private
Definition at line 45 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::ystage3 => null() private
Definition at line 46 of file BetaPlaneSolver.f90.
real(kreal), dimension(:), pointer betaplanesolvermodule::betaplanesolver::ystage4 => null() private
Definition at line 47 of file BetaPlaneSolver.f90.