LPM: Lagrangian Particle Methods: BIVARInterface
BIVARInterface
Interface and workspace for interpolation of LPM data by the BIVAR package.
Detailed Description
Interface and workspace for interpolation of LPM data by the BIVAR package.
Bivar performs its interpolation using quintic Hermite polynomials on triangles. Derivatives are estimated as described in reference 2. It must either build its own Delaunay triangulation of all LPM particles, or, if used with a triangular PolyMesh2d object, the native LPM triangulation may be used.
The BIVAR package is due to H. Akima and can be downloaded from the ACM TOMS web page. LPM uses the updated Fortran 90 version provided by Jeff Burkhardt.
The complete description of the BIVAR package may be found in
H. Akima, A method of bivariate interpolation and smooth surface fitting for values given at irregularly distributed data points, Office of Telecommunications Report OT 75:70, U. S. Dept. of Commerce, 1975.
H. Akima, A method of bivariate interpolation and smooth surface fitting for values given at irregularly distributed data points, ACM TOMS, 4:2, 1978.
H. Akima, On estimating partial derivatives for bivariate interpolation of scattered data, Rocky Mtn. J. Math., 14, 1984.
Data Types
interface bivarinterfacemodule::new
interface bivarinterfacemodule::delete
Functions/Subroutines
final bivarinterfacemodule::bivarinterface::deleteprivate
subroutine bivarinterfacemodule::new::newprivate (self, sourceParticles)
Allocates memory for interpolation of LPM data using the Bivar package.
subroutine bivarinterfacemodule::delete::deleteprivate (self)
Deletes and frees memory associated with a BIVARInterface object.
subroutine bivarinterfacemodule::newprivate (self, sourceParticles)
Allocates memory for interpolation of LPM data using the Bivar package.
subroutine bivarinterfacemodule::deleteprivate (self)
Deletes and frees memory associated with a BIVARInterface object.
subroutine, public bivarinterfacemodule::setbivarmd (self, md)
Resets the value of the Bivar "md" parameter. See bivar.f90 for its definition.
subroutine, public bivarinterfacemodule::interpolatescalar (scalarOut, xOut, yOut, self, sourceParticles, sourceField)
Interpolates a scalar Field from a set of Particles to a set of destination points.
subroutine, public bivarinterfacemodule::interpolatelagparam (lagXOut, lagYOut, xOut, yOut, self, sourceParticles)
Interpolates the Lagrangian coordinates from a set of Particles to a set of destination points.
subroutine, public bivarinterfacemodule::interpolatevector (vecXOut, vecYOut, xOut, yOUt, self, sourceParticles, sourceField)
Interpolates a vector Field from a set of Particles to a set of destination points.
subroutine bivarinterfacemodule::initlogger (aLog, rank)
Initializes a logger for the BIVARInterface module.
Variables
integer(kint), dimension(:),
allocatable bivarinterfacemodule::bivarinterface::intwork
Integer variable workspace, see bivar.f90 for requirements.
real(kreal), dimension(:),
allocatable bivarinterfacemodule::bivarinterface::realwork
Real variable workspace, see bivar.f90 for requirements.
integer(kint) bivarinterfacemodule::bivarinterface::md = 1
Flag to determine state of Delaunay triangulation, see bivar.f90 for definition.
logical(klog), save bivarinterfacemodule::loginit = .FALSE.
type(logger) bivarinterfacemodule::log
character(len=28), save bivarinterfacemodule::logkey = 'Bivar'
integer(kint), parameter bivarinterfacemodule::loglevel = DEBUG_LOGGING_LEVEL
character(len=max_string_length) bivarinterfacemodule::logstring
Function/Subroutine Documentation
subroutine bivarinterfacemodule::deleteprivate (type(bivarinterface), intent(inout) self) private
Deletes and frees memory associated with a BIVARInterface object.
Parameters
[in,out] self Target interpolation interface
Definition at line 96 of file BIVARParticlesInterface.f90.
final bivarinterfacemodule::bivarinterface::deleteprivate () final private
Definition at line 50 of file BIVARParticlesInterface.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine bivarinterfacemodule::delete::deleteprivate (type(bivarinterface), intent(inout) self) private
Deletes and frees memory associated with a BIVARInterface object.
Parameters
[in,out] self Target interpolation interface
Definition at line 96 of file BIVARParticlesInterface.f90.
subroutine bivarinterfacemodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Initializes a logger for the BIVARInterface module.
Output is controlled both by message priority and by MPI Rank
Parameters
aLog Target Logger object
rank Rank of this processor
Definition at line 225 of file BIVARParticlesInterface.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine, public bivarinterfacemodule::interpolatelagparam (real(kreal), dimension(:), intent(inout) lagXOut, real(kreal), dimension(:), intent(inout) lagYOut, real(kreal), dimension(:), intent(in) xOut, real(kreal), dimension(:), intent(in) yOut, type(bivarinterface), intent(inout) self, type(particles), intent(in) sourceParticles)
Interpolates the Lagrangian coordinates from a set of Particles to a set of destination points.
Parameters
[in,out] lagXOut Interpolated Lagrangian x-coordinate values, array must have been allocated prior to calling this routine.
[in,out] lagYOut Interpolated Lagrangian y-coordinate values, array must have been allocated prior to calling this routine.
[in] xOut x-coordinates of destination points
[in] yOut y-coordinates of destination points
[in,out] self Target interpolation interface
[in] sourceParticles Existing Particles
Definition at line 154 of file BIVARParticlesInterface.f90.
References bivarmodule::idbvip().
subroutine, public bivarinterfacemodule::interpolatescalar (real(kreal), dimension(:), intent(inout) scalarOut, real(kreal), dimension(:), intent(in) xOut, real(kreal), dimension(:), intent(in) yOut, type(bivarinterface), intent(inout) self, type(particles), intent(in) sourceParticles, type(field), intent(in) sourceField)
Interpolates a scalar Field from a set of Particles to a set of destination points.
Parameters
[in,out] scalarOut Interpolated scalar values, array must have been allocated prior to calling this routine.
[in] xOut x-coordinates of destination points
[in] yOut y-coordinates of destination points
[in,out] self Target interpolation interface
[in] sourceParticles Existing Particles
[in] sourceField Existing scalar Field
Definition at line 129 of file BIVARParticlesInterface.f90.
References bivarmodule::idbvip().
subroutine, public bivarinterfacemodule::interpolatevector (real(kreal), dimension(:), intent(inout) vecXOut, real(kreal), dimension(:), intent(inout) vecYOut, real(kreal), dimension(:), intent(in) xOut, real(kreal), dimension(:), intent(in) yOUt, type(bivarinterface), intent(inout) self, type(particles), intent(in) sourceParticles, type(field), intent(in) sourceField)
Interpolates a vector Field from a set of Particles to a set of destination points.
Parameters
[in,out] vecXOut Interpolated values of the vector field's x component, array must have been allocated prior to calling this routine.
[in,out] vecYOut Interpolated values of the vector field's y component, array must have been allocated prior to calling this routine.
[in] xOut x-coordinates of destination points
[in] yOut y-coordinates of destination points
[in,out] self Target interpolation interface
[in] sourceParticles Existing Particles
[in] sourceField Existing vector Field
Definition at line 189 of file BIVARParticlesInterface.f90.
References bivarmodule::idbvip().
subroutine bivarinterfacemodule::newprivate (type(bivarinterface), intent(out) self, type(particles), intent(in) sourceParticles) private
Allocates memory for interpolation of LPM data using the Bivar package.
Parameters
[out] self Target interpolation interface
[in] sourceParticles Particles object
Definition at line 84 of file BIVARParticlesInterface.f90.
References initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, and numberkindsmodule::procrank.
subroutine bivarinterfacemodule::new::newprivate (type(bivarinterface), intent(out) self, type(particles), intent(in) sourceParticles) private
Allocates memory for interpolation of LPM data using the Bivar package.
Parameters
[out] self Target interpolation interface
[in] sourceParticles Particles object
Definition at line 84 of file BIVARParticlesInterface.f90.
subroutine, public bivarinterfacemodule::setbivarmd (type(bivarinterface), intent(inout) self, integer(kint), intent(in) md)
Resets the value of the Bivar "md" parameter. See bivar.f90 for its definition.
Parameters
[in,out] self Target interpolation interface
[in] md New parameter value
Definition at line 110 of file BIVARParticlesInterface.f90.
References betaplanemeshmodule::log, betaplanemeshmodule::logkey, and loggermodule::warning_logging_level.
Variable Documentation
integer(kint), dimension(:), allocatable bivarinterfacemodule::bivarinterface::intwork private
Integer variable workspace, see bivar.f90 for requirements.
Definition at line 45 of file BIVARParticlesInterface.f90.
type(logger) bivarinterfacemodule::log private
Definition at line 73 of file BIVARParticlesInterface.f90.
logical(klog), save bivarinterfacemodule::loginit = .FALSE. private
Definition at line 72 of file BIVARParticlesInterface.f90.
character(len=28), save bivarinterfacemodule::logkey = 'Bivar' private
Definition at line 74 of file BIVARParticlesInterface.f90.
integer(kint), parameter bivarinterfacemodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 75 of file BIVARParticlesInterface.f90.
character(len=max_string_length) bivarinterfacemodule::logstring private
Definition at line 76 of file BIVARParticlesInterface.f90.
integer(kint) bivarinterfacemodule::bivarinterface::md = 1 private
Flag to determine state of Delaunay triangulation, see bivar.f90 for definition.
Definition at line 47 of file BIVARParticlesInterface.f90.
real(kreal), dimension(:), allocatable bivarinterfacemodule::bivarinterface::realwork private
Real variable workspace, see bivar.f90 for requirements.
Definition at line 46 of file BIVARParticlesInterface.f90.