LPM: Lagrangian Particle Methods: PlanarSWE
PlanarSWE
Data structure for representing solutions of the shallow water equations in a beta-plane.
Detailed Description
Data structure for representing solutions of the shallow water equations in a beta-plane.
Combines a PolyMesh2d with data Field objects relevant to the shallow water equations.
Solutions are integrated in time using the SWEPlaneSolver module.
In addition to the variables carried by the base Particles object (e.g., physical and Lagrangian coordinates), the BVEMesh data type adds Field structures for relative vorticity \(\zeta(x,y,t) \), divergence \(\delta(x,y,t) \), the materially conserved absolute vorticity \(q(x_0,y_0) \), velocity \(\vec{u}(x,y,t) \) and the fluid depth \(h(x,y,t) \). Users may also specify bottom topography \(\eta_B(x,y) \). These variables are related by the equation
\begin{align} q &= \frac{\zeta + f}{h}, \\ \eta &= \eta_B + h, \end{align}
where \(f = f_0 + \beta y(t) \) is the Coriolis parameter with constants \(f_0 \) and \(\beta \), and \(\eta \) is the fluid surface height.
Illustration of variable definitions used in the shallow water equations.
We again use Green's function for the Poisson equation with free boundaries in the plane to solve the PDE.
Following a discretization by an LPM particle set, we have
\begin{align*} \vec{u}(\vec{x},t) &= \int_{\mathbb{R}^2} \left(\vec{K}_\zeta(\vec{x},\vec{y})\zeta(\vec{y}) + \vec{K}_\delta(\vec{x},\vec{y})\delta(\vec{y})\right)\, dA(\vec{y}), \\ \frac{d\vec{x}}{dt} &= \vec{u}(\vec{x},t), \\ \frac{d\zeta}{dt} &= -\beta \frac{dy}{dt} - (\zeta + f)\delta, \\ \frac{d\delta}{dt} &= f\zeta -\vec{u}\cdot(\nabla\times f\vec{k}) - \nabla\vec{u}:\nabla\vec{u} - g\nabla^2 \eta, \\ \frac{dh}{dt} &= -h\delta, \\ \frac{dA}{dt} &= \delta A, \end{align*}
where the kernels \(\vec{K}_\zeta = -\nabla \times G \) and \(\vec{K}_\delta = \nabla G \) result from applying the appropriate differential operators to the free space Green's function
\[ G(\vec{x},\vec{y}) = \frac{1}{4\pi}\log(|\vec{x}-\vec{y}|^2). \]
The double dot product \(\nabla\vec{u}:\nabla\vec{u}\) is evaluated by again differentiating the kernels \(\vec{K}_\zeta \) and \(\vec{K}_\delta \).
The Laplacian of the fluid surface is evaluated on the particles using Particle Strength Exchange (PSE). See PSEDirectSum for additional details.
Data Types
interface planarswemodule::new
interface planarswemodule::copy
interface planarswemodule::delete
interface planarswemodule::logstats
Functions/Subroutines
final planarswemodule::swemesh::deleteprivate
subroutine planarswemodule::new::newprivate (self, meshSeed, initNest, maxNest, amrLimit, meshRadius, f0, beta, g)
Allocates memory and initializes a planar mesh for solving the shallow water equations.
subroutine planarswemodule::copy::copyprivate (self, other)
Performs a deep copy of a SWE mesh.
subroutine planarswemodule::delete::deleteprivate (self)
Deletes and frees memory associated with a SWEMesh.
subroutine planarswemodule::logstats::logstatsprivate (self, aLog)
subroutine planarswemodule::newprivate (self, meshSeed, initNest, maxNest, amrLimit, meshRadius, f0, beta, g)
Allocates memory and initializes a planar mesh for solving the shallow water equations.
subroutine planarswemodule::copyprivate (self, other)
Performs a deep copy of a SWE mesh.
subroutine planarswemodule::deleteprivate (self)
Deletes and frees memory associated with a SWEMesh.
subroutine planarswemodule::swecomputevelocity (self, velocity, x, y, relVort, divergence, area)
Computes the fluid velocity at each particle in parallel using direct summation.
subroutine planarswemodule::logstatsprivate (self, aLog)
subroutine planarswemodule::setcoriolis (self, f0, beta)
subroutine, public planarswemodule::addtracers (self, nTracers, tracerDims)
subroutine, public planarswemodule::outputtovtkfile (self, filename)
subroutine planarswemodule::outputtotomatlabmfile (self, filename)
subroutine, public planarswemodule::setinitialvorticityonmesh (self, vorticityFn)
subroutine, public planarswemodule::setinitialdivergenceonmesh (self, divergenceFn)
subroutine, public planarswemodule::setinitialhonmesh (self, hFn)
subroutine, public planarswemodule::setbottomheightonmesh (self, depthFn)
subroutine, public planarswemodule::setinitialvelocityonmesh (self, velFn)
subroutine, public planarswemodule::setinitialpotvortonmesh (self)
subroutine planarswemodule::initlogger (aLog, rank)
Variables
type(polymesh2d) planarswemodule::swemesh::mesh
type(field) planarswemodule::swemesh::relvort
type(field) planarswemodule::swemesh::potvort
type(field) planarswemodule::swemesh::divergence
type(field) planarswemodule::swemesh::velocity
type(field) planarswemodule::swemesh::h
type(field) planarswemodule::swemesh::hbottom
type(field), dimension(:), pointer planarswemodule::swemesh::tracers => null()
real(kreal) planarswemodule::swemesh::f0 = 0.0_kreal
real(kreal) planarswemodule::swemesh::beta = 0.0_kreal
real(kreal) planarswemodule::swemesh::g = 0.0_kreal
real(kreal) planarswemodule::swemesh::pseeps = 0.0_kreal
type(mpisetup) planarswemodule::swemesh::mpiparticles
logical(klog), save planarswemodule::loginit = .FALSE.
type(logger) planarswemodule::log
character(len=28), save planarswemodule::logkey = 'SWE'
integer(kint), parameter planarswemodule::loglevel = DEBUG_LOGGING_LEVEL
Function/Subroutine Documentation
subroutine, public planarswemodule::addtracers (type(swemesh), intent(inout) self, integer(kint), intent(in) nTracers, integer(kint), dimension(:), intent(in) tracerDims)
Definition at line 267 of file PlanarSWE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, and betaplanemeshmodule::logkey.
subroutine planarswemodule::copyprivate (type(swemesh), intent(inout) self, type(swemesh), intent(in) other) private
Performs a deep copy of a SWE mesh.
Todo:
This subroutine is incomplete.
Warning
Cannot do remesh/remap until it is done.
Definition at line 184 of file PlanarSWE.f90.
subroutine planarswemodule::copy::copyprivate (type(swemesh), intent(inout) self, type(swemesh), intent(in) other) private
Performs a deep copy of a SWE mesh.
Todo:
This subroutine is incomplete.
Warning
Cannot do remesh/remap until it is done.
Definition at line 184 of file PlanarSWE.f90.
subroutine planarswemodule::deleteprivate (type(swemesh), intent(inout) self) private
Deletes and frees memory associated with a SWEMesh.
Parameters
[in,out] self SWEMesh
Definition at line 191 of file PlanarSWE.f90.
subroutine planarswemodule::delete::deleteprivate (type(swemesh), intent(inout) self) private
Deletes and frees memory associated with a SWEMesh.
Parameters
[in,out] self SWEMesh
Definition at line 191 of file PlanarSWE.f90.
final planarswemodule::swemesh::deleteprivate () final private
Definition at line 88 of file PlanarSWE.f90.
References betaplanemeshmodule::betaplanemesh::deleteprivate().
subroutine planarswemodule::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank) private
Definition at line 421 of file PlanarSWE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, and betaplanemeshmodule::loglevel.
subroutine planarswemodule::logstatsprivate (type(swemesh), intent(in) self, type(logger), intent(inout) aLog) private
Definition at line 245 of file PlanarSWE.f90.
References loggermodule::trace_logging_level.
subroutine planarswemodule::logstats::logstatsprivate (type(swemesh), intent(in) self, type(logger), intent(inout) aLog) private
Definition at line 245 of file PlanarSWE.f90.
subroutine planarswemodule::newprivate (type(swemesh), intent(out) self, integer(kint), intent(in) meshSeed, integer(kint), intent(in) initNest, integer(kint), intent(in) maxNest, integer(kint), intent(in) amrLimit, real(kreal), intent(in) meshRadius, real(kreal), intent(in) f0, real(kreal), intent(in) beta, real(kreal), intent(in) g) private
Allocates memory and initializes a planar mesh for solving the shallow water equations.
Parameters
[out] self new SWE mesh
[in] meshSeed mesh seed integer, as defined in NumberKinds
[in] initNest initial level of uniform refinement
[in] maxNest maximum level of uniform refinment
[in] amrLimit maximum number of times an individual face can be divided beyond initNest
[in] meshRadius maximum extent of mesh from the origin
[in] f0 constant for Coriolis approximation with the beta plane
[in] beta constant for Coriolis approximation with the beta plane
[in] g gravitational constant
Definition at line 150 of file PlanarSWE.f90.
References loggermodule::error_logging_level, initlogger(), betaplanemeshmodule::log, betaplanemeshmodule::loginit, betaplanemeshmodule::logkey, numberkindsmodule::numprocs, numberkindsmodule::procrank, numberkindsmodule::quad_rect_seed, and numberkindsmodule::tri_hex_seed.
subroutine planarswemodule::new::newprivate (type(swemesh), intent(out) self, integer(kint), intent(in) meshSeed, integer(kint), intent(in) initNest, integer(kint), intent(in) maxNest, integer(kint), intent(in) amrLimit, real(kreal), intent(in) meshRadius, real(kreal), intent(in) f0, real(kreal), intent(in) beta, real(kreal), intent(in) g) private
Allocates memory and initializes a planar mesh for solving the shallow water equations.
Parameters
[out] self new SWE mesh
[in] meshSeed mesh seed integer, as defined in NumberKinds
[in] initNest initial level of uniform refinement
[in] maxNest maximum level of uniform refinment
[in] amrLimit maximum number of times an individual face can be divided beyond initNest
[in] meshRadius maximum extent of mesh from the origin
[in] f0 constant for Coriolis approximation with the beta plane
[in] beta constant for Coriolis approximation with the beta plane
[in] g gravitational constant
Definition at line 150 of file PlanarSWE.f90.
subroutine planarswemodule::outputtotomatlabmfile (type(swemesh), intent(in) self, character(len=*), intent(in) filename) private
Definition at line 330 of file PlanarSWE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, and numberkindsmodule::write_unit_1.
subroutine, public planarswemodule::outputtovtkfile (type(swemesh), intent(in) self, character(len=*), intent(in) filename)
Definition at line 286 of file PlanarSWE.f90.
References loggermodule::error_logging_level, betaplanemeshmodule::log, betaplanemeshmodule::logkey, numberkindsmodule::write_unit_1, facesmodule::writefaceareatovtkcelldata(), facesmodule::writefacestovtkpolygons(), fieldmodule::writefieldtovtkpointdata(), outputwritermodule::writevtkfileheader(), particlesmodule::writevtklagcoords(), and outputwritermodule::writevtkpointdatasectionheader().
subroutine, public planarswemodule::setbottomheightonmesh (type(swemesh), intent(inout) self, procedure(scalarfnof2dspace) depthFn)
Definition at line 376 of file PlanarSWE.f90.
subroutine planarswemodule::setcoriolis (type(swemesh), intent(inout) self, real(kreal), intent(in) f0, real(kreal), intent(in) beta) private
Definition at line 260 of file PlanarSWE.f90.
subroutine, public planarswemodule::setinitialdivergenceonmesh (type(swemesh), intent(inout) self, procedure(scalarfnof2dspace) divergenceFn)
Definition at line 354 of file PlanarSWE.f90.
References fieldmodule::insertscalartofield().
subroutine, public planarswemodule::setinitialhonmesh (type(swemesh), intent(inout) self, procedure(scalarfnof2dspace) hFn)
Definition at line 365 of file PlanarSWE.f90.
References fieldmodule::insertscalartofield().
subroutine, public planarswemodule::setinitialpotvortonmesh (type(swemesh), intent(inout) self)
Definition at line 399 of file PlanarSWE.f90.
References fieldmodule::insertscalartofield().
subroutine, public planarswemodule::setinitialvelocityonmesh (type(swemesh), intent(inout) self, procedure(vectorfnof2dspace) velFn)
Definition at line 388 of file PlanarSWE.f90.
References fieldmodule::insertvectortofield().
subroutine, public planarswemodule::setinitialvorticityonmesh (type(swemesh), intent(inout) self, procedure(scalarfnof2dspace) vorticityFn)
Definition at line 343 of file PlanarSWE.f90.
References fieldmodule::insertscalartofield().
subroutine planarswemodule::swecomputevelocity (type(swemesh), intent(inout) self, type(field), intent(inout) velocity, real(kreal), dimension(:), intent(in) x, real(kreal), dimension(:), intent(in) y, real(kreal), dimension(:), intent(in) relVort, real(kreal), dimension(:), intent(in) divergence, real(kreal), dimension(:), intent(in) area) private
Computes the fluid velocity at each particle in parallel using direct summation.
Todo:
Verify whether or not this subroutine is ever used.
Definition at line 214 of file PlanarSWE.f90.
References numberkindsmodule::numprocs, numberkindsmodule::pi, numberkindsmodule::procrank, and fieldmodule::setfieldtozero().
Variable Documentation
real(kreal) planarswemodule::swemesh::beta = 0.0_kreal private
Definition at line 83 of file PlanarSWE.f90.
type(field) planarswemodule::swemesh::divergence private
Definition at line 77 of file PlanarSWE.f90.
real(kreal) planarswemodule::swemesh::f0 = 0.0_kreal private
Definition at line 82 of file PlanarSWE.f90.
real(kreal) planarswemodule::swemesh::g = 0.0_kreal private
Definition at line 84 of file PlanarSWE.f90.
type(field) planarswemodule::swemesh::h private
Definition at line 79 of file PlanarSWE.f90.
type(field) planarswemodule::swemesh::hbottom private
Definition at line 80 of file PlanarSWE.f90.
type(logger) planarswemodule::log private
Definition at line 113 of file PlanarSWE.f90.
logical(klog), save planarswemodule::loginit = .FALSE. private
Definition at line 112 of file PlanarSWE.f90.
character(len=28), save planarswemodule::logkey = 'SWE' private
Definition at line 114 of file PlanarSWE.f90.
integer(kint), parameter planarswemodule::loglevel = DEBUG_LOGGING_LEVEL private
Definition at line 115 of file PlanarSWE.f90.
type(polymesh2d) planarswemodule::swemesh::mesh private
Definition at line 74 of file PlanarSWE.f90.
type(mpisetup) planarswemodule::swemesh::mpiparticles private
Definition at line 86 of file PlanarSWE.f90.
type(field) planarswemodule::swemesh::potvort private
Definition at line 76 of file PlanarSWE.f90.
real(kreal) planarswemodule::swemesh::pseeps = 0.0_kreal private
Definition at line 85 of file PlanarSWE.f90.
type(field) planarswemodule::swemesh::relvort private
Definition at line 75 of file PlanarSWE.f90.
type(field), dimension(:), pointer planarswemodule::swemesh::tracers => null() private
Definition at line 81 of file PlanarSWE.f90.
type(field) planarswemodule::swemesh::velocity private
Definition at line 78 of file PlanarSWE.f90.